Symmetric NDT: SNDTCell Class Reference
SNDTCell Class Reference
#include <sndt_cell.h>
Public Types
enum CellType {
kNotInit, kRegular, kRescale, kAssign,
kNoPoints, kInvalid
}
Cell types.
Public Member Functions
SNDTCell ()
virtual void ComputeGaussian () override
Compute gaussian.
virtual bool HasGaussian () const override
Check if the cell has a valid gaussian.
virtual std::string ToString () const override
Convert the information of this cell to a string.
void AddNormal (const Eigen::Vector2d &normal)
Add a normal to this cell.
CellType GetPCellType () const
CellType GetNCellType () const
double GetRescaleRatio () const
bool GetNHasGaussian () const
Eigen::Vector2d GetNormalMean () const
Eigen::Matrix2d GetNormalCov () const
Eigen::Vector2d GetNormalEvals () const
Eigen::Matrix2d GetNormalEvecs () const
std::vector< Eigen::Vector2d > GetNormals () const
void SetPCellType (CellType pcelltype)
void SetNCellType (CellType ncelltype)
void SetRescaleRatio (double rescale_ratio)
void SetNHasGaussian (bool nhasgaussian)
void SetNormalMean (const Eigen::Vector2d &mean)
void SetNormalCov (const Eigen::Matrix2d &cov)
void SetNormalEvals (const Eigen::Vector2d &evals)
void SetNormalEvecs (const Eigen::Matrix2d &evecs)
void SetNormals (const std::vector< Eigen::Vector2d > &normals)
Public Member Functions inherited from CellInterface
CellInterface ()
Construct a new CellInterface object.
virtual ~CellInterface ()=default
Declare destructor virtual in polymorphic base class.
void AddPoint (const Eigen::Vector2d &point)
Add a point to this cell.
void AddPointWithCovariance (const Eigen::Vector2d &point, const Eigen::Matrix2d &covariance)
Add a point and its covariance to this cell.
Eigen::MatrixXd GetPointsMatrix () const
Get the Points Matrix object.
int GetN () const
bool GetPHasGaussian () const
double GetSkewRad () const
double GetSize () const
Eigen::Vector2d GetCenter () const
Eigen::Vector2d GetPointMean () const
Eigen::Matrix2d GetPointCov () const
Eigen::Vector2d GetPointEvals () const
Eigen::Matrix2d GetPointEvecs () const
std::vector< Eigen::Vector2d > GetPoints () const
std::vector< Eigen::Matrix2d > GetPointCovs () const
void SetN (int n)
void SetPHasGaussian (bool phasgaussian)
void SetSkewRad (double skew_rad)
void SetSize (double size)
void SetCenter (const Eigen::Vector2d &center)
void SetPointMean (const Eigen::Vector2d &mean)
void SetPointCov (const Eigen::Matrix2d &cov)
void SetPointEvals (const Eigen::Vector2d &evals)
void SetPointEvecs (const Eigen::Matrix2d &evecs)
void SetPoints (const std::vector< Eigen::Vector2d > &points)
void SetPointCovs (const std::vector< Eigen::Matrix2d > &point_covs)
Additional Inherited Members
Protected Attributes inherited from CellInterface
int n_
bool phasgaussian_
double skew_rad_
double size_
Eigen::Vector2d center_
Eigen::Vector2d pmean_
Eigen::Vector2d pevals_
Eigen::Matrix2d pcov_
Eigen::Matrix2d pevecs_
std::vector< Eigen::Vector2d > points_
std::vector< Eigen::Matrix2d > point_covs_
Member Enumeration Documentation
CellType
enum SNDTCell::CellType
Cell types.
Enumerator
kNotInit
Covariance is not computed yet
kRegular
Covariance is computed well
kRescale
Covariance is rescaled
kAssign
Covariance is assigned
kNoPoints
Covariance is not computed because no points
kInvalid
Covariance has negative eigenvalues
Constructor & Destructor Documentation
SNDTCell()
SNDTCell::SNDTCell ()
Member Function Documentation
AddNormal()
void SNDTCell::AddNormal (const Eigen::Vector2d & normal) inline
Add a normal to this cell.
Parameters
normal Normal (x, y) to be added
Warning
This function does not check whether the normal is normalized or not. The caller should take responsibility for calling this function.
Referenced by SNDTMap::LoadPointsAndNormals(), and SNDTMap::LoadPointsWithCovariancesAndNormals().
ComputeGaussian()
void SNDTCell::ComputeGaussian () override virtual
Compute gaussian.
Precondition
The size of points_, point_covs_, and normals_ are the same
This function updates mean and covariance of this cell, along with its cell type. Rescaling covariance is performed if necessary.
Implements CellInterface.
GetNCellType()
CellType SNDTCell::GetNCellType () const inline
GetNHasGaussian()
bool SNDTCell::GetNHasGaussian () const inline
Referenced by MarkerArrayOfSNDTCell(), and MarkerArrayOfSNDTCell2().
GetNormalCov()
Eigen::Matrix2d SNDTCell::GetNormalCov () const inline
Referenced by MarkerArrayOfSNDTCell(), MarkerArrayOfSNDTCell2(), SNDTCostFunctor::MeanAndCov(), SNDTCostFunctor::operator()(), and SNDTCostFunctor::Score().
GetNormalEvals()
Eigen::Vector2d SNDTCell::GetNormalEvals () const inline
GetNormalEvecs()
Eigen::Matrix2d SNDTCell::GetNormalEvecs () const inline
GetNormalMean()
Eigen::Vector2d SNDTCell::GetNormalMean () const inline
Referenced by MarkerArrayOfSNDTCell(), MarkerArrayOfSNDTCell2(), SNDTCostFunctor::MeanAndCov(), SNDTCostFunctor::operator()(), and SNDTCostFunctor::Score().
GetNormals()
std::vector<Eigen::Vector2d> SNDTCell::GetNormals () const inline
GetPCellType()
CellType SNDTCell::GetPCellType () const inline
GetRescaleRatio()
double SNDTCell::GetRescaleRatio () const inline
HasGaussian()
bool SNDTCell::HasGaussian () const override virtual
Check if the cell has a valid gaussian.
Implements CellInterface.
SetNCellType()
void SNDTCell::SetNCellType (CellType ncelltype) inline
SetNHasGaussian()
void SNDTCell::SetNHasGaussian (bool nhasgaussian) inline
SetNormalCov()
void SNDTCell::SetNormalCov (const Eigen::Matrix2d & cov) inline
SetNormalEvals()
void SNDTCell::SetNormalEvals (const Eigen::Vector2d & evals) inline
SetNormalEvecs()
void SNDTCell::SetNormalEvecs (const Eigen::Matrix2d & evecs) inline
SetNormalMean()
void SNDTCell::SetNormalMean (const Eigen::Vector2d & mean) inline
SetNormals()
void SNDTCell::SetNormals (const std::vector< Eigen::Vector2d > & normals) inline
SetPCellType()
void SNDTCell::SetPCellType (CellType pcelltype) inline
SetRescaleRatio()
void SNDTCell::SetRescaleRatio (double rescale_ratio) inline
ToString()
std::string SNDTCell::ToString () const override virtual
Convert the information of this cell to a string.
Implements CellInterface.
The documentation for this class was generated from the following files:
sndt_cell.h
sndt_cell.cc