Symmetric NDT: PCA2D Class Reference
PCA2D Class Reference
#include <PCA2D.h>
Public Member Functions
PCA2D ()
Empty constructor.
void initCompute ()
Perform the PCA computation.
void setInputCloud (const ConstPtrCloud &cloud)
Provide a input cloud pointer to deal with.
void setIndices (const pcl::PointIndices &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const pcl::PointIndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const pcl::PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const boost::shared_ptr< std::vector< int >> &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const std::vector< int > &indices)
Provide a pointer to the vector of indices that represents the input data.
Eigen::Vector2f getMean ()
Return the mean computed, if PCA isn't computed, it will perform it.
Eigen::Matrix2f getEigenVectors ()
Return the eigen Vector in Eigen Matrix , if PCA isn't computed, it will perform it.
Eigen::Vector2f getEigenValues ()
Return the eigen Vector in Eigen Matrix , if PCA isn't computed, it will perform it.
void project (const Point &input, Point &projection)
Project point into PCA cartesian system.
void project (const ConstPtrCloud &in_cloud, PtrCloud &out_cloud)
Project input cloud into PCA cartesian system.
PCA2D ()
void initCompute ()
void setInputCloud (const ConstPtrCloud &cloud)
void setIndices (const pcl::PointIndices &indices)
void setIndices (const pcl::PointIndicesPtr &indices)
void setIndices (const pcl::PointIndicesConstPtr &indices)
void setIndices (const boost::shared_ptr< std::vector< int >> &indices)
void setIndices (const std::vector< int > &indices)
Eigen::Vector2f getMean ()
Eigen::Matrix2f getEigenVectors ()
Eigen::Vector2f getEigenValues ()
void project (const Point &input, Point &projection)
void project (const ConstPtrCloud &in_cloud, PtrCloud &out_cloud)
Constructor & Destructor Documentation
PCA2D() [1/2]
PCA2D::PCA2D () inline
Empty constructor.
PCA2D() [2/2]
PCA2D::PCA2D () inline
Member Function Documentation
getEigenValues() [1/2]
Eigen::Vector2f PCA2D::getEigenValues () inline
Return the eigen Vector in Eigen Matrix , if PCA isn't computed, it will perform it.
Returns
The EigenVectors matrix from PCA algorithm.
Referenced by Normal2dEstimation::setIndices().
getEigenValues() [2/2]
Eigen::Vector2f PCA2D::getEigenValues () inline
getEigenVectors() [1/2]
Eigen::Matrix2f PCA2D::getEigenVectors () inline
Return the eigen Vector in Eigen Matrix , if PCA isn't computed, it will perform it.
Returns
The EigenVectors matrix from PCA algorithm.
Referenced by Normal2dEstimation::setIndices().
getEigenVectors() [2/2]
Eigen::Matrix2f PCA2D::getEigenVectors () inline
getMean() [1/2]
Eigen::Vector2f PCA2D::getMean () inline
Return the mean computed, if PCA isn't computed, it will perform it.
Returns
The mean vector from PCA algorithm.
getMean() [2/2]
Eigen::Vector2f PCA2D::getMean () inline
initCompute() [1/2]
void PCA2D::initCompute () inline
initCompute() [2/2]
void PCA2D::initCompute ()
Perform the PCA computation.
Referenced by getEigenValues(), getEigenVectors(), getMean(), and PCA2D().
project() [1/4]
void PCA2D::project (const Point & input, Point & projection)
Project point into PCA cartesian system.
Parameters
input Point to project.
projection Point to fill with projection.
Referenced by getEigenValues(), and project().
project() [2/4]
void PCA2D::project (const Point & input, Point & projection) inline
project() [3/4]
void PCA2D::project (const ConstPtrCloud & in_cloud, PtrCloud & out_cloud)
Project input cloud into PCA cartesian system.
Parameters
input cloud with points to project.
projection Cloud to fill with projected points.
project() [4/4]
void PCA2D::project (const ConstPtrCloud & in_cloud, PtrCloud & out_cloud) inline
setIndices() [1/10]
void PCA2D::setIndices (const pcl::PointIndices & indices)
Provide a pointer to the vector of indices that represents the input data.
Parameters
indices indices a pointer to the indices that represent the input data.
Referenced by PCA2D(), and Normal2dEstimation::setIndices().
setIndices() [2/10]
void PCA2D::setIndices (const pcl::PointIndicesPtr & indices)
Provide a pointer to the vector of indices that represents the input data.
Parameters
indices indices a pointer to the indices that represent the input data.
setIndices() [3/10]
void PCA2D::setIndices (const pcl::PointIndicesConstPtr & indices)
Provide a pointer to the vector of indices that represents the input data.
Parameters
indices indices a pointer to the indices that represent the input data.
setIndices() [4/10]
void PCA2D::setIndices (const boost::shared_ptr< std::vector< int >> & indices)
Provide a pointer to the vector of indices that represents the input data.
Parameters
indices indices a pointer to the indices that represent the input data.
setIndices() [5/10]
void PCA2D::setIndices (const pcl::PointIndices & indices) inline
setIndices() [6/10]
void PCA2D::setIndices (const std::vector< int > & indices)
Provide a pointer to the vector of indices that represents the input data.
Parameters
indices indices a pointer to the indices that represent the input data.
setIndices() [7/10]
void PCA2D::setIndices (const pcl::PointIndicesPtr & indices) inline
setIndices() [8/10]
void PCA2D::setIndices (const pcl::PointIndicesConstPtr & indices) inline
setIndices() [9/10]
void PCA2D::setIndices (const boost::shared_ptr< std::vector< int >> & indices) inline
setIndices() [10/10]
void PCA2D::setIndices (const std::vector< int > & indices) inline
setInputCloud() [1/2]
void PCA2D::setInputCloud (const ConstPtrCloud & cloud)
Provide a input cloud pointer to deal with.
Parameters
cloud Cloud to deal with.
Referenced by PCA2D(), and Normal2dEstimation::setIndices().
setInputCloud() [2/2]
void PCA2D::setInputCloud (const ConstPtrCloud & cloud) inline
The documentation for this class was generated from the following files:
PCA2D.h
PCA2D.hpp