Symmetric NDT: common_utils.hpp File Reference
common_utils.hpp File Reference
#include <bits/stdc++.h>
#include <ros/ros.h>
Namespaces
common
Macros
#define APATH(name) "/home/ee904/Desktop/HuaTsai/NormalNDT/Analysis/"#name
Functions
void dprintf (const char *format,...)
template<typename T >
void common::SerializationInput (const std::string &filepath, T &msg)
template<typename T >
void common::SerializationOutput (const std::string &filepath, const T &msg)
std::vector< std::string > common::GetDataPath (std::string data)
Macro Definition Documentation
APATH
#define APATH (name) "/home/ee904/Desktop/HuaTsai/NormalNDT/Analysis/"#name
Referenced by main().
Function Documentation
dprintf()
void dprintf (const char * format, ...)
Referenced by trimesh::find_overlap(), trimesh::iou(), trimesh::TriMesh::need_across_edge(), trimesh::TriMesh::need_adjacentfaces(), trimesh::TriMesh::need_bbox(), trimesh::TriMesh::need_bsphere(), trimesh::TriMesh::need_curvatures(), trimesh::TriMesh::need_dcurv(), trimesh::TriMesh::need_neighbors(), trimesh::TriMesh::need_normals(), trimesh::TriMesh::need_tstrips(), trimesh::normals_from_points(), and trimesh::TriMesh::unpack_tstrips().