Symmetric NDT: wrapper.hpp File Reference
pclmatch/include/pclmatch/wrapper.hpp File Reference
#include <bits/stdc++.h>
#include <pcl/pcl_config.h>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/registration/gicp.h>
#include <pcl/registration/icp.h>
#include <pcl/registration/icp_nl.h>
#include <pcl/registration/ndt_2d.h>
#include <pcl/registration/transformation_estimation_2D.h>
#include <pcl/filters/filter.h>
#include <TriMesh.h>
#include <ICP.h>
#include <pcl/registration/transformation_estimation_symmetric_point_to_plane_lls.h>
#include "normal2d/Normal2dEstimation.hpp"
#include "common/common.h"
Typedefs
typedef pcl::registration::DefaultConvergenceCriteria< float >::ConvergenceState State
Enumerations
enum ConvergeState {
NOT_CONVERGED, ITERATIONS, TRANSFORM, ABS_MSE,
REL_MSE, NO_CORRESPONDENCES, FAILURE_AFTER_MAX_ITERATIONS
}
Functions
enum ConvergeState FromPCLState (State state)
pcl::PointCloud< pcl::PointXYZ > PCLFromMatrixXd (const Eigen::MatrixXd &mtx)
Eigen::MatrixXd MatrixXdFromPCL (const pcl::PointCloud< pcl::PointXYZ > &pc)
Eigen::MatrixXd MatrixXdFromPCL (pcl::PointCloud< pcl::PointXYZ >::Ptr pc)
template<typename PointCloudPtrType >
void ComputeNormals (pcl::PointCloud< pcl::PointXYZ >::Ptr pc, double radius, PointCloudPtrType normals)
void ComputeNormalsAndJoin (pcl::PointCloud< pcl::PointXYZ >::Ptr pc, double radius, pcl::PointCloud< pcl::PointNormal >::Ptr output)
void RemoveNaN (pcl::PointCloud< pcl::PointNormal >::Ptr pc)
void RemoveNaNAndInf (pcl::PointCloud< pcl::PointNormal >::Ptr pc)
Eigen::Matrix3d Matrix3dFromXForm (const xform &xf)
void DoSICP (common::MatchPackage &mp, const vector< double > &params)
void DoPCLSICP (common::MatchPackage &mp, const vector< double > &params)
TriMesh * MakeMesh (const MatrixXd &data, const vector< double > &params)
Typedef Documentation
State
typedef pcl::registration::DefaultConvergenceCriteria<float>::ConvergenceState State
Enumeration Type Documentation
ConvergeState
enum ConvergeState
Enumerator
NOT_CONVERGED
ITERATIONS
TRANSFORM
ABS_MSE
REL_MSE
NO_CORRESPONDENCES
FAILURE_AFTER_MAX_ITERATIONS
Function Documentation
ComputeNormals()
template<typename PointCloudPtrType > void ComputeNormals (pcl::PointCloud< pcl::PointXYZ >::Ptr pc, double radius, PointCloudPtrType normals)
Referenced by ComputeNormalsAndJoin(), and MakeMap().
ComputeNormalsAndJoin()
void ComputeNormalsAndJoin (pcl::PointCloud< pcl::PointXYZ >::Ptr pc, double radius, pcl::PointCloud< pcl::PointNormal >::Ptr output)
Referenced by DoPCLSICP(), DoSICP(), and MakeMesh().
DoPCLSICP()
void DoPCLSICP (common::MatchPackage & mp, const vector< double > & params)
DoSICP()
void DoSICP (common::MatchPackage & mp, const vector< double > & params)
Referenced by main().
FromPCLState()
enum ConvergeState FromPCLState (State state)
MakeMesh()
TriMesh* MakeMesh (const MatrixXd & data, const vector< double > & params)
Parameters
data
params (radius)
Referenced by main().
Matrix3dFromXForm()
Eigen::Matrix3d Matrix3dFromXForm (const xform & xf)
Referenced by DoSICP().
MatrixXdFromPCL() [1/2]
Eigen::MatrixXd MatrixXdFromPCL (const pcl::PointCloud< pcl::PointXYZ > & pc)
Referenced by main().
MatrixXdFromPCL() [2/2]
Eigen::MatrixXd MatrixXdFromPCL (pcl::PointCloud< pcl::PointXYZ >::Ptr pc)
PCLFromMatrixXd()
pcl::PointCloud<pcl::PointXYZ> PCLFromMatrixXd (const Eigen::MatrixXd & mtx)
Referenced by DoPCLSICP(), and DoSICP().
RemoveNaN()
void RemoveNaN (pcl::PointCloud< pcl::PointNormal >::Ptr pc)
Referenced by DoSICP().
RemoveNaNAndInf()
void RemoveNaNAndInf (pcl::PointCloud< pcl::PointNormal >::Ptr pc)
Referenced by MakeMesh().