Symmetric NDT: Normal2dEstimation Class Reference
Normal2dEstimation Class Reference
Normal2dEstimation estimate local straight line at each points using it neighbour. Contrary to native normal estimation on PCL lib, it works only on 2D points cloud.
#include <Normal2dEstimation.h>
Public Member Functions
Normal2dEstimation (double search_radius=0.0, unsigned int k=0)
Classic constructor, you can directly setup parameters using constructor arguments.
void compute (const PtrCloud &normal_cloud) const
Compute on each point the normal estimation.
void compute (const pcl::PointCloud< pcl::Normal >::Ptr &normal_cloud) const
Compute on each point the normal estimation.
void setViewPoint (const Point &origin)
Setup the view point.
Point getViewPoint () const
return the current view point.
void setRadiusSearch (double search_radius)
Setup a search radius for normal estimation on each point.
double getRadiusSearch () const
Prove current radius for normal estimation.
void setSearchMethod (const PtrkdTree &kdtree)
Provide a pointer to the search object.
void setKSearch (unsigned int k)
Setup the cluster size for normal estimation.
int getKSearch () const
Provide the current k constant.
void setInputCloud (const ConstPtrCloud &cloud)
Provide a input cloud pointer to deal with.
ConstPtrCloud getInputCloud () const
Provide the current cloud set as input.
void setIndices (const pcl::PointIndices::Ptr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const pcl::PointIndices::ConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
Normal2dEstimation (double search_radius=0.0, unsigned int k=0)
void compute (const PtrCloud &normal_cloud) const
void compute (const pcl::PointCloud< pcl::Normal >::Ptr &normal_cloud) const
void setViewPoint (const Point &origin)
Point getViewPoint () const
void setRadiusSearch (double search_radius)
double getRadiusSearch () const
void setSearchMethod (const PtrkdTree &kdtree)
void setKSearch (unsigned int k)
int getKSearch () const
void setInputCloud (const ConstPtrCloud &cloud)
ConstPtrCloud getInputCloud () const
void setIndices (const pcl::PointIndices::Ptr &indices)
void setIndices (const pcl::PointIndices::ConstPtr &indices)
Detailed Description
Normal2dEstimation estimate local straight line at each points using it neighbour. Contrary to native normal estimation on PCL lib, it works only on 2D points cloud.
Note
This class use 3D points cloud but ignore all z components. So make sure you have all your points on z=0 plan.
Constructor & Destructor Documentation
Normal2dEstimation() [1/2]
Normal2dEstimation::Normal2dEstimation (double search_radius = 0.0, unsigned int k = 0) inline
Classic constructor, you can directly setup parameters using constructor arguments.
Parameters
search_radius If different from zero, the normal estimation will use the radius to find out which points it take for line estimation.
k If different from zero, the normal estimation will find the kth closest points for computing line estimation.
Normal2dEstimation() [2/2]
Normal2dEstimation::Normal2dEstimation (double search_radius = 0.0, unsigned int k = 0) inline
Member Function Documentation
compute() [1/4]
void Normal2dEstimation::compute (const PtrCloud & normal_cloud) const inline
compute() [2/4]
void Normal2dEstimation::compute (const PtrCloud & normal_cloud) const
Compute on each point the normal estimation.
Parameters
normal_cloud Normal cloud to fill with normal estimation result.
Referenced by ComputeNormals(), and Normal2dEstimation().
compute() [3/4]
void Normal2dEstimation::compute (const pcl::PointCloud< pcl::Normal >::Ptr & normal_cloud) const
Compute on each point the normal estimation.
Parameters
normal_cloud Normal cloud to fill with normal estimation result.
compute() [4/4]
void Normal2dEstimation::compute (const pcl::PointCloud< pcl::Normal >::Ptr & normal_cloud) const inline
getInputCloud() [1/2]
ConstPtrCloud Normal2dEstimation::getInputCloud () const inline
Provide the current cloud set as input.
Returns
A pointer to current input cloud.
getInputCloud() [2/2]
ConstPtrCloud Normal2dEstimation::getInputCloud () const inline
getKSearch() [1/2]
int Normal2dEstimation::getKSearch () const inline
Provide the current k constant.
Returns
k constant.
getKSearch() [2/2]
int Normal2dEstimation::getKSearch () const inline
getRadiusSearch() [1/2]
double Normal2dEstimation::getRadiusSearch () const inline
Prove current radius for normal estimation.
Returns
Current search radius.
getRadiusSearch() [2/2]
double Normal2dEstimation::getRadiusSearch () const inline
getViewPoint() [1/2]
Point Normal2dEstimation::getViewPoint () const inline
return the current view point.
getViewPoint() [2/2]
Point Normal2dEstimation::getViewPoint () const inline
setIndices() [1/4]
void Normal2dEstimation::setIndices (const pcl::PointIndices::Ptr & indices)
Provide a pointer to the vector of indices that represents the input data.
Parameters
indices indices a pointer to the indices that represent the input data.
Referenced by getInputCloud().
setIndices() [2/4]
void Normal2dEstimation::setIndices (const pcl::PointIndices::ConstPtr & indices)
Provide a pointer to the vector of indices that represents the input data.
Parameters
indices indices a pointer to the indices that represent the input data.
setIndices() [3/4]
void Normal2dEstimation::setIndices (const pcl::PointIndices::Ptr & indices) inline
setIndices() [4/4]
void Normal2dEstimation::setIndices (const pcl::PointIndices::ConstPtr & indices) inline
setInputCloud() [1/2]
void Normal2dEstimation::setInputCloud (const ConstPtrCloud & cloud)
Provide a input cloud pointer to deal with.
Parameters
cloud Cloud to deal with.
Referenced by ComputeNormals(), and getKSearch().
setInputCloud() [2/2]
void Normal2dEstimation::setInputCloud (const ConstPtrCloud & cloud) inline
setKSearch() [1/2]
void Normal2dEstimation::setKSearch (unsigned int k) inline
Setup the cluster size for normal estimation.
Parameters
k cluster size for normal estimation.
setKSearch() [2/2]
void Normal2dEstimation::setKSearch (unsigned int k) inline
setRadiusSearch() [1/2]
void Normal2dEstimation::setRadiusSearch (double search_radius) inline
Setup a search radius for normal estimation on each point.
Parameters
search_radius Max distance for search radius (cartesian distance).
Referenced by ComputeNormals().
setRadiusSearch() [2/2]
void Normal2dEstimation::setRadiusSearch (double search_radius) inline
setSearchMethod() [1/2]
void Normal2dEstimation::setSearchMethod (const PtrkdTree & kdtree) inline
Provide a pointer to the search object.
Parameters
kdtree tree a pointer to the spatial search object.
Referenced by ComputeNormals().
setSearchMethod() [2/2]
void Normal2dEstimation::setSearchMethod (const PtrkdTree & kdtree) inline
setViewPoint() [1/2]
void Normal2dEstimation::setViewPoint (const Point & origin) inline
Setup the view point.
The view points is used in normal orientation purpose. This orientation force all normals to look at view points.
Parameters
origin View point position.
setViewPoint() [2/2]
void Normal2dEstimation::setViewPoint (const Point & origin) inline
The documentation for this class was generated from the following files:
Normal2dEstimation.h
Normal2dEstimation.hpp