Symmetric NDT: ndt_cell.cc File Reference
ndt_cell.cc File Reference
#include "sndt/ndt_cell.h"
#include <bits/stdc++.h>
#include <Eigen/Eigen>
#include <gsl/gsl>
Functions
Vector2d ComputeMean (const vector< Vector2d > &points)
Matrix2d ComputeMean (const vector< Matrix2d > &points)
Matrix2d ComputeCov (const vector< Vector2d > &points, const Vector2d &mean, const Matrix2d &intrinsic=Matrix2d::Zero())
Matrix2d ComputeCov (const vector< Vector2d > &points, const Vector2d &mean, const vector< Matrix2d > &intrinsics)
void ComputeEvalEvec (const Matrix2d &covariance, Vector2d &evals, Matrix2d &evecs)
vector< Vector2d > ExcludeNaNInf (const vector< Vector2d > &points)
vector< Vector2d > RemoveDuplicates (const vector< Vector2d > &points)
pair< vector< Vector2d >, vector< Matrix2d > > ExcludeNaNInf2 (const vector< Vector2d > &points, const vector< Matrix2d > &covariances)
Function Documentation
ComputeCov() [1/2]
Matrix2d ComputeCov (const vector< Vector2d > & points, const Vector2d & mean, const Matrix2d & intrinsic = Matrix2d::Zero())
Referenced by ComputeCov(), NDTCell::ComputeNGaussian(), and NDTCell::ComputePGaussian().
ComputeCov() [2/2]
Matrix2d ComputeCov (const vector< Vector2d > & points, const Vector2d & mean, const vector< Matrix2d > & intrinsics)
ComputeEvalEvec()
void ComputeEvalEvec (const Matrix2d & covariance, Vector2d & evals, Matrix2d & evecs)
Referenced by NDTCell::ComputeNGaussian(), and NDTCell::ComputePGaussian().
ComputeMean() [1/2]
Vector2d ComputeMean (const vector< Vector2d > & points)
Referenced by ComputeCov(), NDTCell::ComputeNGaussian(), and NDTCell::ComputePGaussian().
ComputeMean() [2/2]
Matrix2d ComputeMean (const vector< Matrix2d > & points)
ExcludeNaNInf()
vector<Vector2d> ExcludeNaNInf (const vector< Vector2d > & points)
Referenced by NDTCell::ComputeNGaussian().
ExcludeNaNInf2()
pair<vector<Vector2d>, vector<Matrix2d> > ExcludeNaNInf2 (const vector< Vector2d > & points, const vector< Matrix2d > & covariances)
Referenced by NDTCell::ComputePGaussian().
RemoveDuplicates()
vector<Vector2d> RemoveDuplicates (const vector< Vector2d > & points)