Symmetric NDT: trimesh::TriMesh Class Reference
trimesh::TriMesh Class Reference
#include <TriMesh.h>
Classes
struct BSphere
Public Types
enum TstripRep { TSTRIP_LENGTH, TSTRIP_TERM }
enum { GRID_INVALID = -1 }
enum StatOp {
STAT_MIN, STAT_MINABS, STAT_MAX, STAT_MAXABS,
STAT_SUM, STAT_SUMABS, STAT_SUMSQR, STAT_MEAN,
STAT_MEANABS, STAT_RMS, STAT_MEDIAN, STAT_STDEV
}
enum StatVal {
STAT_VALENCE, STAT_FACEAREA, STAT_ANGLE, STAT_DIHEDRAL,
STAT_EDGELEN, STAT_X, STAT_Y, STAT_Z
}
typedef Vec< 3, int > Face
typedef Box< 3, float > BBox
Public Member Functions
TriMesh ()
void need_faces ()
void need_tstrips (TstripRep rep=TSTRIP_LENGTH)
void convert_strips (TstripRep rep)
void unpack_tstrips ()
void resize_grid (int width, int height)
void triangulate_grid (bool remove_slivers=true)
void need_normals (bool simple_area_weighted=false)
void need_curvatures ()
void need_dcurv ()
void need_pointareas ()
void need_bbox ()
void need_bsphere ()
void need_neighbors ()
void need_adjacentfaces ()
void need_across_edge ()
void clear_vertices ()
void clear_faces ()
void clear_tstrips ()
void clear_grid ()
void clear_colors ()
void clear_confidences ()
void clear_flags ()
void clear_normals ()
void clear_curvatures ()
void clear_dcurv ()
void clear_pointareas ()
void clear_bbox ()
void clear_bsphere ()
void clear_neighbors ()
void clear_adjacentfaces ()
void clear_across_edge ()
void clear ()
bool write (const char *filename)
bool write (const ::std::string &filename)
bool is_bdy (int v)
vec centroid (int f)
vec trinorm (int f)
float cornerangle (int i, int j)
float dihedral (int i, int j)
float stat (StatOp op, StatVal val)
float feature_size ()
Static Public Member Functions
static TriMesh * read (const char *filename)
static TriMesh * read (const ::std::string &filename)
static void set_verbose (int)
static void set_dprintf_hook (void(*hook)(const char *))
static void dprintf (const char *format,...)
static void set_eprintf_hook (void(*hook)(const char *))
static void eprintf (const char *format,...)
Public Attributes
::std::vector< point > vertices
::std::vector< Face > faces
::std::vector< int > tstrips
::std::vector< int > grid
int grid_width
int grid_height
::std::vector< Color > colors
::std::vector< float > confidences
::std::vector< unsigned > flags
unsigned flag_curr
::std::vector< vec > normals
::std::vector< vec > pdir1
::std::vector< vec > pdir2
::std::vector< float > curv1
::std::vector< float > curv2
::std::vector< Vec< 4, float > > dcurv
::std::vector< vec > cornerareas
::std::vector< float > pointareas
BBox bbox
BSphere bsphere
::std::vector< ::std::vector< int > > neighbors
::std::vector< ::std::vector< int > > adjacentfaces
::std::vector< Face > across_edge
Static Public Attributes
static int verbose = 1
static void(* dprintf_hook)(const char *) = NULL
static void(* eprintf_hook)(const char *) = NULL
Static Protected Member Functions
static bool read_helper (const char *filename, TriMesh *mesh)
Member Typedef Documentation
BBox
typedef Box<3,float> trimesh::TriMesh::BBox
Face
typedef Vec<3,int> trimesh::TriMesh::Face
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
GRID_INVALID
StatOp
enum trimesh::TriMesh::StatOp
Enumerator
STAT_MIN
STAT_MINABS
STAT_MAX
STAT_MAXABS
STAT_SUM
STAT_SUMABS
STAT_SUMSQR
STAT_MEAN
STAT_MEANABS
STAT_RMS
STAT_MEDIAN
STAT_STDEV
StatVal
enum trimesh::TriMesh::StatVal
Enumerator
STAT_VALENCE
STAT_FACEAREA
STAT_ANGLE
STAT_DIHEDRAL
STAT_EDGELEN
STAT_X
STAT_Y
STAT_Z
TstripRep
enum trimesh::TriMesh::TstripRep
Enumerator
TSTRIP_LENGTH
TSTRIP_TERM
Constructor & Destructor Documentation
TriMesh()
trimesh::TriMesh::TriMesh () inline
Member Function Documentation
centroid()
vec trimesh::TriMesh::centroid (int f) inline
clear()
void trimesh::TriMesh::clear () inline
Referenced by trimesh::remap_verts().
clear_across_edge()
void trimesh::TriMesh::clear_across_edge () inline
Referenced by clear(), trimesh::remove_faces(), and trimesh::subdiv().
clear_adjacentfaces()
void trimesh::TriMesh::clear_adjacentfaces () inline
Referenced by clear(), trimesh::remove_faces(), trimesh::shared(), and trimesh::subdiv().
clear_bbox()
void trimesh::TriMesh::clear_bbox () inline
Referenced by clear(), and trimesh::subdiv().
clear_bsphere()
void trimesh::TriMesh::clear_bsphere () inline
Referenced by clear(), and trimesh::subdiv().
clear_colors()
void trimesh::TriMesh::clear_colors () inline
Referenced by clear().
clear_confidences()
void trimesh::TriMesh::clear_confidences () inline
Referenced by clear().
clear_curvatures()
void trimesh::TriMesh::clear_curvatures () inline
Referenced by clear(), and trimesh::subdiv().
clear_dcurv()
void trimesh::TriMesh::clear_dcurv () inline
Referenced by clear(), and trimesh::subdiv().
clear_faces()
void trimesh::TriMesh::clear_faces () inline
Referenced by clear(), trimesh::remove_faces(), and trimesh::remove_unused_vertices().
clear_flags()
void trimesh::TriMesh::clear_flags () inline
Referenced by clear(), and trimesh::subdiv().
clear_grid()
void trimesh::TriMesh::clear_grid () inline
Referenced by clear(), trimesh::shared(), and trimesh::subdiv().
clear_neighbors()
void trimesh::TriMesh::clear_neighbors () inline
Referenced by clear(), trimesh::remove_faces(), trimesh::shared(), and trimesh::subdiv().
clear_normals()
void trimesh::TriMesh::clear_normals () inline
Referenced by clear(), and trimesh::subdiv().
clear_pointareas()
void trimesh::TriMesh::clear_pointareas () inline
Referenced by clear(), trimesh::remove_faces(), and trimesh::subdiv().
clear_tstrips()
void trimesh::TriMesh::clear_tstrips () inline
Referenced by clear(), trimesh::remove_faces(), trimesh::shared(), and trimesh::subdiv().
clear_vertices()
void trimesh::TriMesh::clear_vertices () inline
Referenced by clear().
convert_strips()
void trimesh::TriMesh::convert_strips (TstripRep rep)
Referenced by need_faces(), trimesh::read_ply(), trimesh::remap_verts(), trimesh::reorder_verts(), trimesh::write_ply_ascii(), and trimesh::write_ply_binary().
cornerangle()
float trimesh::TriMesh::cornerangle (int i, int j) inline
dihedral()
float trimesh::TriMesh::dihedral (int i, int j) inline
dprintf()
void trimesh::TriMesh::dprintf (const char * format, ...) static
Referenced by need_pointareas(), and triangulate_grid().
eprintf()
void trimesh::TriMesh::eprintf (const char * format, ...) static
feature_size()
float trimesh::TriMesh::feature_size ()
Referenced by dihedral(), and trimesh::remove_sliver_faces().
is_bdy()
bool trimesh::TriMesh::is_bdy (int v) inline
Referenced by trimesh::erode(), trimesh::find_overlap_onedir(), trimesh::join(), trimesh::selectall_and_match(), trimesh::shared(), and trimesh::umbrella().
need_across_edge()
void trimesh::TriMesh::need_across_edge ()
Referenced by dihedral(), trimesh::edgeflip(), trimesh::remap_verts(), resize_grid(), and trimesh::subdiv().
need_adjacentfaces()
void trimesh::TriMesh::need_adjacentfaces ()
Referenced by trimesh::find_comps(), trimesh::find_overlap(), trimesh::ICP(), trimesh::iou(), is_bdy(), trimesh::join(), trimesh::lmsmooth(), trimesh::orient(), trimesh::remap_verts(), resize_grid(), trimesh::shared(), trimesh::subdiv(), and trimesh::umbrella().
need_bbox()
void trimesh::TriMesh::need_bbox ()
Referenced by trimesh::apply_xform(), trimesh::remap_verts(), and resize_grid().
need_bsphere()
void trimesh::TriMesh::need_bsphere ()
Referenced by trimesh::apply_xform(), trimesh::ICP(), trimesh::remap_verts(), and resize_grid().
need_curvatures()
void trimesh::TriMesh::need_curvatures ()
Referenced by trimesh::diffuse_curv(), trimesh::diffuse_dcurv(), and resize_grid().
need_dcurv()
void trimesh::TriMesh::need_dcurv ()
Referenced by trimesh::diffuse_dcurv(), and resize_grid().
need_faces()
void trimesh::TriMesh::need_faces () inline
Referenced by centroid(), cornerangle(), trimesh::edgeflip(), trimesh::faceflip(), trimesh::find_comps(), trimesh::ICP(), trimesh::mesh_center_of_mass(), trimesh::mesh_covariance(), need_pointareas(), trimesh::orient(), trimesh::remap_verts(), trimesh::remove_faces(), trimesh::remove_sliver_faces(), trimesh::remove_unused_vertices(), trimesh::shared(), trimesh::smooth_mesh(), trimesh::subdiv(), trinorm(), trimesh::write_cc(), trimesh::write_dae(), trimesh::write_faces_asc(), trimesh::write_faces_bin(), trimesh::write_obj(), trimesh::write_off(), trimesh::write_ply_header(), trimesh::write_ray(), and trimesh::write_sm().
need_neighbors()
void trimesh::TriMesh::need_neighbors ()
Referenced by trimesh::bilateral_smooth_mesh(), trimesh::diffuse_curv(), trimesh::diffuse_dcurv(), trimesh::diffuse_normals(), trimesh::diffuse_vector(), trimesh::find_overlap(), trimesh::ICP(), trimesh::iou(), is_bdy(), trimesh::join(), trimesh::lmsmooth(), trimesh::noisify(), trimesh::numbrella(), trimesh::remap_verts(), resize_grid(), trimesh::shared(), and trimesh::umbrella().
need_normals()
void trimesh::TriMesh::need_normals (bool simple_area_weighted = false)
Referenced by trimesh::bilateral_smooth_mesh(), trimesh::diffuse_curv(), trimesh::diffuse_dcurv(), trimesh::diffuse_normals(), trimesh::diffuse_vector(), trimesh::find_overlap(), trimesh::ICP(), trimesh::inflate(), trimesh::iou(), trimesh::join(), trimesh::noisify(), trimesh::numbrella(), resize_grid(), trimesh::umbrella(), trimesh::write_cc(), trimesh::write_obj(), trimesh::write_ply_ascii(), trimesh::write_ply_binary(), trimesh::write_pts(), and trimesh::write_ray().
need_pointareas()
void trimesh::TriMesh::need_pointareas ()
Referenced by trimesh::bilateral_smooth_mesh(), trimesh::diffuse_curv(), trimesh::diffuse_dcurv(), trimesh::diffuse_normals(), trimesh::diffuse_vector(), trimesh::find_overlap(), trimesh::iou(), trimesh::remap_verts(), and resize_grid().
need_tstrips()
void trimesh::TriMesh::need_tstrips (TstripRep rep = TSTRIP_LENGTH)
Referenced by trimesh::faceflip(), trimesh::join(), need_faces(), trimesh::remap_verts(), and trimesh::remove_faces().
read() [1/2]
TriMesh * trimesh::TriMesh::read (const char * filename) static
Referenced by clear().
read() [2/2]
TriMesh * trimesh::TriMesh::read (const ::std::string & filename) static
read_helper()
bool trimesh::TriMesh::read_helper (const char * filename, TriMesh * mesh) static protected
Referenced by clear().
resize_grid()
void trimesh::TriMesh::resize_grid (int width, int height) inline
set_dprintf_hook()
void trimesh::TriMesh::set_dprintf_hook (void(*)(const char *) hook) static
set_eprintf_hook()
void trimesh::TriMesh::set_eprintf_hook (void(*)(const char *) hook) static
set_verbose()
void trimesh::TriMesh::set_verbose (int verbose_) static
stat()
float trimesh::TriMesh::stat (StatOp op, StatVal val)
Referenced by dihedral(), and trimesh::find_overlap_onedir().
triangulate_grid()
void trimesh::TriMesh::triangulate_grid (bool remove_slivers = true)
Referenced by need_faces(), and resize_grid().
trinorm()
vec trimesh::TriMesh::trinorm (int f) inline
Referenced by dihedral(), and trimesh::write_stl().
unpack_tstrips()
void trimesh::TriMesh::unpack_tstrips ()
Referenced by need_faces().
write() [1/2]
bool trimesh::TriMesh::write (const char * filename)
Referenced by clear().
write() [2/2]
bool trimesh::TriMesh::write (const ::std::string & filename)
Member Data Documentation
across_edge
::std::vector<Face> trimesh::TriMesh::across_edge
Referenced by trimesh::avg_bdy(), trimesh::edge_flip(), trimesh::flip_benefit(), trimesh::insert_vert(), trimesh::new_loop_edge(), trimesh::opposite(), trimesh::remap_verts(), trimesh::subdiv(), trimesh::tstrip_build(), and trimesh::zorin_edge().
adjacentfaces
::std::vector< ::std::vector<int> > trimesh::TriMesh::adjacentfaces
Referenced by trimesh::avg_bdy(), trimesh::insert_vert(), trimesh::new_loop_edge(), trimesh::orient(), trimesh::remap_verts(), trimesh::shared(), trimesh::subdiv(), and trimesh::zorin_edge().
bbox
BBox trimesh::TriMesh::bbox
Referenced by trimesh::apply_xform(), trimesh::inflate(), trimesh::lmsmooth(), trimesh::remap_verts(), trimesh::remove_faces(), and trimesh::umbrella().
bsphere
BSphere trimesh::TriMesh::bsphere
Referenced by trimesh::apply_xform(), trimesh::ICP(), trimesh::inflate(), trimesh::lmsmooth(), trimesh::remap_verts(), trimesh::remove_faces(), and trimesh::umbrella().
colors
::std::vector<Color> trimesh::TriMesh::colors
Referenced by trimesh::join(), trimesh::read_verts_asc(), trimesh::read_verts_bin(), trimesh::remap_verts(), trimesh::subdiv(), trimesh::swap_vert_props(), trimesh::write_cc(), trimesh::write_ply_header(), trimesh::write_verts_asc(), and trimesh::write_verts_bin_helper().
confidences
::std::vector<float> trimesh::TriMesh::confidences
Referenced by trimesh::join(), trimesh::read_verts_asc(), trimesh::read_verts_bin(), trimesh::remap_verts(), trimesh::subdiv(), trimesh::swap_vert_props(), trimesh::write_ply_header(), trimesh::write_verts_asc(), and trimesh::write_verts_bin_helper().
cornerareas
::std::vector<vec> trimesh::TriMesh::cornerareas
Referenced by need_pointareas(), trimesh::remap_verts(), and trimesh::smooth_mesh().
curv1
::std::vector<float> trimesh::TriMesh::curv1
Referenced by trimesh::diffuse_curv(), trimesh::AccumCurv::operator()(), and trimesh::remap_verts().
curv2
::std::vector<float> trimesh::TriMesh::curv2
Referenced by trimesh::diffuse_curv(), trimesh::AccumCurv::operator()(), and trimesh::remap_verts().
dcurv
::std::vector< Vec<4,float> > trimesh::TriMesh::dcurv
Referenced by trimesh::diffuse_dcurv(), trimesh::AccumDCurv::operator()(), and trimesh::remap_verts().
dprintf_hook
void(* trimesh::TriMesh::dprintf_hook)(const char *) = NULL static
eprintf_hook
void(* trimesh::TriMesh::eprintf_hook)(const char *) = NULL static
faces
::std::vector<Face> trimesh::TriMesh::faces
Referenced by trimesh::avg_bdy(), trimesh::check_ind_range(), trimesh::connected(), trimesh::edge_flip(), trimesh::edgeflip(), trimesh::faceflip(), trimesh::find_comps(), trimesh::find_connected(), trimesh::flip_benefit(), trimesh::insert_vert(), trimesh::join(), trimesh::make_ccone(), trimesh::make_disc(), trimesh::make_torus(), trimesh::max_x(), trimesh::mesh_center_of_mass(), trimesh::mesh_covariance(), trimesh::mkface(), need_pointareas(), trimesh::new_loop_edge(), trimesh::opposite(), trimesh::orient(), trimesh::read_3ds(), trimesh::read_faces_asc(), trimesh::read_faces_bin(), trimesh::read_obj(), trimesh::read_ray(), trimesh::read_stl(), trimesh::remap_verts(), trimesh::remove_faces(), trimesh::remove_sliver_faces(), trimesh::remove_unused_vertices(), trimesh::reorder_verts(), trimesh::select_big_comps(), trimesh::select_comp(), trimesh::select_small_comps(), trimesh::selectall_and_match(), trimesh::shared(), trimesh::smooth_mesh(), trimesh::subdiv(), triangulate_grid(), trimesh::tstrip_build(), trimesh::write_cc(), trimesh::write_dae(), trimesh::write_faces_asc(), trimesh::write_faces_bin(), trimesh::write_obj(), trimesh::write_off(), trimesh::write_ply_header(), trimesh::write_sm(), trimesh::write_stl(), and trimesh::zorin_edge().
flag_curr
unsigned trimesh::TriMesh::flag_curr
flags
::std::vector<unsigned> trimesh::TriMesh::flags
Referenced by trimesh::orient(), and trimesh::remap_verts().
grid
::std::vector<int> trimesh::TriMesh::grid
Referenced by trimesh::mkface(), trimesh::read_grid_asc(), trimesh::read_grid_bin(), trimesh::remap_verts(), trimesh::reorder_verts(), trimesh::selectall_and_match(), triangulate_grid(), trimesh::write_grid_asc(), and trimesh::write_grid_bin().
grid_height
int trimesh::TriMesh::grid_height
Referenced by trimesh::read_grid_asc(), trimesh::read_grid_bin(), trimesh::read_ply(), triangulate_grid(), and trimesh::write_ply_header().
grid_width
int trimesh::TriMesh::grid_width
Referenced by trimesh::read_grid_asc(), trimesh::read_grid_bin(), trimesh::read_ply(), triangulate_grid(), and trimesh::write_ply_header().
neighbors
::std::vector< ::std::vector<int> > trimesh::TriMesh::neighbors
Referenced by trimesh::diffuse_vert_field(), trimesh::jones_filter(), trimesh::noisify(), trimesh::numbrella(), trimesh::remap_verts(), and trimesh::umbrella().
normals
::std::vector<vec> trimesh::TriMesh::normals
Referenced by trimesh::apply_xform(), trimesh::bilateral_smooth_mesh(), trimesh::diffuse_curv(), trimesh::diffuse_normals(), trimesh::diffuse_vert_field(), DoSICP(), trimesh::find_overlap_onedir(), trimesh::ICP_iter(), trimesh::inflate(), trimesh::join(), trimesh::jones_filter(), MakeMesh(), trimesh::noisify(), trimesh::numbrella(), trimesh::NormCompat::operator()(), trimesh::read_obj(), trimesh::read_pts(), trimesh::read_verts_asc(), trimesh::read_verts_bin(), trimesh::remap_verts(), trimesh::selectall_and_match(), trimesh::swap_vert_props(), trimesh::umbrella(), trimesh::write_cc(), trimesh::write_ply_header(), trimesh::write_pts(), trimesh::write_verts_asc(), and trimesh::write_verts_bin_helper().
pdir1
::std::vector<vec> trimesh::TriMesh::pdir1
Referenced by trimesh::diffuse_curv(), trimesh::AccumCurv::operator()(), trimesh::AccumDCurv::operator()(), and trimesh::remap_verts().
pdir2
::std::vector<vec> trimesh::TriMesh::pdir2
Referenced by trimesh::diffuse_curv(), trimesh::AccumCurv::operator()(), trimesh::AccumDCurv::operator()(), and trimesh::remap_verts().
pointareas
::std::vector<float> trimesh::TriMesh::pointareas
Referenced by trimesh::diffuse_vert_field(), trimesh::find_overlap_onedir(), trimesh::jones_filter(), need_pointareas(), trimesh::remap_verts(), and trimesh::smooth_mesh().
tstrips
::std::vector<int> trimesh::TriMesh::tstrips
Referenced by trimesh::edgeflip(), trimesh::faceflip(), trimesh::mesh_center_of_mass(), trimesh::mesh_covariance(), trimesh::orient(), trimesh::read_strips_asc(), trimesh::read_strips_bin(), trimesh::remap_verts(), trimesh::remove_faces(), trimesh::reorder_verts(), trimesh::selectall_and_match(), trimesh::tstrip_build(), trimesh::write_ply_ascii(), trimesh::write_ply_binary(), trimesh::write_strips_asc(), and trimesh::write_strips_bin().
verbose
int trimesh::TriMesh::verbose = 1 static
vertices
::std::vector<point> trimesh::TriMesh::vertices
Referenced by trimesh::apply_xform(), trimesh::avg_bdy(), trimesh::bilateral_smooth_mesh(), trimesh::butterfly(), trimesh::check_ind_range(), trimesh::clip(), trimesh::compute_overlaps(), trimesh::diffuse_curv(), trimesh::diffuse_dcurv(), trimesh::diffuse_normals(), trimesh::diffuse_vector(), DoSICP(), trimesh::erode(), trimesh::find_comps(), trimesh::find_overlap(), trimesh::find_overlap_onedir(), trimesh::flip_benefit(), trimesh::ICP(), trimesh::ICP_iter(), trimesh::inflate(), trimesh::insert_vert(), trimesh::iou(), trimesh::join(), trimesh::jones_filter(), trimesh::loop(), trimesh::make_ccone(), trimesh::make_ccyl(), trimesh::make_cone(), trimesh::make_cube(), trimesh::make_disc(), trimesh::make_scyl(), trimesh::make_sphere_polar(), trimesh::make_surface_of_revolution(), trimesh::make_torus(), MakeMesh(), trimesh::max_x(), trimesh::mesh_center_of_mass(), trimesh::mesh_covariance(), need_bsphere(), need_pointareas(), trimesh::new_loop_edge(), trimesh::noisify(), trimesh::NormCompat::operator()(), trimesh::opposite(), trimesh::orient(), trimesh::pca_rotate(), trimesh::pca_snap(), trimesh::read_3ds(), trimesh::read_faces_asc(), trimesh::read_faces_bin(), trimesh::read_obj(), trimesh::read_pts(), trimesh::read_ray(), trimesh::read_stl(), trimesh::read_verts_asc(), trimesh::read_verts_bin(), trimesh::read_vvd(), trimesh::remap_verts(), trimesh::remove_sliver_faces(), trimesh::remove_unused_vertices(), trimesh::remove_vertices(), trimesh::reorder_verts(), trimesh::selectall_and_match(), trimesh::shared(), trimesh::slurp_verts_bin(), trimesh::smooth_mesh(), trimesh::subdiv(), trimesh::swap_vert_props(), triangulate_grid(), trimesh::umbrella(), trimesh::write_cc(), trimesh::write_dae(), trimesh::write_off(), trimesh::write_ply_header(), trimesh::write_pts(), trimesh::write_ray(), trimesh::write_sm(), trimesh::write_stl(), trimesh::write_verts_asc(), trimesh::write_verts_bin_helper(), trimesh::wt(), and trimesh::zorin_edge().
The documentation for this class was generated from the following files:
TriMesh.h
TriMesh_bounding.cc
TriMesh_connectivity.cc
TriMesh_curvature.cc
TriMesh_grid.cc
TriMesh_io.cc
TriMesh_normals.cc
TriMesh_pointareas.cc
TriMesh_stats.cc
TriMesh_tstrips.cc