Symmetric NDT: trimesh::Vec< D, T > Class Template Reference
trimesh::Vec< D, T > Class Template Reference
#include <Vec.h>
Public Types
typedef T value_type
typedef value_type * pointer
typedef const value_type * const_pointer
typedef value_type & reference
typedef const value_type & const_reference
typedef value_type * iterator
typedef const value_type * const_iterator
typedef ::std::reverse_iterator< iterator > reverse_iterator
typedef ::std::reverse_iterator< const_iterator > const_reverse_iterator
typedef ::std::size_t size_type
typedef ::std::ptrdiff_t difference_type
typedef ::std::conditional< ::std::is_integral< T >::value, double, T >::type float_type
Public Member Functions
Vec ()
Vec (Vec_uninitialized *)
Vec (const T &x_, const T &y_)
Vec (const T &x_, const T &y_, const T &z_)
Vec (const T &x_, const T &y_, const T &z_, const T &w_)
template<class S >
Vec (S x_, typename ::std::enable_if< ::std::is_arithmetic< S >::value, void >::type *=0)
template<class S >
Vec (const S &v_, typename ::std::enable_if< !::std::is_arithmetic< S >::value, void >::type *=0)
template<class S >
typename ::std::enable_if< ::std::is_arithmetic< S >::value, Vec &>::type operator= (S x_)
template<class S >
typename ::std::enable_if< !::std::is_arithmetic< S >::value, Vec &>::type operator= (const S &v_)
reference operator[] (size_type i)
reference operator[] (int i)
const_reference operator[] (size_type i) const
const_reference operator[] (int i) const
reference at (size_type i)
const_reference at (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
operator T* ()
operator const T * ()
operator const T * () const
pointer data ()
const_pointer data () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
size_type size () const
size_type max_size () const
TRIMESH_DEPRECATED bool empty () const
void clear ()
void fill (const value_type &x_)
void set (const value_type &x_)
void set (const T &x_, const T &y_)
void set (const T &x_, const T &y_, const T &z_)
void set (const T &x_, const T &y_, const T &z_, const T &w_)
Vec & operator+= (const Vec &v_)
Vec & operator-= (const Vec &v_)
Vec & operator*= (const Vec &v_)
Vec & operator/= (const Vec &v_)
Vec & operator+= (const T &x_)
Vec & operator-= (const T &x_)
Vec & operator*= (const T &x_)
Vec & operator/= (const T &x_)
Vec & min (const Vec &v_)
Vec & max (const Vec &v_)
Vec & clamp (const Vec &a, const Vec &b)
Vec & min (const T &x_)
Vec & max (const T &x_)
Vec & clamp (const T &a, const T &b)
void swap (Vec &v_)
value_type dot (const Vec &v_) const
Vec< 3, T > cross (const Vec< 3, T > &v_) const
value_type sum () const
value_type sumabs () const
value_type sumsqr () const
float_type avg () const
float_type avgabs () const
float_type mean () const
float_type meanabs () const
float_type rms () const
value_type product () const
value_type min () const
value_type minabs () const
value_type max () const
value_type maxabs () const
Vec apply (value_type func(value_type)) const
Vec apply (value_type func(const value_type &)) const
Vec cshift (int n) const
Vec shift (int n) const
int indexof (const T &x_) const
Static Public Member Functions
static Vec< D, T > uniform_rnd (T sigma=1)
static Vec< D, T > normal_rnd (T sigma=1)
Friends
const Vec operator+ (const T &x, const Vec &v)
const Vec operator+ (const Vec &v, const T &x)
const Vec operator- (const T &x, const Vec &v)
const Vec operator- (const Vec &v, const T &x)
const Vec operator* (const T &x, const Vec &v)
const Vec operator* (const Vec &v, const T &x)
const Vec operator/ (const T &x, const Vec &v)
const Vec operator/ (const Vec &v, const T &x)
void operator== (const Vec &, const T &)
void operator== (const T &, const Vec &)
void operator!= (const Vec &, const T &)
void operator!= (const T &, const Vec &)
void operator> (const Vec &, const T &)
void operator> (const T &, const Vec &)
void operator>= (const Vec &, const T &)
void operator>= (const T &, const Vec &)
void operator< (const Vec &, const T &)
void operator< (const T &, const Vec &)
void operator<= (const Vec &, const T &)
void operator<= (const T &, const Vec &)
Additional Inherited Members
Public Attributes inherited from trimesh::Vec_data< D, T >
T v [D]
Member Typedef Documentation
const_iterator
template<size_t D, class T = float> typedef const value_type* trimesh::Vec< D, T >::const_iterator
const_pointer
template<size_t D, class T = float> typedef const value_type* trimesh::Vec< D, T >::const_pointer
const_reference
template<size_t D, class T = float> typedef const value_type& trimesh::Vec< D, T >::const_reference
const_reverse_iterator
template<size_t D, class T = float> typedef ::std::reverse_iterator<const_iterator> trimesh::Vec< D, T >::const_reverse_iterator
difference_type
template<size_t D, class T = float> typedef ::std::ptrdiff_t trimesh::Vec< D, T >::difference_type
float_type
template<size_t D, class T = float> typedef ::std::conditional< ::std::is_integral<T>::value, double, T >::type trimesh::Vec< D, T >::float_type
iterator
template<size_t D, class T = float> typedef value_type* trimesh::Vec< D, T >::iterator
pointer
template<size_t D, class T = float> typedef value_type* trimesh::Vec< D, T >::pointer
reference
template<size_t D, class T = float> typedef value_type& trimesh::Vec< D, T >::reference
reverse_iterator
template<size_t D, class T = float> typedef ::std::reverse_iterator<iterator> trimesh::Vec< D, T >::reverse_iterator
size_type
template<size_t D, class T = float> typedef ::std::size_t trimesh::Vec< D, T >::size_type
value_type
template<size_t D, class T = float> typedef T trimesh::Vec< D, T >::value_type
Constructor & Destructor Documentation
Vec() [1/7]
template<size_t D, class T = float> trimesh::Vec< D, T >::Vec () inline
Vec() [2/7]
template<size_t D, class T = float> trimesh::Vec< D, T >::Vec (Vec_uninitialized *) inline explicit
Vec() [3/7]
template<size_t D, class T = float> trimesh::Vec< D, T >::Vec (const T & x_, const T & y_) inline
Vec() [4/7]
template<size_t D, class T = float> trimesh::Vec< D, T >::Vec (const T & x_, const T & y_, const T & z_) inline
Vec() [5/7]
template<size_t D, class T = float> trimesh::Vec< D, T >::Vec (const T & x_, const T & y_, const T & z_, const T & w_) inline
Vec() [6/7]
template<size_t D, class T = float> template<class S > trimesh::Vec< D, T >::Vec (S x_, typename ::std::enable_if< ::std::is_arithmetic< S >::value, void >::type * = 0) inline explicit
Vec() [7/7]
template<size_t D, class T = float> template<class S > trimesh::Vec< D, T >::Vec (const S & v_, typename ::std::enable_if< !::std::is_arithmetic< S >::value, void >::type * = 0) inline explicit
Member Function Documentation
apply() [1/2]
template<size_t D, class T = float> Vec trimesh::Vec< D, T >::apply (value_type funcvalue_type) const inline
apply() [2/2]
template<size_t D, class T = float> Vec trimesh::Vec< D, T >::apply (value_type funcconst value_type &) const inline
at() [1/2]
template<size_t D, class T = float> reference trimesh::Vec< D, T >::at (size_type i) inline
Referenced by conti_to_rospc().
at() [2/2]
template<size_t D, class T = float> const_reference trimesh::Vec< D, T >::at (size_type i) const inline
avg()
template<size_t D, class T = float> float_type trimesh::Vec< D, T >::avg () const inline
avgabs()
template<size_t D, class T = float> float_type trimesh::Vec< D, T >::avgabs () const inline
back() [1/2]
template<size_t D, class T = float> reference trimesh::Vec< D, T >::back () inline
back() [2/2]
template<size_t D, class T = float> const_reference trimesh::Vec< D, T >::back () const inline
begin() [1/2]
template<size_t D, class T = float> iterator trimesh::Vec< D, T >::begin () inline
begin() [2/2]
template<size_t D, class T = float> const_iterator trimesh::Vec< D, T >::begin () const inline
cbegin()
template<size_t D, class T = float> const_iterator trimesh::Vec< D, T >::cbegin () const inline
cend()
template<size_t D, class T = float> const_iterator trimesh::Vec< D, T >::cend () const inline
clamp() [1/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::clamp (const Vec< D, T > & a, const Vec< D, T > & b) inline
clamp() [2/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::clamp (const T & a, const T & b) inline
clear()
template<size_t D, class T = float> void trimesh::Vec< D, T >::clear () inline
Referenced by trimesh::jones_filter().
crbegin()
template<size_t D, class T = float> const_reverse_iterator trimesh::Vec< D, T >::crbegin () const inline
crend()
template<size_t D, class T = float> const_reverse_iterator trimesh::Vec< D, T >::crend () const inline
cross()
template<size_t D, class T = float> Vec<3,T> trimesh::Vec< D, T >::cross (const Vec< 3, T > & v_) const inline
cshift()
template<size_t D, class T = float> Vec trimesh::Vec< D, T >::cshift (int n) const inline
data() [1/2]
template<size_t D, class T = float> pointer trimesh::Vec< D, T >::data () inline
data() [2/2]
template<size_t D, class T = float> const_pointer trimesh::Vec< D, T >::data () const inline
dot()
template<size_t D, class T = float> value_type trimesh::Vec< D, T >::dot (const Vec< D, T > & v_) const inline
empty()
template<size_t D, class T = float> TRIMESH_DEPRECATED bool trimesh::Vec< D, T >::empty () const inline
end() [1/2]
template<size_t D, class T = float> iterator trimesh::Vec< D, T >::end () inline
end() [2/2]
template<size_t D, class T = float> const_iterator trimesh::Vec< D, T >::end () const inline
fill()
template<size_t D, class T = float> void trimesh::Vec< D, T >::fill (const value_type & x_) inline
front() [1/2]
template<size_t D, class T = float> reference trimesh::Vec< D, T >::front () inline
front() [2/2]
template<size_t D, class T = float> const_reference trimesh::Vec< D, T >::front () const inline
indexof()
template<size_t D, class T = float> int trimesh::Vec< D, T >::indexof (const T & x_) const inline
Referenced by trimesh::insert_vert().
max() [1/3]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::max (const Vec< D, T > & v_) inline
max() [2/3]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::max (const T & x_) inline
max() [3/3]
template<size_t D, class T = float> value_type trimesh::Vec< D, T >::max () const inline
max_size()
template<size_t D, class T = float> size_type trimesh::Vec< D, T >::max_size () const inline
maxabs()
template<size_t D, class T = float> value_type trimesh::Vec< D, T >::maxabs () const inline
mean()
template<size_t D, class T = float> float_type trimesh::Vec< D, T >::mean () const inline
meanabs()
template<size_t D, class T = float> float_type trimesh::Vec< D, T >::meanabs () const inline
min() [1/3]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::min (const Vec< D, T > & v_) inline
min() [2/3]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::min (const T & x_) inline
min() [3/3]
template<size_t D, class T = float> value_type trimesh::Vec< D, T >::min () const inline
minabs()
template<size_t D, class T = float> value_type trimesh::Vec< D, T >::minabs () const inline
normal_rnd()
template<size_t D, class T = float> static Vec<D,T> trimesh::Vec< D, T >::normal_rnd (T sigma = 1) inline static
operator const T *() [1/2]
template<size_t D, class T = float> trimesh::Vec< D, T >::operator const T * () inline
operator const T *() [2/2]
template<size_t D, class T = float> trimesh::Vec< D, T >::operator const T * () const inline
operator T*()
template<size_t D, class T = float> trimesh::Vec< D, T >::operator T* () inline
operator*=() [1/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::operator*= (const Vec< D, T > & v_) inline
operator*=() [2/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::operator*= (const T & x_) inline
operator+=() [1/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::operator+= (const Vec< D, T > & v_) inline
operator+=() [2/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::operator+= (const T & x_) inline
operator-=() [1/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::operator-= (const Vec< D, T > & v_) inline
operator-=() [2/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::operator-= (const T & x_) inline
operator/=() [1/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::operator/= (const Vec< D, T > & v_) inline
operator/=() [2/2]
template<size_t D, class T = float> Vec& trimesh::Vec< D, T >::operator/= (const T & x_) inline
operator=() [1/2]
template<size_t D, class T = float> template<class S > typename ::std::enable_if< ::std::is_arithmetic<S>::value, Vec & >::type trimesh::Vec< D, T >::operator= (S x_) inline
operator=() [2/2]
template<size_t D, class T = float> template<class S > typename ::std::enable_if< !::std::is_arithmetic<S>::value, Vec & >::type trimesh::Vec< D, T >::operator= (const S & v_) inline
operator[]() [1/4]
template<size_t D, class T = float> reference trimesh::Vec< D, T >::operator[] (size_type i) inline
operator[]() [2/4]
template<size_t D, class T = float> reference trimesh::Vec< D, T >::operator[] (int i) inline
operator[]() [3/4]
template<size_t D, class T = float> const_reference trimesh::Vec< D, T >::operator[] (size_type i) const inline
operator[]() [4/4]
template<size_t D, class T = float> const_reference trimesh::Vec< D, T >::operator[] (int i) const inline
product()
template<size_t D, class T = float> value_type trimesh::Vec< D, T >::product () const inline
rbegin() [1/2]
template<size_t D, class T = float> reverse_iterator trimesh::Vec< D, T >::rbegin () inline
rbegin() [2/2]
template<size_t D, class T = float> const_reverse_iterator trimesh::Vec< D, T >::rbegin () const inline
rend() [1/2]
template<size_t D, class T = float> reverse_iterator trimesh::Vec< D, T >::rend () inline
rend() [2/2]
template<size_t D, class T = float> const_reverse_iterator trimesh::Vec< D, T >::rend () const inline
rms()
template<size_t D, class T = float> float_type trimesh::Vec< D, T >::rms () const inline
set() [1/4]
template<size_t D, class T = float> void trimesh::Vec< D, T >::set (const value_type & x_) inline
Referenced by trimesh::myGluUnProject(), and trimesh::normals_from_points().
set() [2/4]
template<size_t D, class T = float> void trimesh::Vec< D, T >::set (const T & x_, const T & y_) inline
set() [3/4]
template<size_t D, class T = float> void trimesh::Vec< D, T >::set (const T & x_, const T & y_, const T & z_) inline
set() [4/4]
template<size_t D, class T = float> void trimesh::Vec< D, T >::set (const T & x_, const T & y_, const T & z_, const T & w_) inline
shift()
template<size_t D, class T = float> Vec trimesh::Vec< D, T >::shift (int n) const inline
size()
template<size_t D, class T = float> size_type trimesh::Vec< D, T >::size () const inline
Referenced by trimesh::normals_from_tstrips_area(), and trimesh::point_center_of_mass().
sum()
template<size_t D, class T = float> value_type trimesh::Vec< D, T >::sum () const inline
Referenced by trimesh::align_scale().
sumabs()
template<size_t D, class T = float> value_type trimesh::Vec< D, T >::sumabs () const inline
sumsqr()
template<size_t D, class T = float> value_type trimesh::Vec< D, T >::sumsqr () const inline
swap()
template<size_t D, class T = float> void trimesh::Vec< D, T >::swap (Vec< D, T > & v_) inline
uniform_rnd()
template<size_t D, class T = float> static Vec<D,T> trimesh::Vec< D, T >::uniform_rnd (T sigma = 1) inline static
Friends And Related Function Documentation
operator!= [1/2]
template<size_t D, class T = float> void operator!= (const Vec< D, T > & , const T &) friend
operator!= [2/2]
template<size_t D, class T = float> void operator!= (const T & , const Vec< D, T > &) friend
operator* [1/2]
template<size_t D, class T = float> const Vec operator* (const T & x, const Vec< D, T > & v) friend
operator* [2/2]
template<size_t D, class T = float> const Vec operator* (const Vec< D, T > & v, const T & x) friend
operator+ [1/2]
template<size_t D, class T = float> const Vec operator+ (const T & x, const Vec< D, T > & v) friend
operator+ [2/2]
template<size_t D, class T = float> const Vec operator+ (const Vec< D, T > & v, const T & x) friend
operator- [1/2]
template<size_t D, class T = float> const Vec operator- (const T & x, const Vec< D, T > & v) friend
operator- [2/2]
template<size_t D, class T = float> const Vec operator- (const Vec< D, T > & v, const T & x) friend
operator/ [1/2]
template<size_t D, class T = float> const Vec operator/ (const T & x, const Vec< D, T > & v) friend
operator/ [2/2]
template<size_t D, class T = float> const Vec operator/ (const Vec< D, T > & v, const T & x) friend
operator< [1/2]
template<size_t D, class T = float> void operator< (const Vec< D, T > & , const T &) friend
operator< [2/2]
template<size_t D, class T = float> void operator< (const T & , const Vec< D, T > &) friend
operator<= [1/2]
template<size_t D, class T = float> void operator<= (const Vec< D, T > & , const T &) friend
operator<= [2/2]
template<size_t D, class T = float> void operator<= (const T & , const Vec< D, T > &) friend
operator== [1/2]
template<size_t D, class T = float> void operator== (const Vec< D, T > & , const T &) friend
operator== [2/2]
template<size_t D, class T = float> void operator== (const T & , const Vec< D, T > &) friend
operator> [1/2]
template<size_t D, class T = float> void operator> (const Vec< D, T > & , const T &) friend
operator> [2/2]
template<size_t D, class T = float> void operator> (const T & , const Vec< D, T > &) friend
operator>= [1/2]
template<size_t D, class T = float> void operator>= (const Vec< D, T > & , const T &) friend
operator>= [2/2]
template<size_t D, class T = float> void operator>= (const T & , const Vec< D, T > &) friend
The documentation for this class was generated from the following file:
Vec.h