Symmetric NDT: other_utils.h File Reference
other_utils.h File Reference
#include <bits/stdc++.h>
#include <ros/ros.h>
Macros
#define APATH "/home/ee904/Desktop/HuaTsai/NormalNDT/Analysis"
#define BPATH "/home/ee904/Desktop/Dataset/nuScenes"
Functions
std::chrono::steady_clock::time_point GetTime ()
int GetDiffTime (std::chrono::steady_clock::time_point t1, std::chrono::steady_clock::time_point t2)
std::string JoinPath ()
template<typename... Args>
std::string JoinPath (std::string s1, Args... args)
template<typename T >
void SerializationInput (const std::string &filepath, T &msg)
template<typename T >
void SerializationOutput (const std::string &filepath, const T &msg)
std::string GetDataPath (std::string data)
std::vector< std::string > GetBagsPath (std::string data)
Macro Definition Documentation
APATH
#define APATH "/home/ee904/Desktop/HuaTsai/NormalNDT/Analysis"
Referenced by GetDataPath(), and main().
BPATH
#define BPATH "/home/ee904/Desktop/Dataset/nuScenes"
Referenced by GetBagsPath().
Function Documentation
GetBagsPath()
std::vector<std::string> GetBagsPath (std::string data)
Referenced by main().
GetDataPath()
std::string GetDataPath (std::string data)
Referenced by GetFiles(), and main().
GetDiffTime()
int GetDiffTime (std::chrono::steady_clock::time_point t1, std::chrono::steady_clock::time_point t2) inline
Referenced by cb(), main(), NDTD2DMatch(), SICPMatch(), and SNDTMatch().
GetTime()
std::chrono::steady_clock::time_point GetTime () inline
Referenced by cb(), main(), NDTD2DMatch(), SICPMatch(), and SNDTMatch().
JoinPath() [1/2]
std::string JoinPath ()
Referenced by GetBagsPath(), GetDataPath(), GetFiles(), JoinPath(), and main().
JoinPath() [2/2]
template<typename... Args> std::string JoinPath (std::string s1, Args... args)
SerializationInput()
template<typename T > void SerializationInput (const std::string & filepath, T & msg)
Referenced by GetFiles(), and main().
SerializationOutput()
template<typename T > void SerializationOutput (const std::string & filepath, const T & msg)
Referenced by main(), and savecb().