Symmetric NDT: geometry_utils.h File Reference
geometry_utils.h File Reference
#include <tf2_geometry_msgs/tf2_geometry_msgs.h>
#include <gsl/gsl>
Functions
geometry_msgs::Pose PoseInterpolate (const geometry_msgs::PoseStamped &p1, const geometry_msgs::PoseStamped &p2, const ros::Time &time)
geometry_msgs::Pose GetPose (const std::vector< geometry_msgs::PoseStamped > &poses, const ros::Time &time)
Function Documentation
GetPose()
geometry_msgs::Pose GetPose (const std::vector< geometry_msgs::PoseStamped > & poses, const ros::Time & time)
Referenced by cb(), and MakeGtLocal().
PoseInterpolate()
geometry_msgs::Pose PoseInterpolate (const geometry_msgs::PoseStamped & p1, const geometry_msgs::PoseStamped & p2, const ros::Time & time)
Referenced by GetPose().