Symmetric NDT: visuals.h File Reference
visuals.h File Reference
Declaration of Visual Utilities.
#include <visualization_msgs/MarkerArray.h>
#include <sndt/ndt_map.h>
#include <sndt/sndt_map.h>
Enumerations
enum Color {
Color::kRed, Color::kLime, Color::kBlue, Color::kWhite,
Color::kBlack, Color::kGray, Color::kYellow, Color::kAqua,
Color::kFuchsia
}
Functions
std_msgs::ColorRGBA MakeColorRGBA (const Color &color, double alpha=1.)
Factory method for making std_msgs::ColorRGBA.
std::vector< Eigen::Vector2d > FindTangentPoints (const Marker &ellipse, const Eigen::Vector2d &point)
Given an ellipse and an external point, find the tangent points.
MarkerArray JoinMarkers (const std::vector< Marker > &markers)
Join markers by assigning different id.
MarkerArray JoinMarkerArrays (const std::vector< MarkerArray > &markerarrays)
Join markerarrays by assigning different id.
MarkerArray JoinMarkerArraysAndMarkers (const std::vector< MarkerArray > &markerarrays, const std::vector< Marker > &markers)
Join markerarrays and markers by assigning different id.
Marker MarkerOfBoundary (const Eigen::Vector2d &center, double size, double skew_rad=0, const Color &color=Color::kBlack, double alpha=1.0)
Marker of the cell boundary.
Marker MarkerOfEllipse (const Eigen::Vector2d &mean, const Eigen::Matrix2d &covariance, const Color &color=Color::kLime, double alpha=0.6)
Marker of the cell covariance.
Marker MarkerOfCircle (const Eigen::Vector2d &center, double size, const Color &color=Color::kLime, double alpha=0.6)
Marker of the circle.
Marker MarkerOfLines (const std::vector< Eigen::Vector2d > &points, const Color &color=Color::kLime, double alpha=1.0)
Marker of the lines.
Marker MarkerOfLinesByMiddlePoints (const std::vector< Eigen::Vector2d > &points, const Color &color=Color::kLime, double alpha=1.0)
Marker of the lines by middle points.
Marker MarkerOfPoints (const std::vector< Eigen::Vector2d > &points, double size=0.1, const Color &color=Color::kLime, double alpha=1.0)
Marker of the points.
Marker MarkerOfArrow (const Eigen::Vector2d &start, const Eigen::Vector2d &end, const Color &color=Color::kLime, double alpha=1.0)
Marker of the arrows.
Marker MarkerOfText (std::string text, const Eigen::Vector2d &position, const Color &color=Color::kBlack, double alpha=1.0)
Marker of the text.
MarkerArray MarkerArrayOfArrows (const std::vector< Eigen::Vector2d > &starts, const std::vector< Eigen::Vector2d > &ends, const Color &color=Color::kLime, double alpha=1.0)
MarkerArray of the arrows.
MarkerArray MarkerArrayOfSNDTCell (const SNDTCell *cell)
General MarkerArray of SNDTCell.
MarkerArray MarkerArrayOfSNDTCell2 (const SNDTCell *cell)
Special MarkerArray of SNDTCell.
MarkerArray MarkerArrayOfSNDTMap (const SNDTMap &map, bool use_target_color=false)
MarkerArray of SNDTMap.
MarkerArray MarkerArrayOfSNDTMap (const std::vector< std::shared_ptr< SNDTCell >> &map, bool use_target_color=false)
MarkerArray of SNDTMap.
MarkerArray MarkerArrayOfCorrespondences (const NDTCell *source_cell, const NDTCell *target_cell, std::string text, const Color &color=Color::kBlack)
MarkerArray of correspondences.
MarkerArray MarkerArrayOfSensor (const std::vector< Eigen::Affine2d > &affs)
MarkerArray of the sensors.
Detailed Description
Declaration of Visual Utilities.
Author
HuaTsai (huats.nosp@m.ai.e.nosp@m.ed07g.nosp@m.@nct.nosp@m.u.edu.nosp@m..tw)
Version
0.1
Date
2021-07-30
Copyright
Copyright (c) 2021
Enumeration Type Documentation
Color
enum Color strong
Enumerator
kRed
(R, G, B) = (1.0, 0.0, 0.0)
kLime
(R, G, B) = (0.0, 1.0, 0.0)
kBlue
(R, G, B) = (0.0, 0.0, 1.0)
kWhite
(R, G, B, A) = (x, x, x, 0.0)
kBlack
(R, G, B) = (0.0, 0.0, 0.0)
kGray
(R, G, B) = (0.5, 0.5, 0.5)
kYellow
(R, G, B) = (1.0, 1.0, 0.0)
kAqua
(R, G, B) = (0.0, 1.0, 1.0)
kFuchsia
(R, G, B) = (1.0, 0.0, 1.0)
Function Documentation
FindTangentPoints()
std::vector<Eigen::Vector2d> FindTangentPoints (const Marker & ellipse, const Eigen::Vector2d & point)
Given an ellipse and an external point, find the tangent points.
Parameters
ellipse Input ellipse
point Input external point
Returns
Two tangent points
Referenced by MarkerArrayOfSNDTCell(), and MarkerArrayOfSNDTCell2().
JoinMarkerArrays()
MarkerArray JoinMarkerArrays (const std::vector< MarkerArray > & markerarrays)
Join markerarrays by assigning different id.
Parameters
markerarrays Input markerarrays
Returns
Joined markerarray
Referenced by MarkerArrayOfSNDTMap().
JoinMarkerArraysAndMarkers()
MarkerArray JoinMarkerArraysAndMarkers (const std::vector< MarkerArray > & markerarrays, const std::vector< Marker > & markers)
Join markerarrays and markers by assigning different id.
Parameters
markerarrays Input markerarrays
markers Input markers
Returns
Joined markerarray
Referenced by MarkerArrayOfCorrespondences().
JoinMarkers()
MarkerArray JoinMarkers (const std::vector< Marker > & markers)
Join markers by assigning different id.
Parameters
markers Input markers
Returns
Joined markerarray
Referenced by MarkerArrayOfSNDTCell(), and MarkerArrayOfSNDTCell2().
MakeColorRGBA()
std_msgs::ColorRGBA MakeColorRGBA (const Color & color, double alpha = 1.)
Factory method for making std_msgs::ColorRGBA.
Parameters
color Input color defined in enum Color
alpha Alpha, 0 represents transparent while 1 represents opaque
See also
Color
Referenced by MarkerArrayOfArrows(), MarkerArrayOfSensor(), MarkerOfArrow(), MarkerOfBoundary(), MarkerOfCircle(), MarkerOfEllipse(), MarkerOfLines(), MarkerOfPoints(), and MarkerOfText().
MarkerArrayOfArrows()
MarkerArray MarkerArrayOfArrows (const std::vector< Eigen::Vector2d > & starts, const std::vector< Eigen::Vector2d > & ends, const Color & color = Color::kLime, double alpha = 1.0)
MarkerArray of the arrows.
Parameters
starts Starts of the arrows
ends Ends of the arrows
color Arrows color (default kLime)
alpha Alpha (default 1.0)
Precondition
The size of starts and ends should be the same
Returns
MarkerArray of arrows
Referenced by cb().
MarkerArrayOfCorrespondences()
MarkerArray MarkerArrayOfCorrespondences (const NDTCell * source_cell, const NDTCell * target_cell, std::string text, const Color & color = Color::kBlack)
MarkerArray of correspondences.
Parameters
source_cell Source cell
target_cell Target cell
text Text of the cost value
color Text color (default black)
Returns
MarkerArray of correspondences
MarkerArrayOfSensor()
MarkerArray MarkerArrayOfSensor (const std::vector< Eigen::Affine2d > & affs)
MarkerArray of the sensors.
Parameters
affs Poses of the sensors
Returns
MarkerArray of the sensors
MarkerArrayOfSNDTCell()
MarkerArray MarkerArrayOfSNDTCell (const SNDTCell * cell)
General MarkerArray of SNDTCell.
Parameters
cell Input cell pointer
Returns
General MarkerArray of SNDTCell
Boundary, point covariance, (normal covariance, and tangent lines) are drawed.
Referenced by MarkerArrayOfCorrespondences(), and MarkerArrayOfSNDTMap().
MarkerArrayOfSNDTCell2()
MarkerArray MarkerArrayOfSNDTCell2 (const SNDTCell * cell)
Special MarkerArray of SNDTCell.
Parameters
cell Input cell pointer
Returns
Special MarkerArray of SNDTCell
Note
Boundary, point covariance, (normal covariance, and tangent lines) are drawed. The only difference is that the covariance color and the boundary color are red.
Referenced by MarkerArrayOfCorrespondences(), and MarkerArrayOfSNDTMap().
MarkerArrayOfSNDTMap() [1/2]
MarkerArray MarkerArrayOfSNDTMap (const SNDTMap & map, bool use_target_color = false)
MarkerArray of SNDTMap.
Parameters
map Input SNDTMap
use_target_color Use target color (default false)
Returns
MarkerArray of SNDTMap
Note
This function omits those HasGaussian() is false
Referenced by cb().
MarkerArrayOfSNDTMap() [2/2]
MarkerArray MarkerArrayOfSNDTMap (const std::vector< std::shared_ptr< SNDTCell >> & map, bool use_target_color = false)
MarkerArray of SNDTMap.
Parameters
map Input SNDTMap
use_target_color Use target color (default false)
Returns
MarkerArray of SNDTMap
Note
This function omits those HasGaussian() is false
MarkerOfArrow()
Marker MarkerOfArrow (const Eigen::Vector2d & start, const Eigen::Vector2d & end, const Color & color = Color::kLime, double alpha = 1.0)
Marker of the arrows.
Parameters
start Input arrow start
end Input arrow end
color Arrow color (default kLime)
alpha Alpha (default 1.0)
Returns
Marker of type ARROW of the arrow
MarkerOfBoundary()
Marker MarkerOfBoundary (const Eigen::Vector2d & center, double size, double skew_rad = 0, const Color & color = Color::kBlack, double alpha = 1.0)
Marker of the cell boundary.
Parameters
center Cell center
size Cell size
skew_rad Cell skew radian (default 0)
color Boundary Color (default kBlack)
alpha Alpha (default 1.0)
Returns
Marker of type LINE_LIST of the cell boundary
Referenced by MarkerArrayOfSNDTCell(), and MarkerArrayOfSNDTCell2().
MarkerOfCircle()
Marker MarkerOfCircle (const Eigen::Vector2d & center, double size, const Color & color = Color::kLime, double alpha = 0.6)
Marker of the circle.
Parameters
center Circle center
size Circle size
color Circle color (default kLime)
alpha Alpha (default 0.6)
Returns
Marker of type SPHERE of the circle
MarkerOfEllipse()
Marker MarkerOfEllipse (const Eigen::Vector2d & mean, const Eigen::Matrix2d & covariance, const Color & color = Color::kLime, double alpha = 0.6)
Marker of the cell covariance.
Parameters
mean Ellipse center
covariance Ellipse axes and length
color Ellipse color (default kLime)
alpha Alpha (default 0.6)
Returns
Marker of type SPHERE the cell covariance
Note: "pseudo" computes complex eigen value if no real solution However, covariance is always a real symmetric matrix, which means 1) it is Hermitia, all its eigenvalues are real 2) the decomposed matrix is an orthogonal matrix, i.e., rotaion matrix
Referenced by MarkerArrayOfSNDTCell(), and MarkerArrayOfSNDTCell2().
MarkerOfLines()
Marker MarkerOfLines (const std::vector< Eigen::Vector2d > & points, const Color & color = Color::kLime, double alpha = 1.0)
Marker of the lines.
Parameters
points Points that form lines
color Lines color
alpha Alpha (default 1.0)
Returns
Marker of type LINE_LIST of the lines
Precondition
The size of points should be even
Points 0-1 forms line 0, points 2-3 forms line 1, etc.
Referenced by MarkerArrayOfCorrespondences(), and MarkerOfLinesByMiddlePoints().
MarkerOfLinesByMiddlePoints()
Marker MarkerOfLinesByMiddlePoints (const std::vector< Eigen::Vector2d > & points, const Color & color = Color::kLime, double alpha = 1.0)
Marker of the lines by middle points.
Parameters
points Points that form lines
color Lines color (default kLime)
alpha Alpha (default 1.0)
Returns
Marker of type LINE_LIST of the lines
Points 0-1 forms line 0, points 1-2 forms line 1, etc.
Referenced by MarkerArrayOfSNDTCell(), and MarkerArrayOfSNDTCell2().
MarkerOfPoints()
Marker MarkerOfPoints (const std::vector< Eigen::Vector2d > & points, double size = 0.1, const Color & color = Color::kLime, double alpha = 1.0)
Marker of the points.
Parameters
points Input points
size Input point size
color Points color (default kLime)
alpha Alpha (default 1.0)
Returns
Marker of type SPHERE_LIST of the points
Referenced by cb().
MarkerOfText()
Marker MarkerOfText (std::string text, const Eigen::Vector2d & position, const Color & color = Color::kBlack, double alpha = 1.0)
Marker of the text.
Parameters
text Input text
position Text position
color Text color (default kBlack)
alpha Alpha (default 1.0)
Returns
Marker of type TEXT_VIEW_FACING of the text
Referenced by MarkerArrayOfCorrespondences().