Symmetric NDT: NDTMatcher Class Reference
NDTMatcher Class Reference
#include <ndt_matcher.h>
Public Types
enum Strategy { kDEFAULT, kNEAREST_1_POINTS, kUSE_CELLS_GREATER_THAN_TWO_POINTS }
Public Member Functions
NDTMatcher ()
Matrix3d CeresMatch (NDTMap &target_map, NDTMap &source_map, const Affine2d &guess_tf=Affine2d::Identity())
Matrix3d CeresMatch (NDTMap &target_map, NDTMap &source_map, const Matrix3d &guess_tf=Matrix3d::Identity())
int GetIteration ()
void SetStrategy (Strategy strategy)
void SetMaxIterations (int max_iterations)
void SetThreshold (double threshold)
Public Attributes
vector< pair< MarkerArray, MarkerArray > > vmas
vector< Vector2d > costs
double huber
bool verbose
Member Enumeration Documentation
Strategy
enum NDTMatcher::Strategy
Enumerator
kDEFAULT
kNEAREST_1_POINTS
kUSE_CELLS_GREATER_THAN_TWO_POINTS
Constructor & Destructor Documentation
NDTMatcher()
NDTMatcher::NDTMatcher ()
Member Function Documentation
CeresMatch() [1/2]
Matrix3d NDTMatcher::CeresMatch (NDTMap & target_map, NDTMap & source_map, const Affine2d & guess_tf = Affine2d::Identity()) inline
Referenced by cb(), and DoSNDT().
CeresMatch() [2/2]
Matrix3d NDTMatcher::CeresMatch (NDTMap & target_map, NDTMap & source_map, const Matrix3d & guess_tf = Matrix3d::Identity())
GetIteration()
int NDTMatcher::GetIteration () inline
Referenced by DoSNDT().
SetMaxIterations()
void NDTMatcher::SetMaxIterations (int max_iterations) inline
SetStrategy()
void NDTMatcher::SetStrategy (Strategy strategy) inline
Referenced by cb(), and DoSNDT().
SetThreshold()
void NDTMatcher::SetThreshold (double threshold) inline
Referenced by DoSNDT().
Member Data Documentation
costs
vector<Vector2d> NDTMatcher::costs
huber
double NDTMatcher::huber
Referenced by cb().
verbose
bool NDTMatcher::verbose
Referenced by main().
vmas
vector<pair<MarkerArray, MarkerArray> > NDTMatcher::vmas
Referenced by cb().
The documentation for this class was generated from the following files:
ndt_matcher.h
ndt_matcher.cc