Symmetric NDT: NDTMap Class Reference
NDTMap Class Reference
#include <ndt_map.h>
Public Member Functions
NDTMap (double cell_size)
Construct a new NDTMap object.
~NDTMap ()
void LoadPoints (const std::vector< Eigen::Vector2d > &points)
Load points into the NDTMap.
void LoadPointsWithCovariances (const std::vector< Eigen::Vector2d > &points, const std::vector< Eigen::Matrix2d > &point_covs)
Load points and point covariances into the NDTMap.
std::vector< std::shared_ptr< NDTCell > > PseudoTransformCells (const Eigen::Affine2d &T, bool include_data=false) const
Perform transformation to NDTMap.
NDTCell * GetCellAndAllocate (const Eigen::Vector2d &point)
Get and allocate the cell by a given point.
const NDTCell * GetCellForPoint (const Eigen::Vector2d &point) const
Get the cell by a given point.
virtual std::string ToString () const override
Convert the information of the NDTMap to a string.
std::vector< Eigen::Vector2d > GetPoints () const
Get the Points object.
size_t size () const
std::vector< NDTCell * >::iterator begin ()
std::vector< NDTCell * >::const_iterator begin () const
std::vector< NDTCell * >::iterator end ()
std::vector< NDTCell * >::const_iterator end () const
Public Member Functions inherited from MapInterface
MapInterface (double cell_size)
Construct a new MapInterface object.
virtual ~MapInterface ()=default
Eigen::Vector2i GetIndexForPoint (const Eigen::Vector2d &point) const
Get the index by a given point.
double GetCellSize () const
Eigen::Vector2d GetMapSize () const
Eigen::Vector2d GetMapCenter () const
Additional Inherited Members
Protected Member Functions inherited from MapInterface
void GuessMapSize (const std::vector< Eigen::Vector2d > &points)
Update mata information of MapInterface by points.
bool IsValidIndex (const Eigen::Vector2i &index) const
Check the validity of an index.
Protected Attributes inherited from MapInterface
bool is_loaded_
double cell_size_
Eigen::Vector2d map_size_
Eigen::Vector2d map_center_
Eigen::Vector2i map_center_index_
Eigen::Vector2i cellptrs_size_
Constructor & Destructor Documentation
NDTMap()
NDTMap::NDTMap (double cell_size) explicit
Construct a new NDTMap object.
Parameters
cell_size Cell size of the NDTMap
~NDTMap()
NDTMap::~NDTMap ()
Member Function Documentation
begin() [1/2]
std::vector<NDTCell *>::iterator NDTMap::begin () inline
Referenced by GetPoints(), and PseudoTransformCells().
begin() [2/2]
std::vector<NDTCell *>::const_iterator NDTMap::begin () const inline
end() [1/2]
std::vector<NDTCell *>::iterator NDTMap::end () inline
Referenced by GetPoints(), and PseudoTransformCells().
end() [2/2]
std::vector<NDTCell *>::const_iterator NDTMap::end () const inline
GetCellAndAllocate()
NDTCell * NDTMap::GetCellAndAllocate (const Eigen::Vector2d & point)
Get and allocate the cell by a given point.
Parameters
point Input point
Referenced by LoadPoints(), and LoadPointsWithCovariances().
GetCellForPoint()
const NDTCell * NDTMap::GetCellForPoint (const Eigen::Vector2d & point) const
Get the cell by a given point.
Parameters
point Input point
Referenced by NDTD2DMatch().
GetPoints()
std::vector< Eigen::Vector2d > NDTMap::GetPoints () const
Get the Points object.
Note
The points are retrived from active_cells_, which does not necessarily equal to the original input
Referenced by NDTD2DMatch().
LoadPoints()
void NDTMap::LoadPoints (const std::vector< Eigen::Vector2d > & points)
Load points into the NDTMap.
Parameters
points Points to load
normals Normals to load
Note
points and normals should have the same size
LoadPointsWithCovariances()
void NDTMap::LoadPointsWithCovariances (const std::vector< Eigen::Vector2d > & points, const std::vector< Eigen::Matrix2d > & point_covs)
Load points and point covariances into the NDTMap.
Parameters
points Points to load
point_covs Point covariances to load
normals Normals to load
Note
points, point_covs, and normals should have the same size
Referenced by MakeNDTMap().
PseudoTransformCells()
std::vector< std::shared_ptr< NDTCell > > NDTMap::PseudoTransformCells (const Eigen::Affine2d & T, bool include_data = false) const
Perform transformation to NDTMap.
Parameters
T Transformation
include_data Transform data as well (default false)
Returns
Transformed cells
Referenced by NDTD2DMatch().
size()
size_t NDTMap::size () const inline
ToString()
std::string NDTMap::ToString () const override virtual
Convert the information of the NDTMap to a string.
Implements MapInterface.
The documentation for this class was generated from the following files:
ndt_map.h
ndt_map.cc