Symmetric NDT: common::MatchInternal Class Reference
common::MatchInternal Class Reference
#include <match_utils.hpp>
Public Member Functions
MatchInternal ()
template<typename Archive >
void serialize_mtx (Archive &ar, std::string str, Eigen::MatrixXd &mtx)
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
void PushBack (const Correspondences &corr, const Eigen::Vector3d &tf)
void PushBack (const Correspondences &corr, const std::vector< double > &tf)
void ClearResults ()
bool has_data () const
double cell_size () const
Eigen::MatrixXd source () const
Eigen::MatrixXd target () const
std::vector< Eigen::MatrixXd > corrs () const
std::vector< Eigen::Vector3d > tfs () const
std::string comment () const
void set_has_data (bool has_data)
void set_cell_size (double cell_size)
void set_source (const Eigen::MatrixXd &source)
void set_target (const Eigen::MatrixXd &target)
void set_corrs (const std::vector< Eigen::MatrixXd > &corrs)
void set_tfs (const std::vector< Eigen::Vector3d > &tfs)
void set_comment (const std::string &comment)
Friends
class boost::serialization::access
Constructor & Destructor Documentation
MatchInternal()
common::MatchInternal::MatchInternal () inline
Member Function Documentation
cell_size()
double common::MatchInternal::cell_size () const inline
ClearResults()
void common::MatchInternal::ClearResults () inline
Referenced by trimesh::ICP().
comment()
std::string common::MatchInternal::comment () const inline
corrs()
std::vector<Eigen::MatrixXd> common::MatchInternal::corrs () const inline
has_data()
bool common::MatchInternal::has_data () const inline
PushBack() [1/2]
void common::MatchInternal::PushBack (const Correspondences & corr, const Eigen::Vector3d & tf) inline
PushBack() [2/2]
void common::MatchInternal::PushBack (const Correspondences & corr, const std::vector< double > & tf) inline
serialize()
template<typename Archive > void common::MatchInternal::serialize (Archive & ar, const unsigned int version) inline
serialize_mtx()
template<typename Archive > void common::MatchInternal::serialize_mtx (Archive & ar, std::string str, Eigen::MatrixXd & mtx) inline
set_cell_size()
void common::MatchInternal::set_cell_size (double cell_size) inline
set_comment()
void common::MatchInternal::set_comment (const std::string & comment) inline
set_corrs()
void common::MatchInternal::set_corrs (const std::vector< Eigen::MatrixXd > & corrs) inline
set_has_data()
void common::MatchInternal::set_has_data (bool has_data) inline
Referenced by trimesh::ICP().
set_source()
void common::MatchInternal::set_source (const Eigen::MatrixXd & source) inline
Referenced by trimesh::ICP().
set_target()
void common::MatchInternal::set_target (const Eigen::MatrixXd & target) inline
Referenced by trimesh::ICP().
set_tfs()
void common::MatchInternal::set_tfs (const std::vector< Eigen::Vector3d > & tfs) inline
source()
Eigen::MatrixXd common::MatchInternal::source () const inline
target()
Eigen::MatrixXd common::MatchInternal::target () const inline
tfs()
std::vector<Eigen::Vector3d> common::MatchInternal::tfs () const inline
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
The documentation for this class was generated from the following file:
match_utils.hpp