Symmetric NDT: NDTCell Class Reference
NDTCell Class Reference
#include <ndt_cell.h>
Public Member Functions
NDTCell ()
void ComputeGaussian ()
void ComputePGaussian ()
void ComputeNGaussian ()
void AddPoint (const Vector2d &point)
void AddPointWithCovariance (const Vector2d &point, const Matrix2d &covariance)
void AddNormal (const Vector2d &normal)
MatrixXd GetPointsMatrix () const
MatrixXd GetNormalsMatrix () const
string ToString ()
int GetN () const
bool GetPHasGaussian () const
bool GetNHasGaussian () const
bool BothHasGaussian () const
double GetSkewRad () const
double GetSize () const
Vector2d GetCenter () const
Vector2d GetPointMean () const
Matrix2d GetPointCov () const
Vector2d GetPointEvals () const
Matrix2d GetPointEvecs () const
Vector2d GetNormalMean () const
Matrix2d GetNormalCov () const
Vector2d GetNormalEvals () const
Matrix2d GetNormalEvecs () const
vector< Vector2d > GetPoints () const
vector< Vector2d > GetNormals () const
void SetN (int n)
void SetPHasGaussian (bool phasgaussian)
void SetNHasGaussian (bool nhasgaussian)
void SetSkewRad (double skew_rad)
void SetSize (double size)
void SetCenter (const Vector2d &center)
void SetPointMean (const Vector2d &mean)
void SetPointCov (const Matrix2d &cov)
void SetPointEvals (const Vector2d &evals)
void SetPointEvecs (const Matrix2d &evecs)
void SetNormalMean (const Vector2d &mean)
void SetNormalCov (const Matrix2d &cov)
void SetNormalEvals (const Vector2d &evals)
void SetNormalEvecs (const Matrix2d &evecs)
Public Attributes
bool mark
Constructor & Destructor Documentation
NDTCell()
NDTCell::NDTCell ()
Member Function Documentation
AddNormal()
void NDTCell::AddNormal (const Vector2d & normal)
Referenced by NDTGrid::AddPointAndNormal(), NDTGrid::AddPointAndNormalWithCovariance(), and MakeCell().
AddPoint()
void NDTCell::AddPoint (const Vector2d & point)
Referenced by NDTGrid::AddPoint(), and NDTGrid::AddPointAndNormal().
AddPointWithCovariance()
void NDTCell::AddPointWithCovariance (const Vector2d & point, const Matrix2d & covariance)
Referenced by NDTGrid::AddPointAndNormalWithCovariance(), and MakeCell().
BothHasGaussian()
bool NDTCell::BothHasGaussian () const inline
ComputeGaussian()
void NDTCell::ComputeGaussian ()
Referenced by NDTMap::LoadPointCloud(), NDTMap::LoadPointCloudWithCovariances(), and MakeCell().
ComputeNGaussian()
void NDTCell::ComputeNGaussian ()
ComputePGaussian()
void NDTCell::ComputePGaussian ()
GetCenter()
Vector2d NDTCell::GetCenter () const inline
Referenced by CorrespondenceMsg(), MarkerArrayOfNDTCell(), and MarkerArrayOfNDTCell2().
GetN()
int NDTCell::GetN () const inline
Referenced by CorrespondenceMsg().
GetNHasGaussian()
bool NDTCell::GetNHasGaussian () const inline
Referenced by MarkerArrayOfNDTCell(), and MarkerArrayOfNDTCell2().
GetNormalCov()
Matrix2d NDTCell::GetNormalCov () const inline
Referenced by CorrespondenceMsg(), MarkerArrayOfNDTCell(), MarkerArrayOfNDTCell2(), CostFunctor::MeanAndCov(), CostFunctions::OldMeanAndCov(), CostFunctor::operator()(), and CostFunctor::Score().
GetNormalEvals()
Vector2d NDTCell::GetNormalEvals () const inline
GetNormalEvecs()
Matrix2d NDTCell::GetNormalEvecs () const inline
GetNormalMean()
Vector2d NDTCell::GetNormalMean () const inline
Referenced by CorrespondenceMsg(), MarkerArrayOfNDTCell(), MarkerArrayOfNDTCell2(), CostFunctor::MeanAndCov(), CostFunctions::NewMeanAndCov(), CostFunctions::OldMeanAndCov(), CostFunctor::operator()(), and CostFunctor::Score().
GetNormals()
vector<Vector2d> NDTCell::GetNormals () const inline
Referenced by CorrespondenceMsg().
GetNormalsMatrix()
MatrixXd NDTCell::GetNormalsMatrix () const
GetPHasGaussian()
bool NDTCell::GetPHasGaussian () const inline
GetPointCov()
Matrix2d NDTCell::GetPointCov () const inline
Referenced by CorrespondenceMsg(), MarkerArrayOfNDTCell(), MarkerArrayOfNDTCell2(), CostFunctor::MeanAndCov(), CostFunctions::NewMeanAndCov(), CostFunctions::OldMeanAndCov(), CostFunctor::operator()(), and CostFunctor::Score().
GetPointEvals()
Vector2d NDTCell::GetPointEvals () const inline
GetPointEvecs()
Matrix2d NDTCell::GetPointEvecs () const inline
GetPointMean()
Vector2d NDTCell::GetPointMean () const inline
Referenced by CorrespondenceMsg(), main(), MarkerArrayOfCorrespondences(), MarkerArrayOfNDTCell(), MarkerArrayOfNDTCell2(), CostFunctor::MeanAndCov(), CostFunctions::NewMeanAndCov(), CostFunctions::OldMeanAndCov(), CostFunctor::operator()(), and CostFunctor::Score().
GetPoints()
vector<Vector2d> NDTCell::GetPoints () const inline
GetPointsMatrix()
MatrixXd NDTCell::GetPointsMatrix () const
GetSize()
double NDTCell::GetSize () const inline
Referenced by MarkerArrayOfNDTCell(), and MarkerArrayOfNDTCell2().
GetSkewRad()
double NDTCell::GetSkewRad () const inline
Referenced by MarkerArrayOfNDTCell(), and MarkerArrayOfNDTCell2().
SetCenter()
void NDTCell::SetCenter (const Vector2d & center) inline
Referenced by main(), and MakeCell().
SetN()
void NDTCell::SetN (int n) inline
SetNHasGaussian()
void NDTCell::SetNHasGaussian (bool nhasgaussian) inline
Referenced by main().
SetNormalCov()
void NDTCell::SetNormalCov (const Matrix2d & cov) inline
Referenced by main().
SetNormalEvals()
void NDTCell::SetNormalEvals (const Vector2d & evals) inline
SetNormalEvecs()
void NDTCell::SetNormalEvecs (const Matrix2d & evecs) inline
SetNormalMean()
void NDTCell::SetNormalMean (const Vector2d & mean) inline
Referenced by main().
SetPHasGaussian()
void NDTCell::SetPHasGaussian (bool phasgaussian) inline
SetPointCov()
void NDTCell::SetPointCov (const Matrix2d & cov) inline
Referenced by main().
SetPointEvals()
void NDTCell::SetPointEvals (const Vector2d & evals) inline
SetPointEvecs()
void NDTCell::SetPointEvecs (const Matrix2d & evecs) inline
SetPointMean()
void NDTCell::SetPointMean (const Vector2d & mean) inline
Referenced by main().
SetSize()
void NDTCell::SetSize (double size) inline
Referenced by main(), and MakeCell().
SetSkewRad()
void NDTCell::SetSkewRad (double skew_rad) inline
ToString()
string NDTCell::ToString ()
Member Data Documentation
mark
bool NDTCell::mark
The documentation for this class was generated from the following files:
ndt_cell.h
ndt_cell.cc