Symmetric NDT: common Namespace Reference
common Namespace Reference
Classes
struct Correspondences
class MatchInternal
struct MatchPackage
class MatchResults
class RandomTransformGenerator2D
Enumerations
enum Color {
Color::kRed, Color::kLime, Color::kBlue, Color::kWhite,
Color::kBlack, Color::kGray, Color::kYellow, Color::kAqua,
Color::kFuchsia
}
Functions
template<typename T >
void SerializationInput (const std::string &filepath, T &msg)
template<typename T >
void SerializationOutput (const std::string &filepath, const T &msg)
std::vector< std::string > GetDataPath (std::string data)
Eigen::Affine3d Affine3dFromXYZRPY (const Eigen::Vector3d &xyz, const Eigen::Vector3d &rpy)
Eigen::Affine3d Affine3dFromAffine2d (const Eigen::Affine2d &aff)
Eigen::Affine3d Affine3dFromMatrix3d (const Eigen::Matrix3d &mtx)
Eigen::Affine3d Affine3dFromMatrix4f (const Eigen::Matrix4f &mtx)
Eigen::Matrix< double, 6, 1 > XYZRPYFromAffine3d (const Eigen::Affine3d &mtx)
Eigen::Matrix< double, 6, 1 > XYZRPYFromMatrix4f (const Eigen::Matrix4f &mtx)
Eigen::Vector3d XYTRadianFromMatrix3d (const Eigen::Matrix3d &mtx)
Eigen::Vector3d XYTDegreeFromMatrix3d (const Eigen::Matrix3d &mtx)
Eigen::Matrix3d Matrix3dFromXYTRadian (const Eigen::Vector3d &xyt)
Eigen::Matrix3d Matrix3dFromXYTDegree (const Eigen::Vector3d &xyt)
Eigen::Matrix3d Matrix3dFromMatrix4f (const Eigen::Matrix4f &mtx)
Eigen::Matrix4f Matrix4fFromMatrix3d (const Eigen::Matrix3d &mtx)
Eigen::Matrix4f Matrix4fFromXYTRadian (const Eigen::Vector3d &xyt)
geometry_msgs::TransformStamped TstFromAffine3d (const Eigen::Affine3d &T, const ros::Time &stamp, const std::string &frame_id, const std::string &child_frame_id)
geometry_msgs::TransformStamped TstFromMatrix4f (const Eigen::Matrix4f &T, const ros::Time &stamp, const std::string &frame_id, const std::string &child_frame_id)
Eigen::Affine3d Conserve2DFromAffine3d (const Eigen::Affine3d &T)
Eigen::Vector2d TransNormRotDegAbsFromMatrix3d (const Eigen::Matrix3d &mtx)
geometry_msgs::Pose PoseInterpolate (const geometry_msgs::PoseStamped &p1, const geometry_msgs::PoseStamped &p2, const ros::Time &time)
template<typename T >
geometry_msgs::Pose GetPose (const T &poses, const ros::Time &time)
template<typename T >
void SerializeOut (std::string file_name, const T &data)
template<typename T >
void SerializeIn (std::string file_name, T &data)
std::vector< std::vector< double > > Combinations (std::vector< std::vector< double >> x)
std_msgs::ColorRGBA MakeColorRGBA (const Color &color, double alpha=1.)
visualization_msgs::Marker MakeArrowMarkerByEnds (int idx, const std::string &frame_id, const Eigen::Vector3d &start, const Eigen::Vector3d &end, const Color &color)
visualization_msgs::Marker MakeArrowMarkerByPose (int idx, const std::string &frame_id, const geometry_msgs::Pose &pose, const Color &color)
visualization_msgs::Marker MakeCovarianceMarker (int idx, const std::string &frame_id, const Eigen::Vector2d &pt, const Eigen::Matrix2d &cov, const Color &color)
visualization_msgs::Marker MakeTextMarker (int idx, const std::string &frame_id, const std::string &text, const geometry_msgs::Pose &pose, const Color &color)
Enumeration Type Documentation
Color
enum common::Color strong
Enumerator
kRed
kLime
kBlue
kWhite
kBlack
kGray
kYellow
kAqua
kFuchsia
Function Documentation
Affine3dFromAffine2d()
Eigen::Affine3d common::Affine3dFromAffine2d (const Eigen::Affine2d & aff)
Referenced by Affine3dFromMatrix3d(), and main().
Affine3dFromMatrix3d()
Eigen::Affine3d common::Affine3dFromMatrix3d (const Eigen::Matrix3d & mtx)
Affine3dFromMatrix4f()
Eigen::Affine3d common::Affine3dFromMatrix4f (const Eigen::Matrix4f & mtx)
Referenced by MakePST(), TstFromMatrix4f(), and XYZRPYFromMatrix4f().
Affine3dFromXYZRPY()
Eigen::Affine3d common::Affine3dFromXYZRPY (const Eigen::Vector3d & xyz, const Eigen::Vector3d & rpy)
Referenced by Conserve2DFromAffine3d().
Combinations()
std::vector<std::vector<double> > common::Combinations (std::vector< std::vector< double >> x)
Conserve2DFromAffine3d()
Eigen::Affine3d common::Conserve2DFromAffine3d (const Eigen::Affine3d & T)
Referenced by cb(), GetPosesDis(), MakeGtLocal(), and MakeLocalGt().
GetDataPath()
std::vector<std::string> common::GetDataPath (std::string data)
GetPose()
template<typename T > geometry_msgs::Pose common::GetPose (const T & poses, const ros::Time & time)
Referenced by cb(), and MakeGtLocal().
MakeArrowMarkerByEnds()
visualization_msgs::Marker common::MakeArrowMarkerByEnds (int idx, const std::string & frame_id, const Eigen::Vector3d & start, const Eigen::Vector3d & end, const Color & color)
MakeArrowMarkerByPose()
visualization_msgs::Marker common::MakeArrowMarkerByPose (int idx, const std::string & frame_id, const geometry_msgs::Pose & pose, const Color & color)
MakeColorRGBA()
std_msgs::ColorRGBA common::MakeColorRGBA (const Color & color, double alpha = 1.)
Referenced by main(), MakeArrowMarkerByEnds(), MakeArrowMarkerByPose(), MakeCovarianceMarker(), MakePointsNormalMarker(), and MakeTextMarker().
MakeCovarianceMarker()
visualization_msgs::Marker common::MakeCovarianceMarker (int idx, const std::string & frame_id, const Eigen::Vector2d & pt, const Eigen::Matrix2d & cov, const Color & color)
MakeTextMarker()
visualization_msgs::Marker common::MakeTextMarker (int idx, const std::string & frame_id, const std::string & text, const geometry_msgs::Pose & pose, const Color & color)
Referenced by MakeTexts().
Matrix3dFromMatrix4f()
Eigen::Matrix3d common::Matrix3dFromMatrix4f (const Eigen::Matrix4f & mtx)
Referenced by DoPCLSICP(), main(), and Matrix3dFromXForm().
Matrix3dFromXYTDegree()
Eigen::Matrix3d common::Matrix3dFromXYTDegree (const Eigen::Vector3d & xyt)
Matrix3dFromXYTRadian()
Eigen::Matrix3d common::Matrix3dFromXYTRadian (const Eigen::Vector3d & xyt)
Referenced by Matrix3dFromMatrix4f(), Matrix3dFromXYTDegree(), and Matrix4fFromXYTRadian().
Matrix4fFromMatrix3d()
Eigen::Matrix4f common::Matrix4fFromMatrix3d (const Eigen::Matrix3d & mtx)
Referenced by DoPCLSICP(), DoSICP(), main(), and Matrix4fFromXYTRadian().
Matrix4fFromXYTRadian()
Eigen::Matrix4f common::Matrix4fFromXYTRadian (const Eigen::Vector3d & xyt)
Referenced by AugmentPointCloud(), and main().
PoseInterpolate()
geometry_msgs::Pose common::PoseInterpolate (const geometry_msgs::PoseStamped & p1, const geometry_msgs::PoseStamped & p2, const ros::Time & time)
Referenced by GetPose().
SerializationInput()
template<typename T > void common::SerializationInput (const std::string & filepath, T & msg)
Referenced by GetFiles(), and main().
SerializationOutput()
template<typename T > void common::SerializationOutput (const std::string & filepath, const T & msg)
Referenced by main(), and savecb().
SerializeIn()
template<typename T > void common::SerializeIn (std::string file_name, T & data)
Referenced by main().
SerializeOut()
template<typename T > void common::SerializeOut (std::string file_name, const T & data)
Referenced by main().
TransNormRotDegAbsFromMatrix3d()
Eigen::Vector2d common::TransNormRotDegAbsFromMatrix3d (const Eigen::Matrix3d & mtx)
Referenced by cb().
TstFromAffine3d()
geometry_msgs::TransformStamped common::TstFromAffine3d (const Eigen::Affine3d & T, const ros::Time & stamp, const std::string & frame_id, const std::string & child_frame_id)
Referenced by TstFromMatrix4f().
TstFromMatrix4f()
geometry_msgs::TransformStamped common::TstFromMatrix4f (const Eigen::Matrix4f & T, const ros::Time & stamp, const std::string & frame_id, const std::string & child_frame_id)
XYTDegreeFromMatrix3d()
Eigen::Vector3d common::XYTDegreeFromMatrix3d (const Eigen::Matrix3d & mtx)
Referenced by main(), and TransNormRotDegAbsFromMatrix3d().
XYTRadianFromMatrix3d()
Eigen::Vector3d common::XYTRadianFromMatrix3d (const Eigen::Matrix3d & mtx)
Referenced by XYTDegreeFromMatrix3d().
XYZRPYFromAffine3d()
Eigen::Matrix<double, 6, 1> common::XYZRPYFromAffine3d (const Eigen::Affine3d & mtx)
Referenced by Conserve2DFromAffine3d(), and XYZRPYFromMatrix4f().
XYZRPYFromMatrix4f()
Eigen::Matrix<double, 6, 1> common::XYZRPYFromMatrix4f (const Eigen::Matrix4f & mtx)
Referenced by Matrix3dFromMatrix4f().