Symmetric NDT: matcher.cc File Reference
matcher.cc File Reference
Definition of Matching Algorithm.
#include <ceres/ceres.h>
#include <sndt/matcher.h>
#include <sndt/pcl_utils.h>
#include <sndt/visuals.h>
#include <common/other_utils.h>
#include <sndt/cost_functors.h>
Macros
#define thrds 4
Functions
int FindNearestNeighborIndex (const Eigen::Vector2d &query, const pcl::KdTreeFLANN< pcl::PointXY > &kd)
Eigen::Affine2d SICPMatch (const std::vector< Eigen::Vector2d > &target_points, const std::vector< Eigen::Vector2d > &source_points, SICPParameters &params, const Eigen::Affine2d &guess_tf)
Eigen::Affine2d NDTD2DMatch (const NDTMap &target_map, const NDTMap &source_map, NDTD2DParameters &params, const Eigen::Affine2d &guess_tf)
Eigen::Affine2d SNDTMatch (const SNDTMap &target_map, const SNDTMap &source_map, SNDTParameters &params, const Eigen::Affine2d &guess_tf)
Detailed Description
Definition of Matching Algorithm.
Author
HuaTsai (huats.nosp@m.ai.e.nosp@m.ed07g.nosp@m.@nct.nosp@m.u.edu.nosp@m..tw)
Version
0.1
Date
2021-07-29
Copyright
Copyright (c) 2021
Macro Definition Documentation
thrds
#define thrds 4
Function Documentation
FindNearestNeighborIndex()
int FindNearestNeighborIndex (const Eigen::Vector2d & query, const pcl::KdTreeFLANN< pcl::PointXY > & kd)
Referenced by NDTD2DMatch(), SICPMatch(), and SNDTMatch().
NDTD2DMatch()
Eigen::Affine2d NDTD2DMatch (const NDTMap & target_map, const NDTMap & source_map, NDTD2DParameters & params, const Eigen::Affine2d & guess_tf)
Referenced by cb(), and main().
SICPMatch()
Eigen::Affine2d SICPMatch (const std::vector< Eigen::Vector2d > & target_points, const std::vector< Eigen::Vector2d > & source_points, SICPParameters & params, const Eigen::Affine2d & guess_tf)
Referenced by cb(), and main().
SNDTMatch()
Eigen::Affine2d SNDTMatch (const SNDTMap & target_map, const SNDTMap & source_map, SNDTParameters & params, const Eigen::Affine2d & guess_tf)
Referenced by cb(), and main().