Symmetric NDT: wrapper.hpp File Reference
wrapper.hpp File Reference
#include <sndt/pcl_utils.h>
#include <sndt/matcher.h>
#include <common/EgoPointClouds.h>
#include <common/common.h>
#include <nav_msgs/Path.h>
Functions
std::vector< std::pair< std::vector< Eigen::Vector2d >, Eigen::Affine2d > > Augment (const std::vector< common::EgoPointClouds > &vepcs, int start, int end, Eigen::Affine2d &T, std::vector< Eigen::Affine2d > &allT)
std::vector< Eigen::Vector2d > AugmentPoints (const std::vector< common::EgoPointClouds > &vepcs, int start, int end, Eigen::Affine2d &T, std::vector< Eigen::Affine2d > &allT)
NDTMap MakeNDTMap (const std::vector< std::pair< std::vector< Eigen::Vector2d >, Eigen::Affine2d >> &data, const NDTD2DParameters &params)
SNDTMap MakeSNDTMap (const std::vector< std::pair< std::vector< Eigen::Vector2d >, Eigen::Affine2d >> &data, const SNDTParameters &params)
void MakeGtLocal (nav_msgs::Path &path, const ros::Time &start)
void WriteToFile (const nav_msgs::Path &path, std::string filename)
Detailed Description
Author
HuaTsai (huats.nosp@m.ai.e.nosp@m.ed07g.nosp@m.@nct.nosp@m.u.edu.nosp@m..tw)
Version
0.1
Date
2021-07-30
Copyright
Copyright (c) 2021
Function Documentation
Augment()
std::vector<std::pair<std::vector<Eigen::Vector2d>, Eigen::Affine2d> > Augment (const std::vector< common::EgoPointClouds > & vepcs, int start, int end, Eigen::Affine2d & T, std::vector< Eigen::Affine2d > & allT)
Referenced by cb(), and main().
AugmentPoints()
std::vector<Eigen::Vector2d> AugmentPoints (const std::vector< common::EgoPointClouds > & vepcs, int start, int end, Eigen::Affine2d & T, std::vector< Eigen::Affine2d > & allT)
Referenced by cb(), and main().
MakeGtLocal()
void MakeGtLocal (nav_msgs::Path & path, const ros::Time & start)
Referenced by main().
MakeNDTMap()
NDTMap MakeNDTMap (const std::vector< std::pair< std::vector< Eigen::Vector2d >, Eigen::Affine2d >> & data, const NDTD2DParameters & params)
Referenced by cb(), and main().
MakeSNDTMap()
SNDTMap MakeSNDTMap (const std::vector< std::pair< std::vector< Eigen::Vector2d >, Eigen::Affine2d >> & data, const SNDTParameters & params)
Referenced by cb(), and main().
WriteToFile()
void WriteToFile (const nav_msgs::Path & path, std::string filename)
Referenced by main().