Symmetric NDT: ndt_visualizations.h File Reference
ndt_visualizations.h File Reference
#include <bits/stdc++.h>
#include <Eigen/Eigen>
#include <visualization_msgs/MarkerArray.h>
#include "sndt/ndt_map.h"
Enumerations
enum Color {
Color::kRed, Color::kLime, Color::kBlue, Color::kWhite,
Color::kBlack, Color::kGray, Color::kYellow, Color::kAqua,
Color::kFuchsia
}
Functions
std_msgs::ColorRGBA MakeColorRGBA (const Color &color, double alpha=1.)
vector< Vector2d > FindTangentPoints (const Marker &eclipse, const Vector2d &point)
void UpdateMarkerArray (MarkerArray &markerarray, Marker marker)
MarkerArray JoinMarkers (const vector< Marker > &ms)
MarkerArray JoinMarkerArrays (const vector< MarkerArray > &mas)
MarkerArray JoinMarkerArraysAndMarkers (const vector< MarkerArray > &mas, const vector< Marker > &ms={})
Marker MarkerOfBoundary (const Vector2d &center, double size, double skew_rad=0, const Color &color=Color::kBlack)
Marker MarkerOfEclipse (const Vector2d &mean, const Matrix2d &covariance, const Color &color=Color::kLime, double alpha=0.6)
Marker MarkerOfCircle (const Vector2d &mean, double size, const Color &color=Color::kLime, double alpha=0.6)
Marker MarkerOfLines (const vector< Vector2d > &points, const Color &color=Color::kGray, double alpha=0.6)
Marker MarkerOfLinesByEndPoints (const vector< Vector2d > &points, const Color &color=Color::kGray, double alpha=0.6)
vector< Vector2d > PointsOfNDTMap (const NDTMap &map)
vector< Vector2d > PointsOfNDTMap (const vector< shared_ptr< NDTCell >> &map)
Marker MarkerOfPoints (const vector< Vector2d > &points, double size=0.1, const Color &color=Color::kLime, double alpha=1.0)
Marker MarkerOfPoints (const MatrixXd &points, double size=0.1, const Color &color=Color::kLime, double alpha=1.0)
Marker MarkerOfArrow (const Vector2d &start, const Vector2d &end, const Color &color=Color::kGray, double alpha=0.6)
Marker MarkerOfText (string text, const Vector2d &position, const Color &color=Color::kBlack, double alpha=1.0)
MarkerArray MarkerArrayOfArrow (const MatrixXd &start, const MatrixXd &end, const Color &color=Color::kRed, double alpha=1.0)
MarkerArray MarkerArrayOfArrow (const vector< Vector2d > &starts, const vector< Vector2d > &ends, const Color &color=Color::kRed, double alpha=1.0)
MarkerArray MarkerArrayOfNDTCell (const NDTCell *cell)
MarkerArray MarkerArrayOfNDTCell2 (const NDTCell *cell)
MarkerArray MarkerArrayOfNDTMap (const NDTMap &map, bool is_target_color=false)
MarkerArray MarkerArrayOfNDTMap (const vector< shared_ptr< NDTCell >> &map, bool is_target_color=false)
MarkerArray MarkerArrayOfCorrespondences (const NDTCell *source_cell, const NDTCell *target_cell, string text, const Color &color=Color::kBlack)
MarkerArray MarkerArrayOfSensor (const vector< Affine2d > &affs)
Enumeration Type Documentation
Color
enum Color strong
Enumerator
kRed
kLime
kBlue
kWhite
kBlack
kGray
kYellow
kAqua
kFuchsia
Function Documentation
FindTangentPoints()
vector<Vector2d> FindTangentPoints (const Marker & eclipse, const Vector2d & point)
Referenced by main(), MarkerArrayOfNDTCell(), and MarkerArrayOfNDTCell2().
JoinMarkerArrays()
MarkerArray JoinMarkerArrays (const vector< MarkerArray > & mas)
Referenced by NDTMatcher::CeresMatch().
JoinMarkerArraysAndMarkers()
MarkerArray JoinMarkerArraysAndMarkers (const vector< MarkerArray > & mas, const vector< Marker > & ms = {})
Referenced by main(), MarkerArrayOfCorrespondences(), MarkerArrayOfNDTCell(), MarkerArrayOfNDTCell2(), and MarkerArrayOfNDTMap().
JoinMarkers()
MarkerArray JoinMarkers (const vector< Marker > & ms)
Referenced by main().
MakeColorRGBA()
std_msgs::ColorRGBA MakeColorRGBA (const Color & color, double alpha = 1.)
Referenced by MarkerArrayOfArrow(), MarkerArrayOfSensor(), MarkerOfArrow(), MarkerOfBoundary(), MarkerOfCircle(), MarkerOfEclipse(), MarkerOfLines(), MarkerOfPoints(), and MarkerOfText().
MarkerArrayOfArrow() [1/2]
MarkerArray MarkerArrayOfArrow (const MatrixXd & start, const MatrixXd & end, const Color & color = Color::kRed, double alpha = 1.0)
Referenced by cb(), and main().
MarkerArrayOfArrow() [2/2]
MarkerArray MarkerArrayOfArrow (const vector< Vector2d > & starts, const vector< Vector2d > & ends, const Color & color = Color::kRed, double alpha = 1.0)
MarkerArrayOfCorrespondences()
MarkerArray MarkerArrayOfCorrespondences (const NDTCell * source_cell, const NDTCell * target_cell, string text, const Color & color = Color::kBlack)
Referenced by NDTMatcher::CeresMatch().
MarkerArrayOfNDTCell()
MarkerArray MarkerArrayOfNDTCell (const NDTCell * cell)
Referenced by main(), MarkerArrayOfCorrespondences(), and MarkerArrayOfNDTMap().
MarkerArrayOfNDTCell2()
MarkerArray MarkerArrayOfNDTCell2 (const NDTCell * cell)
Referenced by main(), MarkerArrayOfCorrespondences(), and MarkerArrayOfNDTMap().
MarkerArrayOfNDTMap() [1/2]
MarkerArray MarkerArrayOfNDTMap (const NDTMap & map, bool is_target_color = false)
Referenced by cb(), and main().
MarkerArrayOfNDTMap() [2/2]
MarkerArray MarkerArrayOfNDTMap (const vector< shared_ptr< NDTCell >> & map, bool is_target_color = false)
MarkerArrayOfSensor()
MarkerArray MarkerArrayOfSensor (const vector< Affine2d > & affs)
Referenced by main().
MarkerOfArrow()
Marker MarkerOfArrow (const Vector2d & start, const Vector2d & end, const Color & color = Color::kGray, double alpha = 0.6)
MarkerOfBoundary()
Marker MarkerOfBoundary (const Vector2d & center, double size, double skew_rad = 0, const Color & color = Color::kBlack)
Referenced by main(), MarkerArrayOfNDTCell(), and MarkerArrayOfNDTCell2().
MarkerOfCircle()
Marker MarkerOfCircle (const Vector2d & mean, double size, const Color & color = Color::kLime, double alpha = 0.6)
Referenced by main().
MarkerOfEclipse()
Marker MarkerOfEclipse (const Vector2d & mean, const Matrix2d & covariance, const Color & color = Color::kLime, double alpha = 0.6)
Note: "pseudo" computes complex eigen value if no real solution However, covariance is always a real symmetric matrix, which means 1) it is Hermitia, all its eigenvalues are real 2) the decomposed matrix is an orthogonal matrix, i.e., rotaion matrix
Referenced by main(), MarkerArrayOfNDTCell(), and MarkerArrayOfNDTCell2().
MarkerOfLines()
Marker MarkerOfLines (const vector< Vector2d > & points, const Color & color = Color::kGray, double alpha = 0.6)
Referenced by main(), MarkerArrayOfCorrespondences(), MarkerArrayOfNDTCell(), MarkerArrayOfNDTCell2(), and MarkerOfLinesByEndPoints().
MarkerOfLinesByEndPoints()
Marker MarkerOfLinesByEndPoints (const vector< Vector2d > & points, const Color & color = Color::kGray, double alpha = 0.6)
Referenced by main().
MarkerOfPoints() [1/2]
Marker MarkerOfPoints (const vector< Vector2d > & points, double size = 0.1, const Color & color = Color::kLime, double alpha = 1.0)
Referenced by main(), MarkerOfPoints(), and ThePoints().
MarkerOfPoints() [2/2]
Marker MarkerOfPoints (const MatrixXd & points, double size = 0.1, const Color & color = Color::kLime, double alpha = 1.0)
MarkerOfText()
Marker MarkerOfText (string text, const Vector2d & position, const Color & color = Color::kBlack, double alpha = 1.0)
Referenced by MarkerArrayOfCorrespondences().
PointsOfNDTMap() [1/2]
vector<Vector2d> PointsOfNDTMap (const NDTMap & map)
Referenced by main().
PointsOfNDTMap() [2/2]
vector<Vector2d> PointsOfNDTMap (const vector< shared_ptr< NDTCell >> & map)
UpdateMarkerArray()
void UpdateMarkerArray (MarkerArray & markerarray, Marker marker)
Referenced by main().