Symmetric NDT: eigen_utils.h File Reference
eigen_utils.h File Reference
Eigen Utilities.
#include <bits/stdc++.h>
#include <Eigen/Dense>
#include <gsl/gsl>
Functions
Eigen::Vector2d ComputeMean (const std::vector< Eigen::Vector2d > &points)
Compute mean of points.
Eigen::Matrix2d ComputeMean (const std::vector< Eigen::Matrix2d > &matrices)
Compute mean of matrices.
Eigen::Matrix2d ComputeCov (const std::vector< Eigen::Vector2d > &points, const Eigen::Vector2d &mean, const Eigen::Matrix2d &offset=Eigen::Matrix2d::Zero())
Compute covariance of points.
Eigen::Matrix2d ComputeCov (const std::vector< Eigen::Vector2d > &points, const Eigen::Vector2d &mean, const std::vector< Eigen::Matrix2d > &offsets)
Compute covariance of points.
void ComputeEvalEvec (const Eigen::Matrix2d &covariance, Eigen::Vector2d &evals, Eigen::Matrix2d &evecs)
Compute eigenvalues and eigenvectors from covariance.
std::vector< Eigen::Vector2d > ExcludeNaNInf (const std::vector< Eigen::Vector2d > &points)
Remove points that contain NaN or Inf.
std::pair< std::vector< Eigen::Vector2d >, std::vector< Eigen::Matrix2d > > ExcludeNaNInf2 (const std::vector< Eigen::Vector2d > &points, const std::vector< Eigen::Matrix2d > &covariances)
Remove points and covariances that contain NaN or Inf.
Detailed Description
Eigen Utilities.
Author
HuaTsai (huats.nosp@m.ai.e.nosp@m.ed07g.nosp@m.@nct.nosp@m.u.edu.nosp@m..tw)
Version
0.1
Date
2021-07-29
Copyright
Copyright (c) 2021
Function Documentation
ComputeCov() [1/2]
Eigen::Matrix2d ComputeCov (const std::vector< Eigen::Vector2d > & points, const Eigen::Vector2d & mean, const Eigen::Matrix2d & offset = Eigen::Matrix2d::Zero()) inline
Compute covariance of points.
Parameters
points Input points
mean Input mean of points
offset Offset added to the covariance (default zero)
Returns
Covariance of points
Note
This function does not check the validity of its elements
Referenced by ComputeCov(), SNDTCell::ComputeGaussian(), and NDTCell::ComputeGaussian().
ComputeCov() [2/2]
Eigen::Matrix2d ComputeCov (const std::vector< Eigen::Vector2d > & points, const Eigen::Vector2d & mean, const std::vector< Eigen::Matrix2d > & offsets) inline
Compute covariance of points.
Parameters
points Input points
mean Input mean of points
offsets Offsets that will be averaged and added to the covariance
Returns
Covariance of points
Precondition
Arguments points and offsets should have the same size.
Note
This function does not check the validity of its elements
ComputeEvalEvec()
void ComputeEvalEvec (const Eigen::Matrix2d & covariance, Eigen::Vector2d & evals, Eigen::Matrix2d & evecs) inline
Compute eigenvalues and eigenvectors from covariance.
Parameters
[in] covariance Input covariance
[out] evals Output eigenvalues
[out] evecs Output eigenvectors
Referenced by SNDTCell::ComputeGaussian(), and NDTCell::ComputeGaussian().
ComputeMean() [1/2]
Eigen::Vector2d ComputeMean (const std::vector< Eigen::Vector2d > & points) inline
Compute mean of points.
Parameters
points Input points
Returns
Mean of points
Note
This function does not check the validity of its elements
Referenced by ComputeCov(), SNDTCell::ComputeGaussian(), NDTCell::ComputeGaussian(), and MapInterface::GuessMapSize().
ComputeMean() [2/2]
Eigen::Matrix2d ComputeMean (const std::vector< Eigen::Matrix2d > & matrices) inline
Compute mean of matrices.
Parameters
matrices Input matrices
Returns
Mean of matrices
Note
This function does not check the validity of its elements
ExcludeNaNInf()
std::vector<Eigen::Vector2d> ExcludeNaNInf (const std::vector< Eigen::Vector2d > & points) inline
Remove points that contain NaN or Inf.
Parameters
points Input points
Returns
Result points
Referenced by SNDTCell::ComputeGaussian(), MapInterface::GuessMapSize(), and SICPMatch().
ExcludeNaNInf2()
std::pair<std::vector<Eigen::Vector2d>, std::vector<Eigen::Matrix2d> > ExcludeNaNInf2 (const std::vector< Eigen::Vector2d > & points, const std::vector< Eigen::Matrix2d > & covariances) inline
Remove points and covariances that contain NaN or Inf.
Parameters
points Input points
covariances Input covariances
Returns
Pair of result points and result covariances
This function keeps the entries that have both valid point and valid covariance
Precondition
Arguments points and covariances should have the same size
Referenced by SNDTCell::ComputeGaussian(), and NDTCell::ComputeGaussian().