Symmetric NDT: trimesh::KDtree Class Reference
trimesh::KDtree Class Reference
#include <KDtree.h>
Classes
struct CompatFunc
struct Node
struct NodeStorageBlock
Public Member Functions
KDtree (const float *ptlist, size_t n)
template<class T >
KDtree (const ::std::vector< T > &v)
KDtree (const float **pts, size_t n)
template<class T >
KDtree (::std::vector< T *> &pts)
~KDtree ()
const float * closest_to_pt (const float *p, float maxdist2=0.0f, const CompatFunc *iscompat=NULL, float approx_eps=0.0f) const
const float * closest_to_pt (const float *p, float maxdist2, float approx_eps) const
const float * closest_to_ray (const float *p, const float *dir, float maxdist2=0.0f, const CompatFunc *iscompat=NULL, float approx_eps=0.0f) const
const float * closest_to_ray (const float *p, const float *dir, float maxdist2, float approx_eps) const
void find_k_closest_to_pt (::std::vector< const float *> &knn, int k, const float *p, float maxdist2=0.0f, const CompatFunc *iscompat=NULL, float approx_eps=0.0f) const
void find_k_closest_to_pt (::std::vector< const float *> &knn, int k, const float *p, float maxdist2, float approx_eps) const
bool exists_pt_within (const float *p, float maxdist) const
Constructor & Destructor Documentation
KDtree() [1/4]
trimesh::KDtree::KDtree (const float * ptlist, size_t n) inline
KDtree() [2/4]
template<class T > trimesh::KDtree::KDtree (const ::std::vector< T > & v) inline
KDtree() [3/4]
trimesh::KDtree::KDtree (const float ** pts, size_t n) inline
KDtree() [4/4]
template<class T > trimesh::KDtree::KDtree (::std::vector< T *> & pts) inline
~KDtree()
trimesh::KDtree::~KDtree ()
Referenced by KDtree().
Member Function Documentation
closest_to_pt() [1/2]
const float * trimesh::KDtree::closest_to_pt (const float * p, float maxdist2 = 0.0f, const CompatFunc * iscompat = NULL, float approx_eps = 0.0f) const
Referenced by closest_to_pt(), trimesh::TriMesh::feature_size(), trimesh::find_overlap_onedir(), KDtree(), and trimesh::selectall_and_match().
closest_to_pt() [2/2]
const float* trimesh::KDtree::closest_to_pt (const float * p, float maxdist2, float approx_eps) const inline
closest_to_ray() [1/2]
const float * trimesh::KDtree::closest_to_ray (const float * p, const float * dir, float maxdist2 = 0.0f, const CompatFunc * iscompat = NULL, float approx_eps = 0.0f) const
Referenced by closest_to_pt(), and closest_to_ray().
closest_to_ray() [2/2]
const float* trimesh::KDtree::closest_to_ray (const float * p, const float * dir, float maxdist2, float approx_eps) const inline
exists_pt_within()
bool trimesh::KDtree::exists_pt_within (const float * p, float maxdist) const
Referenced by trimesh::compute_overlaps(), and find_k_closest_to_pt().
find_k_closest_to_pt() [1/2]
void trimesh::KDtree::find_k_closest_to_pt (::std::vector< const float *> & knn, int k, const float * p, float maxdist2 = 0.0f, const CompatFunc * iscompat = NULL, float approx_eps = 0.0f) const
Referenced by closest_to_ray(), find_k_closest_to_pt(), and trimesh::normals_from_points().
find_k_closest_to_pt() [2/2]
void trimesh::KDtree::find_k_closest_to_pt (::std::vector< const float *> & knn, int k, const float * p, float maxdist2, float approx_eps) const inline
The documentation for this class was generated from the following files:
KDtree.h
KDtree.cc