Symmetric NDT: std Namespace Reference
std Namespace Reference
Classes
struct conditional
struct conditional< false, T, F >
struct enable_if
struct enable_if< true, T >
struct integral_constant
struct is_arithmetic
struct is_floating_point
struct is_floating_point< const T >
struct is_floating_point< T[N]>
struct is_integral
struct is_integral< const T >
struct is_integral< T[N]>
Typedefs
typedef integral_constant< bool, true > true_type
typedef integral_constant< bool, false > false_type
Functions
template<size_t D, class T >
static void swap (const ::trimesh::Vec< D, T > &v1, const ::trimesh::Vec< D, T > &v2)
template<size_t I, size_t D, class T >
static T & get (::trimesh::Vec< D, T > &v)
template<size_t I, size_t D, class T >
static const T & get (const ::trimesh::Vec< D, T > &v)
Typedef Documentation
false_type
typedef integral_constant<bool, false> std::false_type
true_type
typedef integral_constant<bool, true> std::true_type
Function Documentation
get() [1/2]
template<size_t I, size_t D, class T > static T& std::get (::trimesh::Vec< D, T > & v) inline static
get() [2/2]
template<size_t I, size_t D, class T > static const T& std::get (const ::trimesh::Vec< D, T > & v) inline static
swap()
template<size_t D, class T > static void std::swap (const ::trimesh::Vec< D, T > & v1, const ::trimesh::Vec< D, T > & v2) inline static
Referenced by trimesh::Box< 3, float >::Box(), trimesh::KDtree::Node::build(), trimesh::clear_and_release(), trimesh::diagonalize_curv(), trimesh::eigdc(), trimesh::faceflip(), trimesh::ludcmp(), trimesh::Noise3D::Noise3D(), trimesh::norm_xf(), trimesh::orient(), and trimesh::Vec< 3, float >::swap().