Symmetric NDT: trimesh Namespace Reference
trimesh Namespace Reference
Namespaces
Mouse
Classes
struct AccumCurv
struct AccumDCurv
struct AccumVec
class Basis
class Box
class Color
class CompareArrayElements
class GLCamera
class GLManager
class KDtree
class Miniball
class Noise3D
class NormCompat
class PerlinNoise3D
struct PtPair
struct STATIC_ASSERTION_FAILURE
struct STATIC_ASSERTION_FAILURE< true >
class TriMesh
class Vec
struct Vec_data
struct Vec_data< 1, T >
struct Vec_data< 2, T >
struct Vec_data< 3, T >
struct Vec_data< 4, T >
struct Vec_uninitialized
class XForm
Typedefs
typedef Box< 3, float > box
typedef Box< 2, float > box2
typedef Box< 3, float > box3
typedef Box< 4, float > box4
typedef Box< 2, int > ibox2
typedef Box< 3, int > ibox3
typedef Box< 4, int > ibox4
typedef Box< 2, double > dbox2
typedef Box< 3, double > dbox3
typedef Box< 4, double > dbox4
typedef struct timeval timestamp
typedef Vec< 3, float > vec
typedef Vec< 3, float > point
typedef Vec< 2, float > vec2
typedef Vec< 3, float > vec3
typedef Vec< 4, float > vec4
typedef Vec< 2, float > point2
typedef Vec< 3, float > point3
typedef Vec< 4, float > point4
typedef Vec< 2, int > ivec2
typedef Vec< 3, int > ivec3
typedef Vec< 4, int > ivec4
typedef Vec< 2, double > dvec2
typedef Vec< 3, double > dvec3
typedef Vec< 4, double > dvec4
typedef XForm< double > xform
typedef XForm< double > dxform
typedef XForm< float > fxform
typedef ptrdiff_t GLsizeiptr
typedef ptrdiff_t GLintptr
typedef char GLchar
typedef GLuint * buffers
typedef GLsizeiptr size
typedef GLsizeiptr const void * data
typedef GLsizeiptr const void GLenum usage
typedef GLuint buffer
typedef GLsizei count
typedef GLsizei const GLchar *const * string
typedef GLsizei const GLchar *const const GLint * length
typedef GLenum pname
typedef GLenum GLint * params
typedef GLsizei bufSize
typedef GLsizei GLsizei GLchar * infoLog
typedef GLuint shader
typedef GLfloat v0
typedef GLfloat GLfloat v1
typedef GLfloat GLfloat GLfloat v2
typedef GLfloat GLfloat GLfloat GLfloat v3
typedef GLsizei GLboolean transpose
typedef GLsizei GLboolean const GLfloat * value
typedef GLuint index
typedef GLuint GLsizei GLsizei GLint GLenum * type
typedef GLuint GLsizei GLsizei GLint GLenum GLchar * name
typedef GLfloat x
typedef GLfloat GLfloat y
typedef GLfloat GLfloat GLfloat z
typedef GLfloat GLfloat GLfloat GLfloat w
typedef GLint GLenum GLboolean normalized
typedef GLint GLenum GLboolean GLsizei stride
typedef GLint GLenum GLboolean GLsizei const void * pointer
typedef GLuint * arrays
typedef GLuint * framebuffers
typedef GLenum attachment
typedef GLenum GLenum textarget
typedef GLenum GLenum GLuint texture
typedef GLenum GLenum GLuint GLint level
typedef GLuint framebuffer
typedef GLenum clamp
typedef pair< float, const float * > pt_with_d
Enumerations
enum ICP_xform_type { ICP_TRANSLATION, ICP_RIGID, ICP_SIMILARITY, ICP_AFFINE }
enum SubdivScheme {
SUBDIV_PLANAR, SUBDIV_LOOP, SUBDIV_LOOP_ORIG, SUBDIV_LOOP_NEW,
SUBDIV_BUTTERFLY, SUBDIV_BUTTERFLY_MODIFIED
}
enum FixedShape {
SHAPE_TETRAHEDRON, SHAPE_CUBE, SHAPE_OCTAHEDRON, SHAPE_DODECAHEDRON,
SHAPE_ICOSAHEDRON, SHAPE_TRUNCATED_TETRAHEDRON, SHAPE_CUBOCTAHEDRON, SHAPE_TRUNCATED_CUBE,
SHAPE_TRUNCATED_OCTAHEDRON, SHAPE_RHOMBICUBOCTAHEDRON, SHAPE_TRUNCATED_CUBOCTAHEDRON, SHAPE_ICOSIDODECAHEDRON,
SHAPE_TRUNCATED_DODECAHEDRON, SHAPE_TRUNCATED_ICOSAHEDRON, SHAPE_SNUB_CUBE, SHAPE_RHOMBICOSIDODECAHEDRON,
SHAPE_TRUNCATED_ICOSIDODECAHEDRON, SHAPE_SNUB_DODECAHEDRON, SHAPE_TRIAKIS_TETRAHEDRON, SHAPE_RHOMBIC_DODECAHEDRON,
SHAPE_TRIAKIS_OCTAHEDRON, SHAPE_TETRAKIS_HEXAHEDRON, SHAPE_DELTOIDAL_ICOSITETRAHEDRON, SHAPE_DISDYAKIS_DODECAHEDRON,
SHAPE_RHOMBIC_TRIACONTAHEDRON, SHAPE_TRIAKIS_ICOSAHEDRON, SHAPE_PENTAKIS_DODECAHEDRON, SHAPE_PENTAGONAL_ICOSITETRAHEDRON,
SHAPE_DELTOIDAL_HEXECONTAHEDRON, SHAPE_DISDYAKIS_TRIACONTAHEDRON, SHAPE_PENTAGONAL_HEXECONTAHEDRON
}
Functions
template<size_t D, class T >
static bool operator== (const Box< D, T > &b1, const Box< D, T > &b2)
template<size_t D, class T >
static bool operator!= (const Box< D, T > &b1, const Box< D, T > &b2)
template<size_t D, class T >
static bool operator! (const Box< D, T > &b)
static inline ::std::string bboxname (const ::std::string &filename)
static bool we_are_little_endian ()
static bool we_are_big_endian ()
static void swap_16 (unsigned char *p)
static void swap_32 (unsigned char *p)
static void swap_64 (unsigned char *p)
static void swap_short (short &x)
static void swap_ushort (unsigned short &x)
static void swap_int (int &x)
static void swap_unsigned (unsigned &x)
static void swap_float (float &x)
static void swap_double (double &x)
Grid * make_grid (TriMesh *mesh)
void compute_overlaps (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, const xform &xf2, const KDtree *kd1, const KDtree *kd2, const Grid *g1, const Grid *g2, ::std::vector< float > &o1, ::std::vector< float > &o2, float &maxdist, int verbose)
float ICP (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, xform &xf2, const KDtree *kd1, const KDtree *kd2, ::std::vector< float > &weights1, ::std::vector< float > &weights2, float maxdist=0.0f, int verbose=0, ICP_xform_type xform_type=ICP_RIGID)
float ICP (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, xform &xf2, const KDtree *kd1, const KDtree *kd2, int verbose=0, ICP_xform_type xform_type=ICP_RIGID)
float ICP (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, xform &xf2, int verbose=0, ICP_xform_type xform_type=ICP_RIGID)
float ICP (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, xform &xf2, const KDtree *kd1, const KDtree *kd2, ::std::vector< float > &weights1, ::std::vector< float > &weights2, float maxdist, int verbose, bool do_scale, bool do_affine=false)
float ICP (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, xform &xf2, const KDtree *kd1, const KDtree *kd2, int verbose, bool do_scale, bool do_affine=false)
float ICP (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, xform &xf2, int verbose, bool do_scale, bool do_affine=false)
template<class T , int N>
static bool ludcmp (T(&A)[N][N], int ind[N])
template<class T , int N>
static void lubksb (const T(&A)[N][N], const int ind[N], T b[N])
template<class T , int N>
static void lubksb (const T(&A)[N][N], const int ind[N], const T b[N], T x[N])
template<class T , int N>
static bool ldltdc (T(&A)[N][N], T rdiag[N])
template<class T , int N>
static void ldltsl (const T(&A)[N][N], const T rdiag[N], const T b[N], T x[N])
template<class T , int N>
static void ldltsl (const T(&A)[N][N], const T rdiag[N], T b[N])
template<class T , int N>
static void eigdc (T(&A)[N][N], T d[N])
template<class T , int N>
static void eigmult (const T(&A)[N][N], const T d[N], const T b[N], T x[N])
template<class T , int N>
static void eigmult (const T(&A)[N][N], const T d[N], T b[N])
template<class T , int M, int N>
static void svd (T(&A)[M][N], T s[N], T(&V)[N][N])
template<class T >
static T sqr (const T &x)
template<class T >
static T cube (const T &x)
template<class T >
static T sgn (const T &x)
template<class T >
static T sign (const T &x)
template<class T >
static double radians (const T &x)
static float radians (const float &x)
static long double radians (const long double &x)
template<class T >
static double degrees (const T &x)
static float degrees (const float &x)
static long double degrees (const long double &x)
template<class T >
static T fract (const T &x)
template<class T , class A , class B >
static T clamp (const T &x, const A &a, const B &b)
template<class T , class A >
static T mix (const T &x, const T &y, const A &a)
template<class T , class A >
static T step (const A &a, const T &x)
template<class T , class A , class B >
static T smoothstep (const A &a, const B &b, const T &x)
static unsigned xorshift_rnd (unsigned n=~0u)
template<class T >
static typename ::std::enable_if< ::std::is_integral< T >::value, T >::type uniform_rnd (T n)
template<class T >
static typename ::std::enable_if< ::std::is_floating_point< T >::value, T >::type uniform_rnd (T n)
static float uniform_rnd ()
template<class T >
static typename ::std::enable_if< ::std::is_floating_point< T >::value, T >::type normal_rnd (T sigma)
template<class T >
static typename ::std::enable_if< ::std::is_integral< T >::value, double >::type normal_rnd (T sigma)
static float normal_rnd ()
static inline ::std::string replace_ext (const ::std::string &filename, const ::std::string &ext)
static inline ::std::string string_printf (const char *format,...)
static bool begins_with (const char *s1, const char *s2)
static bool begins_with (const ::std::string &s1, const ::std::string &s2)
static bool ends_with (const char *s1, const char *s2)
static bool ends_with (const ::std::string &s1, const ::std::string &s2)
static bool contains (const char *s1, const char *s2)
static bool contains (const ::std::string &s1, const ::std::string &s2)
static float operator- (const timestamp &t1, const timestamp &t2)
static timestamp now ()
template<class T >
static void clear_and_release (::std::vector< T > &v)
void edgeflip (TriMesh *mesh)
void faceflip (TriMesh *mesh)
void umbrella (TriMesh *mesh, float stepsize, bool tangent=false)
void lmsmooth (TriMesh *mesh, int niters)
void numbrella (TriMesh *mesh, float stepsize)
void remove_vertices (TriMesh *mesh, const ::std::vector< bool > &toremove)
void remove_unused_vertices (TriMesh *mesh)
void remove_faces (TriMesh *mesh, const ::std::vector< bool > &toremove)
void remove_sliver_faces (TriMesh *mesh)
void remap_verts (TriMesh *mesh, const ::std::vector< int > &remap_table)
void reorder_verts (TriMesh *mesh)
void subdiv (TriMesh *mesh, SubdivScheme scheme=SUBDIV_LOOP)
void smooth_mesh (TriMesh *themesh, float sigma)
void bilateral_smooth_mesh (TriMesh *themesh, float sigma1, float sigma2)
template<class T >
void diffuse_vector (TriMesh *themesh, ::std::vector< T > &field, float sigma)
void diffuse_normals (TriMesh *themesh, float sigma)
void diffuse_curv (TriMesh *themesh, float sigma)
void diffuse_dcurv (TriMesh *themesh, float sigma)
void diagonalize_curv (const vec &old_u, const vec &old_v, float ku, float kuv, float kv, const vec &new_norm, vec &pdir1, vec &pdir2, float &k1, float &k2)
void proj_curv (const vec &old_u, const vec &old_v, float old_ku, float old_kuv, float old_kv, const vec &new_u, const vec &new_v, float &new_ku, float &new_kuv, float &new_kv)
void proj_dcurv (const vec &old_u, const vec &old_v, const Vec< 4 > old_dcurv, const vec &new_u, const vec &new_v, Vec< 4 > &new_dcurv)
void inflate (TriMesh *mesh, float amount)
void apply_xform (TriMesh *mesh, const xform &xf)
void trans (TriMesh *mesh, const vec &transvec)
void rot (TriMesh *mesh, float r, const vec &axis)
void scale (TriMesh *mesh, float s)
void scale (TriMesh *mesh, float sx, float sy, float sz)
void scale (TriMesh *mesh, float s, const vec &d)
void clip (TriMesh *mesh, const box &b)
point point_center_of_mass (const ::std::vector< point > &pts)
point mesh_center_of_mass (TriMesh *mesh)
void point_covariance (const ::std::vector< point > &pts, float(&C)[3][3])
void mesh_covariance (TriMesh *mesh, float(&C)[3][3])
void normalize_variance (TriMesh *mesh)
void pca_rotate (TriMesh *mesh)
void pca_snap (TriMesh *mesh)
void orient (TriMesh *mesh)
void erode (TriMesh *mesh)
void noisify (TriMesh *mesh, float amount)
void find_comps (TriMesh *mesh, ::std::vector< int > &comps, ::std::vector< int > &compsizes, bool conn_vert=false)
void select_comp (TriMesh *mesh, const ::std::vector< int > &comps, int whichcc)
void select_big_comps (TriMesh *mesh, const ::std::vector< int > &comps, const ::std::vector< int > &compsizes, int min_size, int total_largest=::std::numeric_limits< int >::max())
void select_small_comps (TriMesh *mesh, const ::std::vector< int > &comps, const ::std::vector< int > &compsizes, int max_size, int total_smallest=::std::numeric_limits< int >::max())
void find_overlap (TriMesh *mesh1, TriMesh *mesh2, float &area, float &rmsdist)
void find_overlap (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, const xform &xf2, float &area, float &rmsdist)
void find_overlap (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, const xform &xf2, const KDtree *kd1, const KDtree *kd2, float &area, float &rmsdist)
float iou (TriMesh *mesh1, TriMesh *mesh2)
float iou (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, const xform &xf2)
float iou (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, const xform &xf2, const KDtree *kd1, const KDtree *kd2)
void shared (TriMesh *mesh, float tol)
TriMesh * join (const ::std::vector< TriMesh *> &meshes, float tol=-1.0f)
TriMesh * make_plane (int tess_x, int tess_y=-1)
TriMesh * make_bump (int tess, float sigma=1.0f)
TriMesh * make_wave (int tess, float omega=M_PIf)
TriMesh * make_frac (int tess)
TriMesh * make_cube (int tess)
TriMesh * make_disc (int tess_th, int tess_r)
TriMesh * make_cyl (int tess_th, int tess_h, float r=1.0f)
TriMesh * make_ccyl (int tess_th, int tess_h, float r=1.0f)
TriMesh * make_scyl (int tess_th, int tess_h, float r=1.0f)
TriMesh * make_cone (int tess_th, int tess_r, float r=1.0f)
TriMesh * make_ccone (int tess_th, int tess_r, float r=1.0f)
TriMesh * make_torus (int tess_th, int tess_ph, float r=0.25f)
TriMesh * make_knot (int tess_th, int tess_ph, float r=0.2f)
TriMesh * make_klein (int tess_th, int tess_ph)
TriMesh * make_helix (int tess_th, int tess_ph, float turns, float r=0.2f)
TriMesh * make_sphere_polar (int tess_ph, int tess_th)
TriMesh * make_sphere_subdiv (int nfaces, int nsubdiv)
TriMesh * make_fixed_shape (FixedShape shape)
TriMesh * make_platonic (int nfaces)
TriMesh * make_surface_of_revolution (int tess_th, const ::std::vector< point > &curve_pts)
TriMesh * make_teapot (int tess, bool omit_bottom=false, bool taller=false)
template<size_t D, class T >
static const Vec< D, T > operator+ (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static const Vec< D, T > operator- (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static const Vec< D, T > operator* (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static const Vec< D, T > operator/ (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static const T operator^ (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static const T dot (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<class T >
static const Vec< 3, T > operator% (const Vec< 3, T > &v1, const Vec< 3, T > &v2)
template<class T >
static const Vec< 3, T > cross (const Vec< 3, T > &v1, const Vec< 3, T > &v2)
template<size_t D, class T >
static bool operator== (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static bool operator!= (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static bool operator< (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static bool operator> (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static bool operator<= (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static bool operator>= (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static const Vec< D, T > & operator+ (const Vec< D, T > &v)
template<size_t D, class T >
static const Vec< D, T > operator- (const Vec< D, T > &v)
template<size_t D, class T >
static bool operator! (const Vec< D, T > &v)
template<size_t D, class T >
static inline ::std::ostream & operator<< (::std::ostream &os, const Vec< D, T > &v)
template<size_t D, class T >
static inline ::std::istream & operator>> (::std::istream &is, Vec< D, T > &v)
template<size_t D, class T >
static Vec< D, T > faceforward (const Vec< D, T > &N, const Vec< D, T > &I, const Vec< D, T > &Nref)
template<size_t D, class T >
static Vec< D, T > reflect (const Vec< D, T > &I, const Vec< D, T > &N)
template<size_t D, class T >
static Vec< D, T > refract (const Vec< D, T > &I, const Vec< D, T > &N, const T &eta)
template<size_t D, class T >
static const T len2 (const Vec< D, T > &v)
template<size_t D, class T >
static const Vec< D, T >::float_type len (const Vec< D, T > &v)
template<size_t D, class T >
static const T length2 (const Vec< D, T > &v)
template<size_t D, class T >
static const Vec< D, T >::float_type length (const Vec< D, T > &v)
template<size_t D, class T >
static const T dist2 (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static const Vec< D, T >::float_type dist (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static const T distance2 (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static const Vec< D, T >::float_type distance (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<size_t D, class T >
static void normalize (Vec< D, T > &v)
template<size_t D, class T >
static Vec< D, T > normalized (const Vec< D, T > &v)
template<class T >
static Vec< 3, T > trinorm (const Vec< 3, T > &v0, const Vec< 3, T > &v1, const Vec< 3, T > &v2)
template<size_t D, class T >
static const Vec< D, T >::float_type angle (const Vec< D, T > &v1, const Vec< D, T > &v2)
template<class T >
static XForm< T > operator+ (const XForm< T > &xf1, const XForm< T > &xf2)
template<class T >
static XForm< T > operator- (const XForm< T > &xf1, const XForm< T > &xf2)
template<class T >
static XForm< T > operator* (const XForm< T > &xf1, const XForm< T > &xf2)
template<class S , class T >
static const S operator* (const XForm< T > &xf, const S &v)
template<class T >
static bool operator== (const XForm< T > &xf1, const XForm< T > &xf2)
template<class T >
static bool operator!= (const XForm< T > &xf1, const XForm< T > &xf2)
template<class T >
static XForm< T > inv (const XForm< T > &xf)
template<class T >
static void invert (XForm< T > &xf)
template<class T >
static XForm< T > transp (const XForm< T > &xf)
template<class T >
static void transpose (XForm< T > &xf)
template<class T >
static XForm< T > rot_only (const XForm< T > &xf)
template<class T >
static XForm< T > trans_only (const XForm< T > &xf)
template<class T >
static XForm< T > norm_xf (const XForm< T > &xf)
template<class T , class S >
static void decompose_rot (const XForm< T > &xf, T &angle, S &axis)
template<class T >
static void orthogonalize (XForm< T > &xf)
template<class T , class S >
static XForm< T > mix (const XForm< T > &x, const XForm< T > &y, const S &a)
template<class T >
static inline ::std::ostream & operator<< (::std::ostream &os, const XForm< T > &m)
template<class T >
static inline ::std::istream & operator>> (::std::istream &is, XForm< T > &m)
static inline ::std::string xfname (const ::std::string &filename)
static bool connected (const TriMesh *mesh, int f1, int f2, bool conn_vert)
static void find_connected (const TriMesh *mesh, vector< int > &comps, vector< int > &compsizes, int f, int whichcomponent, bool conn_vert)
static void sort_comps (vector< int > &comps, vector< int > &compsizes)
void find_comps (TriMesh *mesh, vector< int > &comps, vector< int > &compsizes, bool conn_vert)
void select_comp (TriMesh *mesh, const vector< int > &comps, int whichcc)
void select_big_comps (TriMesh *mesh, const vector< int > &comps, const vector< int > &compsizes, int min_size, int total_largest)
void select_small_comps (TriMesh *mesh, const vector< int > &comps, const vector< int > &compsizes, int max_size, int total_smallest)
static float wt (const point &p1, const point &p2, float invsigma2)
static float wt (const TriMesh *themesh, int v1, int v2, float invsigma2)
template<class ACCUM , class T >
static void diffuse_vert_field (TriMesh *themesh, vector< unsigned > &flags, unsigned &flag_curr, const ACCUM &accum, int v, float invsigma2, T &flt)
static void jones_filter (TriMesh *themesh, vector< unsigned > &flags, unsigned &flag_curr, int v, float invsigma2_1, float invsigma2_2, vector< point > &oldverts)
template<class T >
void diffuse_vector (TriMesh *themesh, std::vector< T > &field, float sigma)
template void diffuse_vector< float > (TriMesh *, vector< float > &, float)
template void diffuse_vector< Vec< 2, float > > (TriMesh *, vector< Vec< 2, float > > &, float)
template void diffuse_vector< Vec< 3, float > > (TriMesh *, vector< Vec< 3, float > > &, float)
template void diffuse_vector< Vec< 4, float > > (TriMesh *, vector< Vec< 4, float > > &, float)
static float cosmaxangle (const point &v1, const point &v2, const point &v3)
static float flip_benefit (const point &v1, const point &v2, const point &v3, const point &v4)
static float flip_benefit (const TriMesh *mesh, int f, int e)
static int edge_flip (TriMesh *mesh, int f1, int e)
point point_center_of_mass (const vector< point > &pts)
void point_covariance (const vector< point > &pts, float(&C)[3][3])
static float max_x (const TriMesh *mesh, int i)
static GLint myGluProject (GLdouble objX, GLdouble objY, GLdouble objZ, const GLdouble *model, const GLdouble *proj, const GLint *view, GLdouble *winX, GLdouble *winY, GLdouble *winZ)
static GLint myGluUnProject (GLdouble winX, GLdouble winY, GLdouble winZ, const GLdouble *model, const GLdouble *proj, const GLint *view, GLdouble *objX, GLdouble *objY, GLdouble *objZ)
typedef void (APIENTRYP glGenBuffers_t)(GLsizei n
typedef GLuint (APIENTRYP glCreateShader_t)(GLenum type)
typedef GLint (APIENTRYP glGetUniformLocation_t)(GLuint program
static GLFuncPtr glGetProcAddress (const char *name)
std::vector< double > XYTDegreeFromXForm (const xform &xf)
void compute_overlaps (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, const xform &xf2, const KDtree *kd1, const KDtree *kd2, vector< float > &o1, vector< float > &o2, float maxdist, int verbose)
static void selectall_and_match (TriMesh *tgt, TriMesh *src, const xform &srcxf, const KDtree *tgtkd, float maxdist, float angle_thresh, vector< PtPair > &pairs)
static void align_symm (const vector< PtPair > &pairs, float scale, const point &centroid1, const point &centroid2, float median_dist, xform &alignxf)
static void align_pt2pl_trans (const vector< PtPair > &pairs, const point &centroid1, const point &centroid2, xform &alignxf)
static void align_scale (const vector< PtPair > &pairs, xform &alignxf, const point &centroid1, const point &centroid2, bool do_affine)
static float median (vector< float > vals)
static float ICP_iter (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, xform &xf2, const KDtree *kd1, const KDtree *kd2, const vector< float > &weights1, const vector< float > &weights2, vector< float > &sampcdf1, vector< float > &sampcdf2, int desired_pairs, float &cdfincr, bool update_cdfs, float &maxdist, float &angle_thresh, int verbose, ICP_xform_type xform_type)
static void make_uniform_cdfs (const vector< float > &weights1, vector< float > &sampcdf1, const vector< float > &weights2, vector< float > &sampcdf2)
float ICP (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, xform &xf2, const KDtree *kd1, const KDtree *kd2, vector< float > &weights1, vector< float > &weights2, float maxdist, int verbose, ICP_xform_type xform_type)
static float sqr (float x)
static float dist2 (const float *x, const float *y)
static float dist2ray2 (const float *x, const float *p, const float *d)
static void mkpoint (TriMesh *mesh, float x, float y, float z)
static void mkface (TriMesh *mesh, int v1, int v2, int v3)
static void mkquad (TriMesh *mesh, int ll, int lr, int ul, int ur)
TriMesh * make_surface_of_revolution (int tess_th, const vector< point > &curve_pts)
TriMesh * join (const vector< TriMesh *> &meshes, float tol)
static void find_overlap_onedir (TriMesh *mesh1, TriMesh *mesh2, const xform &xf1, const xform &xf2, const KDtree *kd2, float &overlap_area, float &nonoverlap_area, float &rmsdist)
void remove_vertices (TriMesh *mesh, const vector< bool > &toremove)
void remove_faces (TriMesh *mesh, const vector< bool > &toremove)
void remap_verts (TriMesh *mesh, const std::vector< int > &remap_table)
static point loop (TriMesh *mesh, int, int, int v0, int v1, int v2, int v3)
static point opposite (TriMesh *mesh, int f, int v)
static point butterfly (TriMesh *mesh, int f1, int f2, int v0, int v1, int v2, int v3)
static point new_loop_edge (TriMesh *mesh, int f1, int f2, int v0, int v1, int v2, int v3)
static point zorin_edge (TriMesh *mesh, int f1, int f2, int v0, int v1, int v2, int v3)
static point avg_bdy (TriMesh *mesh, int v)
static float loop_update_alpha (SubdivScheme scheme, int n)
static void insert_vert (TriMesh *mesh, SubdivScheme scheme, int f, int e)
static void rot_coord_sys (const vec &old_u, const vec &old_v, const vec &new_norm, vec &new_u, vec &new_v)
static void mkface (TriMesh *mesh, int v1, int v2, int v3)
static bool read_ply (FILE *f, TriMesh *mesh)
static bool read_3ds (FILE *f, TriMesh *mesh)
static bool read_vvd (FILE *f, TriMesh *mesh)
static bool read_ray (FILE *f, TriMesh *mesh)
static bool read_obj (FILE *f, TriMesh *mesh)
static bool read_off (FILE *f, TriMesh *mesh)
static bool read_sm (FILE *f, TriMesh *mesh)
static bool read_stl (FILE *f, TriMesh *mesh)
static bool read_pts (FILE *f, TriMesh *mesh)
static bool read_verts_bin (FILE *f, TriMesh *mesh, bool &need_swap, int nverts, int vert_len, int vert_pos, int vert_norm, int vert_color, bool float_color, int vert_conf)
static bool slurp_verts_bin (FILE *f, TriMesh *mesh, bool need_swap, int nverts)
static bool read_verts_asc (FILE *f, TriMesh *mesh, int nverts, int vert_len, int vert_pos, int vert_norm, int vert_color, bool float_color, int vert_conf)
static bool read_faces_bin (FILE *f, TriMesh *mesh, bool need_swap, int nfaces, int face_len, int face_count, int face_idx)
static bool read_faces_asc (FILE *f, TriMesh *mesh, int nfaces, int face_len, int face_count, int face_idx, bool read_to_eol=false)
static bool read_strips_bin (FILE *f, TriMesh *mesh, bool need_swap)
static bool read_strips_asc (FILE *f, TriMesh *mesh)
static bool read_grid_bin (FILE *f, TriMesh *mesh, bool need_swap)
static bool read_grid_asc (FILE *f, TriMesh *mesh)
static int ply_type_len (const char *buf, bool binary)
static bool ply_property (const char *buf, int &len, bool binary)
static void check_need_swap (const point &p, bool &need_swap)
static void check_ind_range (TriMesh *mesh)
static void skip_comments (FILE *f)
static void tess (const vector< point > &verts, const vector< int > &thisface, vector< TriMesh::Face > &tris)
static bool write_ply_ascii (TriMesh *mesh, FILE *f, bool write_norm, bool write_grid, bool float_color)
static bool write_ply_binary (TriMesh *mesh, FILE *f, bool little_endian, bool write_norm, bool write_grid, bool float_color)
static bool write_ray (TriMesh *mesh, FILE *f)
static bool write_obj (TriMesh *mesh, FILE *f, bool write_norm)
static bool write_off (TriMesh *mesh, FILE *f)
static bool write_sm (TriMesh *mesh, FILE *f)
static bool write_stl (TriMesh *mesh, FILE *f)
static bool write_pts (TriMesh *mesh, FILE *f)
static bool write_cc (TriMesh *mesh, FILE *f, const char *filename, bool write_norm, bool float_color)
static bool write_dae (TriMesh *mesh, FILE *f)
static bool write_verts_asc (TriMesh *mesh, FILE *f, const char *before_vert, const char *before_norm, const char *before_color, bool float_color, const char *before_conf, const char *after_line)
static bool write_verts_bin (TriMesh *mesh, FILE *f, bool need_swap, bool write_norm, bool write_color, bool float_color, bool write_conf)
static bool write_faces_asc (TriMesh *mesh, FILE *f, const char *before_face, const char *after_line)
static bool write_faces_bin (TriMesh *mesh, FILE *f, bool need_swap, int before_face_len, const char *before_face, int after_face_len, const char *after_face)
static bool write_strips_asc (TriMesh *mesh, FILE *f)
static bool write_strips_bin (TriMesh *mesh, FILE *f, bool need_swap)
static bool write_grid_asc (TriMesh *mesh, FILE *f)
static bool write_grid_bin (TriMesh *mesh, FILE *f, bool need_swap)
static void pushback (const char *buf, FILE *f)
static bool write_ply_header (TriMesh *mesh, FILE *f, const char *format, bool write_grid, bool write_tstrips, bool write_norm, bool float_color)
static unsigned char color2uchar (float p)
static void swap_vert_props (TriMesh *mesh, bool swap_color)
static bool write_verts_bin_helper (TriMesh *mesh, FILE *f, bool write_norm, bool write_color, bool float_color, bool write_conf)
static void normals_from_tstrips_Max (vector< int > &tstrips, vector< point > &vertices, vector< vec > &normals)
static void normals_from_tstrips_area (vector< int > &tstrips, vector< point > &vertices, vector< vec > &normals)
static void normals_from_faces_Max (vector< TriMesh::Face > &faces, vector< point > &vertices, vector< vec > &normals)
static void normals_from_faces_area (vector< TriMesh::Face > &faces, vector< point > &vertices, vector< vec > &normals)
static void normals_from_points (vector< point > &vertices, vector< vec > &normals)
static void tstrip_build (TriMesh &mesh, int f, vector< signed char > &face_avail, vector< int > &todo)
Variables
static glGenBuffers_t glGenBuffers
static glBufferData_t glBufferData
static glBindBuffer_t glBindBuffer
static glDeleteBuffers_t glDeleteBuffers
static glCreateShader_t glCreateShader
static glShaderSource_t glShaderSource
static glCompileShader_t glCompileShader
static glDeleteShader_t glDeleteShader
static glGetShaderiv_t glGetShaderiv
static glGetShaderInfoLog_t glGetShaderInfoLog
static glCreateProgram_t glCreateProgram
static glAttachShader_t glAttachShader
static glLinkProgram_t glLinkProgram
static glValidateProgram_t glValidateProgram
static glUseProgram_t glUseProgram
static glDeleteProgram_t glDeleteProgram
static glGetProgramiv_t glGetProgramiv
static glGetProgramInfoLog_t glGetProgramInfoLog
static glUniform1f_t glUniform1f
static glUniform2f_t glUniform2f
static glUniform3f_t glUniform3f
static glUniform4f_t glUniform4f
static glUniform1i_t glUniform1i
static glUniform2i_t glUniform2i
static glUniform3i_t glUniform3i
static glUniform4i_t glUniform4i
static glUniformMatrix2fv_t glUniformMatrix2fv
static glUniformMatrix3fv_t glUniformMatrix3fv
static glUniformMatrix4fv_t glUniformMatrix4fv
static glGetActiveUniform_t glGetActiveUniform
static glGetUniformLocation_t glGetUniformLocation
static glVertexAttrib1f_t glVertexAttrib1f
static glVertexAttrib2f_t glVertexAttrib2f
static glVertexAttrib3f_t glVertexAttrib3f
static glVertexAttrib4f_t glVertexAttrib4f
static glVertexAttribPointer_t glVertexAttribPointer
static glEnableVertexAttribArray_t glEnableVertexAttribArray
static glDisableVertexAttribArray_t glDisableVertexAttribArray
static glGetActiveAttrib_t glGetActiveAttrib
static glGetAttribLocation_t glGetAttribLocation
static glGenVertexArrays_t glGenVertexArrays
static glBindVertexArray_t glBindVertexArray
static glDeleteVertexArrays_t glDeleteVertexArrays
static glGenFramebuffers_t glGenFramebuffers
static glFramebufferTexture2D_t glFramebufferTexture2D
static glBindFramebuffer_t glBindFramebuffer
static glDeleteFramebuffers_t glDeleteFramebuffers
static glClampColor_t glClampColor
static glClampColorARB_t glClampColorARB
static glPrimitiveRestartIndex_t glPrimitiveRestartIndex
static glPrimitiveRestartIndexNV_t glPrimitiveRestartIndexNV
static const float sqrt2 = 1.41421356f
static const float sqrt6 = 2.44948974f
static const float sqrt8 = 2.82842712f
static const float phi = 1.61803399f
static const float phibar = 0.61803399f
static const float tetrahedron_verts []
static const int tetrahedron_faces []
static const float cube_verts []
static const int cube_faces []
static const float octahedron_verts []
static const int octahedron_faces []
static const float dodecahedron_verts []
static const int dodecahedron_faces []
static const float icosahedron_verts []
static const int icosahedron_faces []
static const float truncated_tetrahedron_verts []
static const int truncated_tetrahedron_faces []
static const float cuboctahedron_verts []
static const int cuboctahedron_faces []
static const float truncated_cube_verts []
static const int truncated_cube_faces []
static const float truncated_octahedron_verts []
static const int truncated_octahedron_faces []
static const float rhombicuboctahedron_verts []
static const int rhombicuboctahedron_faces []
static const float truncated_cuboctahedron_verts []
static const int truncated_cuboctahedron_faces []
static const float icosidodecahedron_verts []
static const int icosidodecahedron_faces []
static const float truncated_dodecahedron_verts []
static const int truncated_dodecahedron_faces []
static const float truncated_icosahedron_verts []
static const int truncated_icosahedron_faces []
static const float snub_cube_verts []
static const int snub_cube_faces []
static const float rhombicosidodecahedron_verts []
static const int rhombicosidodecahedron_faces []
static const float truncated_icosidodecahedron_verts []
static const int truncated_icosidodecahedron_faces []
static const float snub_dodecahedron_verts []
static const int snub_dodecahedron_faces []
static const float triakis_tetrahedron_verts []
static const int triakis_tetrahedron_faces []
static const float rhombic_dodecahedron_verts []
static const int rhombic_dodecahedron_faces []
static const float triakis_octahedron_verts []
static const int triakis_octahedron_faces []
static const float tetrakis_hexahedron_verts []
static const int tetrakis_hexahedron_faces []
static const float deltoidal_icositetrahedron_verts []
static const int deltoidal_icositetrahedron_faces []
static const float disdyakis_dodecahedron_verts []
static const int disdyakis_dodecahedron_faces []
static const float rhombic_triacontahedron_verts []
static const int rhombic_triacontahedron_faces []
static const float triakis_icosahedron_verts []
static const int triakis_icosahedron_faces []
static const float pentakis_dodecahedron_verts []
static const int pentakis_dodecahedron_faces []
static const float pentagonal_icositetrahedron_verts []
static const int pentagonal_icositetrahedron_faces []
static const float deltoidal_hexecontahedron_verts []
static const int deltoidal_hexecontahedron_faces []
static const float disdyakis_triacontahedron_verts []
static const int disdyakis_triacontahedron_faces []
static const float pentagonal_hexecontahedron_verts []
static const int pentagonal_hexecontahedron_faces []
static const float teapot_verts []
static const int teapot_patches []
Typedef Documentation
arrays
typedef const GLuint * trimesh::arrays
attachment
typedef GLenum trimesh::attachment
box
typedef Box<3,float> trimesh::box
box2
typedef Box<2,float> trimesh::box2
box3
typedef Box<3,float> trimesh::box3
box4
typedef Box<4,float> trimesh::box4
buffer
typedef GLuint trimesh::buffer
buffers
typedef const GLuint * trimesh::buffers
bufSize
typedef GLuint GLsizei trimesh::bufSize
clamp
typedef GLenum trimesh::clamp
count
typedef GLsizei trimesh::count
data
typedef GLsizeiptr const void* trimesh::data
dbox2
typedef Box<2,double> trimesh::dbox2
dbox3
typedef Box<3,double> trimesh::dbox3
dbox4
typedef Box<4,double> trimesh::dbox4
dvec2
typedef Vec<2,double> trimesh::dvec2
dvec3
typedef Vec<3,double> trimesh::dvec3
dvec4
typedef Vec<4,double> trimesh::dvec4
dxform
typedef XForm<double> trimesh::dxform
framebuffer
typedef GLuint trimesh::framebuffer
framebuffers
typedef const GLuint * trimesh::framebuffers
fxform
typedef XForm<float> trimesh::fxform
GLchar
typedef char trimesh::GLchar
GLintptr
typedef ptrdiff_t trimesh::GLintptr
GLsizeiptr
typedef ptrdiff_t trimesh::GLsizeiptr
ibox2
typedef Box<2,int> trimesh::ibox2
ibox3
typedef Box<3,int> trimesh::ibox3
ibox4
typedef Box<4,int> trimesh::ibox4
index
typedef GLuint trimesh::index
infoLog
typedef GLsizei GLsizei GLchar * trimesh::infoLog
ivec2
typedef Vec<2,int> trimesh::ivec2
ivec3
typedef Vec<3,int> trimesh::ivec3
ivec4
typedef Vec<4,int> trimesh::ivec4
length
typedef GLuint GLsizei GLsizei * trimesh::length
level
typedef GLenum GLenum GLuint GLint trimesh::level
name
typedef const GLchar * trimesh::name
normalized
typedef GLint GLenum GLboolean trimesh::normalized
params
typedef GLenum GLint * trimesh::params
pname
typedef GLenum trimesh::pname
point
typedef Vec<3,float> trimesh::point
point2
typedef Vec<2,float> trimesh::point2
point3
typedef Vec<3,float> trimesh::point3
point4
typedef Vec<4,float> trimesh::point4
pointer
typedef GLint GLenum GLboolean GLsizei const void* trimesh::pointer
pt_with_d
typedef pair<float, const float *> trimesh::pt_with_d
shader
typedef GLuint trimesh::shader
size
typedef GLuint GLsizei GLsizei GLint * trimesh::size
stride
typedef GLint GLenum GLboolean GLsizei trimesh::stride
string
typedef GLsizei const GLchar* const* trimesh::string
textarget
typedef GLenum GLenum trimesh::textarget
texture
typedef GLenum GLenum GLuint trimesh::texture
timestamp
typedef struct timeval trimesh::timestamp
transpose
typedef GLsizei GLboolean trimesh::transpose
type
typedef GLuint GLsizei GLsizei GLint GLenum * trimesh::type
usage
typedef GLsizeiptr const void GLenum trimesh::usage
v0
typedef GLint trimesh::v0
v1
typedef GLint GLint trimesh::v1
v2
typedef GLint GLint GLint trimesh::v2
v3
typedef GLint GLint GLint GLint trimesh::v3
value
typedef GLsizei GLboolean const GLfloat * trimesh::value
vec
typedef Vec<3,float> trimesh::vec
vec2
typedef Vec<2,float> trimesh::vec2
vec3
typedef Vec<3,float> trimesh::vec3
vec4
typedef Vec<4,float> trimesh::vec4
w
typedef GLfloat GLfloat GLfloat GLfloat trimesh::w
x
typedef GLfloat trimesh::x
xform
typedef XForm<double> trimesh::xform
y
typedef GLfloat GLfloat trimesh::y
z
typedef GLfloat GLfloat GLfloat trimesh::z
Enumeration Type Documentation
FixedShape
enum trimesh::FixedShape
Enumerator
SHAPE_TETRAHEDRON
SHAPE_CUBE
SHAPE_OCTAHEDRON
SHAPE_DODECAHEDRON
SHAPE_ICOSAHEDRON
SHAPE_TRUNCATED_TETRAHEDRON
SHAPE_CUBOCTAHEDRON
SHAPE_TRUNCATED_CUBE
SHAPE_TRUNCATED_OCTAHEDRON
SHAPE_RHOMBICUBOCTAHEDRON
SHAPE_TRUNCATED_CUBOCTAHEDRON
SHAPE_ICOSIDODECAHEDRON
SHAPE_TRUNCATED_DODECAHEDRON
SHAPE_TRUNCATED_ICOSAHEDRON
SHAPE_SNUB_CUBE
SHAPE_RHOMBICOSIDODECAHEDRON
SHAPE_TRUNCATED_ICOSIDODECAHEDRON
SHAPE_SNUB_DODECAHEDRON
SHAPE_TRIAKIS_TETRAHEDRON
SHAPE_RHOMBIC_DODECAHEDRON
SHAPE_TRIAKIS_OCTAHEDRON
SHAPE_TETRAKIS_HEXAHEDRON
SHAPE_DELTOIDAL_ICOSITETRAHEDRON
SHAPE_DISDYAKIS_DODECAHEDRON
SHAPE_RHOMBIC_TRIACONTAHEDRON
SHAPE_TRIAKIS_ICOSAHEDRON
SHAPE_PENTAKIS_DODECAHEDRON
SHAPE_PENTAGONAL_ICOSITETRAHEDRON
SHAPE_DELTOIDAL_HEXECONTAHEDRON
SHAPE_DISDYAKIS_TRIACONTAHEDRON
SHAPE_PENTAGONAL_HEXECONTAHEDRON
ICP_xform_type
enum trimesh::ICP_xform_type
Enumerator
ICP_TRANSLATION
ICP_RIGID
ICP_SIMILARITY
ICP_AFFINE
SubdivScheme
enum trimesh::SubdivScheme
Enumerator
SUBDIV_PLANAR
SUBDIV_LOOP
SUBDIV_LOOP_ORIG
SUBDIV_LOOP_NEW
SUBDIV_BUTTERFLY
SUBDIV_BUTTERFLY_MODIFIED
Function Documentation
align_pt2pl_trans()
static void trimesh::align_pt2pl_trans (const vector< PtPair > & pairs, const point & centroid1, const point & centroid2, xform & alignxf) static
Referenced by ICP_iter().
align_scale()
static void trimesh::align_scale (const vector< PtPair > & pairs, xform & alignxf, const point & centroid1, const point & centroid2, bool do_affine) static
Referenced by ICP_iter().
align_symm()
static void trimesh::align_symm (const vector< PtPair > & pairs, float scale, const point & centroid1, const point & centroid2, float median_dist, xform & alignxf) static
Referenced by ICP_iter().
angle()
template<size_t D, class T > static const Vec<D,T>::float_type trimesh::angle (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
Referenced by common::Affine3dFromAffine2d(), trimesh::TriMesh::dihedral(), common::RandomTransformGenerator2D::Generate(), make_helix(), MarkerArrayOfSensor(), mix(), orthogonalize(), and common::XYTRadianFromMatrix3d().
apply_xform()
void trimesh::apply_xform (TriMesh * mesh, const xform & xf)
Referenced by pca_rotate(), pca_snap(), rot(), scale(), and trans().
avg_bdy()
static point trimesh::avg_bdy (TriMesh * mesh, int v) static
Referenced by insert_vert().
bboxname()
static inline ::std::string trimesh::bboxname (const ::std::string & filename) static
begins_with() [1/2]
static bool trimesh::begins_with (const char * s1, const char * s2) inline static
Referenced by begins_with(), ply_type_len(), trimesh::TriMesh::read_helper(), and trimesh::TriMesh::write().
begins_with() [2/2]
static bool trimesh::begins_with (const ::std::string & s1, const ::std::string & s2) inline static
bilateral_smooth_mesh()
void trimesh::bilateral_smooth_mesh (TriMesh * themesh, float sigma1, float sigma2)
butterfly()
static point trimesh::butterfly (TriMesh * mesh, int f1, int f2, int v0, int v1, int v2, int v3) static
Referenced by insert_vert(), and zorin_edge().
check_ind_range()
static void trimesh::check_ind_range (TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
check_need_swap()
static void trimesh::check_need_swap (const point & p, bool & need_swap) static
Referenced by read_verts_bin().
clamp()
template<class T , class A , class B > static T trimesh::clamp (const T & x, const A & a, const B & b) inline static
clear_and_release()
template<class T > static void trimesh::clear_and_release (::std::vector< T > & v) inline static
Referenced by trimesh::TriMesh::clear_across_edge(), trimesh::TriMesh::clear_adjacentfaces(), trimesh::TriMesh::clear_colors(), trimesh::TriMesh::clear_confidences(), trimesh::TriMesh::clear_curvatures(), trimesh::TriMesh::clear_dcurv(), trimesh::TriMesh::clear_faces(), trimesh::TriMesh::clear_flags(), trimesh::TriMesh::clear_grid(), trimesh::TriMesh::clear_neighbors(), trimesh::TriMesh::clear_normals(), trimesh::TriMesh::clear_pointareas(), trimesh::TriMesh::clear_tstrips(), and trimesh::TriMesh::clear_vertices().
clip()
void trimesh::clip (TriMesh * mesh, const box & b)
color2uchar()
static unsigned char trimesh::color2uchar (float p) static
Referenced by write_cc(), write_verts_asc(), and write_verts_bin_helper().
compute_overlaps() [1/2]
void trimesh::compute_overlaps (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, const xform & xf2, const KDtree * kd1, const KDtree * kd2, const Grid * g1, const Grid * g2, ::std::vector< float > & o1, ::std::vector< float > & o2, float & maxdist, int verbose)
compute_overlaps() [2/2]
void trimesh::compute_overlaps (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, const xform & xf2, const KDtree * kd1, const KDtree * kd2, vector< float > & o1, vector< float > & o2, float maxdist, int verbose)
Referenced by ICP().
connected()
static bool trimesh::connected (const TriMesh * mesh, int f1, int f2, bool conn_vert) static
Referenced by find_connected().
contains() [1/2]
static bool trimesh::contains (const char * s1, const char * s2) inline static
Referenced by contains().
contains() [2/2]
static bool trimesh::contains (const ::std::string & s1, const ::std::string & s2) inline static
cosmaxangle()
static float trimesh::cosmaxangle (const point & v1, const point & v2, const point & v3) static
Referenced by flip_benefit().
cross()
template<class T > static const Vec<3,T> trimesh::cross (const Vec< 3, T > & v1, const Vec< 3, T > & v2) inline static
cube()
template<class T > static T trimesh::cube (const T & x) inline static
Referenced by trimesh::Color::col_transform(), std::get(), and make_fixed_shape().
decompose_rot()
template<class T , class S > static void trimesh::decompose_rot (const XForm< T > & xf, T & angle, S & axis) inline static
Referenced by mix(), and orthogonalize().
degrees() [1/3]
template<class T > static double trimesh::degrees (const T & x) inline static
Referenced by std::get(), and ICP_iter().
degrees() [2/3]
static float trimesh::degrees (const float & x) inline static
degrees() [3/3]
static long double trimesh::degrees (const long double & x) inline static
diagonalize_curv()
void trimesh::diagonalize_curv (const vec & old_u, const vec & old_v, float ku, float kuv, float kv, const vec & new_norm, vec & pdir1, vec & pdir2, float & k1, float & k2)
Referenced by diffuse_curv(), and trimesh::TriMesh::need_curvatures().
diffuse_curv()
void trimesh::diffuse_curv (TriMesh * themesh, float sigma)
diffuse_dcurv()
void trimesh::diffuse_dcurv (TriMesh * themesh, float sigma)
diffuse_normals()
void trimesh::diffuse_normals (TriMesh * themesh, float sigma)
Referenced by bilateral_smooth_mesh(), and smooth_mesh().
diffuse_vector() [1/2]
template<class T > void trimesh::diffuse_vector (TriMesh * themesh, ::std::vector< T > & field, float sigma)
diffuse_vector() [2/2]
template<class T > void trimesh::diffuse_vector (TriMesh * themesh, std::vector< T > & field, float sigma)
diffuse_vector< float >()
template void trimesh::diffuse_vector< float > (TriMesh * , vector< float > & , float)
Referenced by diffuse_dcurv().
diffuse_vector< Vec< 2, float > >()
template void trimesh::diffuse_vector< Vec< 2, float > > (TriMesh * , vector< Vec< 2, float > > & , float)
diffuse_vector< Vec< 3, float > >()
template void trimesh::diffuse_vector< Vec< 3, float > > (TriMesh * , vector< Vec< 3, float > > & , float)
diffuse_vector< Vec< 4, float > >()
template void trimesh::diffuse_vector< Vec< 4, float > > (TriMesh * , vector< Vec< 4, float > > & , float)
diffuse_vert_field()
template<class ACCUM , class T > static void trimesh::diffuse_vert_field (TriMesh * themesh, vector< unsigned > & flags, unsigned & flag_curr, const ACCUM & accum, int v, float invsigma2, T & flt) static
Referenced by diffuse_curv(), diffuse_dcurv(), diffuse_normals(), diffuse_vector(), and smooth_mesh().
dist()
template<size_t D, class T > static const Vec<D,T>::float_type trimesh::dist (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
Referenced by cosmaxangle(), distance(), ICP(), trimesh::TriMesh::need_bsphere(), trimesh::Box< 3, float >::radius(), and trimesh::TriMesh::stat().
dist2() [1/2]
static float trimesh::dist2 (const float * x, const float * y) inline static
Referenced by trimesh::KDtree::Node::exists_pt(), trimesh::KDtree::Node::find_closest_compat_to_pt(), trimesh::KDtree::Node::find_closest_to_pt(), trimesh::KDtree::Node::find_k_closest_compat_to_pt(), and trimesh::KDtree::Node::find_k_closest_to_pt().
dist2() [2/2]
template<size_t D, class T > static const T trimesh::dist2 (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
Referenced by NDTMatcher::CeresMatch(), dist(), distance2(), trimesh::TriMesh::feature_size(), ICP_iter(), main(), trimesh::TriMesh::need_bsphere(), remove_sliver_faces(), tess(), trimesh::TriMesh::triangulate_grid(), and wt().
dist2ray2()
static float trimesh::dist2ray2 (const float * x, const float * p, const float * d) inline static
Referenced by trimesh::KDtree::Node::find_closest_compat_to_ray(), and trimesh::KDtree::Node::find_closest_to_ray().
distance()
template<size_t D, class T > static const Vec<D,T>::float_type trimesh::distance (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
distance2()
template<size_t D, class T > static const T trimesh::distance2 (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
dot()
template<size_t D, class T > static const T trimesh::dot (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
Referenced by ICP_iter(), main(), and replace_ext().
edge_flip()
static int trimesh::edge_flip (TriMesh * mesh, int f1, int e) static
Referenced by edgeflip().
edgeflip()
void trimesh::edgeflip (TriMesh * mesh)
eigdc()
template<class T , int N> static void trimesh::eigdc (T(&) A[N][N], T d[N]) inline static
eigmult() [1/2]
template<class T , int N> static void trimesh::eigmult (const T(&) A[N][N], const T d[N], const T b[N], T x[N]) inline static
eigmult() [2/2]
template<class T , int N> static void trimesh::eigmult (const T(&) A[N][N], const T d[N], T b[N]) inline static
ends_with() [1/2]
static bool trimesh::ends_with (const char * s1, const char * s2) inline static
Referenced by ends_with(), trimesh::TriMesh::read_helper(), and trimesh::TriMesh::write().
ends_with() [2/2]
static bool trimesh::ends_with (const ::std::string & s1, const ::std::string & s2) inline static
erode()
void trimesh::erode (TriMesh * mesh)
faceflip()
void trimesh::faceflip (TriMesh * mesh)
faceforward()
template<size_t D, class T > static Vec<D,T> trimesh::faceforward (const Vec< D, T > & N, const Vec< D, T > & I, const Vec< D, T > & Nref) inline static
find_comps() [1/2]
void trimesh::find_comps (TriMesh * mesh, vector< int > & comps, vector< int > & compsizes, bool conn_vert)
find_comps() [2/2]
void trimesh::find_comps (TriMesh * mesh, ::std::vector< int > & comps, ::std::vector< int > & compsizes, bool conn_vert = false)
Referenced by shared().
find_connected()
static void trimesh::find_connected (const TriMesh * mesh, vector< int > & comps, vector< int > & compsizes, int f, int whichcomponent, bool conn_vert) static
Referenced by find_comps().
find_overlap() [1/3]
void trimesh::find_overlap (TriMesh * mesh1, TriMesh * mesh2, float & area, float & rmsdist)
Referenced by find_overlap().
find_overlap() [2/3]
void trimesh::find_overlap (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, const xform & xf2, float & area, float & rmsdist)
find_overlap() [3/3]
void trimesh::find_overlap (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, const xform & xf2, const KDtree * kd1, const KDtree * kd2, float & area, float & rmsdist)
find_overlap_onedir()
static void trimesh::find_overlap_onedir (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, const xform & xf2, const KDtree * kd2, float & overlap_area, float & nonoverlap_area, float & rmsdist) static
Referenced by find_overlap(), and iou().
flip_benefit() [1/2]
static float trimesh::flip_benefit (const point & v1, const point & v2, const point & v3, const point & v4) static
flip_benefit() [2/2]
static float trimesh::flip_benefit (const TriMesh * mesh, int f, int e) static
Referenced by edgeflip().
fract()
template<class T > static T trimesh::fract (const T & x) inline static
Referenced by std::get().
glGetProcAddress()
static GLFuncPtr trimesh::glGetProcAddress (const char * name) static
GLint()
typedef trimesh::GLint (APIENTRYP glGetUniformLocation_t)
Referenced by trimesh::GLManager::draw_points(), trimesh::GLManager::make_shader(), trimesh::GLCamera::mouse(), myGluUnProject(), trimesh::GLManager::rendertarget(), trimesh::GLCamera::setupGL(), trimesh::GLManager::shader_ready(), trimesh::GLManager::slow_tstrips(), and trimesh::GLManager::use_texture().
GLuint()
typedef trimesh::GLuint (APIENTRYP glCreateShader_t)
ICP() [1/7]
float trimesh::ICP (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, xform & xf2, const KDtree * kd1, const KDtree * kd2, ::std::vector< float > & weights1, ::std::vector< float > & weights2, float maxdist = 0.0f, int verbose = 0, ICP_xform_type xform_type = ICP_RIGID)
Referenced by DoSICP(), and main().
ICP() [2/7]
float trimesh::ICP (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, xform & xf2, const KDtree * kd1, const KDtree * kd2, int verbose = 0, ICP_xform_type xform_type = ICP_RIGID)
ICP() [3/7]
float trimesh::ICP (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, xform & xf2, int verbose = 0, ICP_xform_type xform_type = ICP_RIGID)
ICP() [4/7]
float trimesh::ICP (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, xform & xf2, const KDtree * kd1, const KDtree * kd2, ::std::vector< float > & weights1, ::std::vector< float > & weights2, float maxdist, int verbose, bool do_scale, bool do_affine = false)
ICP() [5/7]
float trimesh::ICP (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, xform & xf2, const KDtree * kd1, const KDtree * kd2, int verbose, bool do_scale, bool do_affine = false)
ICP() [6/7]
float trimesh::ICP (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, xform & xf2, int verbose, bool do_scale, bool do_affine = false)
ICP() [7/7]
float trimesh::ICP (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, xform & xf2, const KDtree * kd1, const KDtree * kd2, vector< float > & weights1, vector< float > & weights2, float maxdist, int verbose, ICP_xform_type xform_type)
Referenced by ICP().
ICP_iter()
static float trimesh::ICP_iter (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, xform & xf2, const KDtree * kd1, const KDtree * kd2, const vector< float > & weights1, const vector< float > & weights2, vector< float > & sampcdf1, vector< float > & sampcdf2, int desired_pairs, float & cdfincr, bool update_cdfs, float & maxdist, float & angle_thresh, int verbose, ICP_xform_type xform_type) static
Referenced by ICP().
inflate()
void trimesh::inflate (TriMesh * mesh, float amount)
insert_vert()
static void trimesh::insert_vert (TriMesh * mesh, SubdivScheme scheme, int f, int e) static
Referenced by subdiv().
inv()
template<class T > static XForm<T> trimesh::inv (const XForm< T > & xf) inline static
Referenced by compute_overlaps(), find_overlap_onedir(), invert(), mix(), myGluUnProject(), and norm_xf().
invert()
template<class T > static void trimesh::invert (XForm< T > & xf) inline static
Referenced by pca_rotate(), and pca_snap().
iou() [1/3]
float trimesh::iou (TriMesh * mesh1, TriMesh * mesh2)
Referenced by iou().
iou() [2/3]
float trimesh::iou (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, const xform & xf2)
iou() [3/3]
float trimesh::iou (TriMesh * mesh1, TriMesh * mesh2, const xform & xf1, const xform & xf2, const KDtree * kd1, const KDtree * kd2)
join() [1/2]
TriMesh* trimesh::join (const vector< TriMesh *> & meshes, float tol)
join() [2/2]
TriMesh* trimesh::join (const ::std::vector< TriMesh *> & meshes, float tol = -1.0f)
jones_filter()
static void trimesh::jones_filter (TriMesh * themesh, vector< unsigned > & flags, unsigned & flag_curr, int v, float invsigma2_1, float invsigma2_2, vector< point > & oldverts) static
Referenced by bilateral_smooth_mesh().
ldltdc()
template<class T , int N> static bool trimesh::ldltdc (T(&) A[N][N], T rdiag[N]) inline static
ldltsl() [1/2]
template<class T , int N> static void trimesh::ldltsl (const T(&) A[N][N], const T rdiag[N], const T b[N], T x[N]) inline static
Referenced by ldltsl().
ldltsl() [2/2]
template<class T , int N> static void trimesh::ldltsl (const T(&) A[N][N], const T rdiag[N], T b[N]) inline static
len()
template<size_t D, class T > static const Vec<D,T>::float_type trimesh::len (const Vec< D, T > & v) inline static
Referenced by align_symm(), angle(), trimesh::TriMesh::convert_strips(), length(), trimesh::GLManager::make_shader(), mesh_center_of_mass(), mesh_covariance(), myGluUnProject(), trimesh::TriMesh::need_pointareas(), noisify(), normalize(), trimesh::GLManager::shader_ready(), trimesh::TriMesh::stat(), and trimesh::TriMesh::unpack_tstrips().
len2()
template<size_t D, class T > static const T trimesh::len2 (const Vec< D, T > & v) inline static
Referenced by contains(), len(), length2(), trimesh::TriMesh::need_pointareas(), normals_from_faces_Max(), normals_from_tstrips_Max(), and smooth_mesh().
length()
template<size_t D, class T > static const Vec<D,T>::float_type trimesh::length (const Vec< D, T > & v) inline static
length2()
template<size_t D, class T > static const T trimesh::length2 (const Vec< D, T > & v) inline static
lmsmooth()
void trimesh::lmsmooth (TriMesh * mesh, int niters)
loop()
static point trimesh::loop (TriMesh * mesh, int , int , int v0, int v1, int v2, int v3) static
Referenced by insert_vert(), and new_loop_edge().
loop_update_alpha()
static float trimesh::loop_update_alpha (SubdivScheme scheme, int n) inline static
Referenced by subdiv().
lubksb() [1/2]
template<class T , int N> static void trimesh::lubksb (const T(&) A[N][N], const int ind[N], T b[N]) inline static
Referenced by lubksb().
lubksb() [2/2]
template<class T , int N> static void trimesh::lubksb (const T(&) A[N][N], const int ind[N], const T b[N], T x[N]) inline static
ludcmp()
template<class T , int N> static bool trimesh::ludcmp (T(&) A[N][N], int ind[N]) inline static
make_bump()
TriMesh * trimesh::make_bump (int tess, float sigma = 1.0f)
make_ccone()
TriMesh * trimesh::make_ccone (int tess_th, int tess_r, float r = 1.0f)
make_ccyl()
TriMesh * trimesh::make_ccyl (int tess_th, int tess_h, float r = 1.0f)
Referenced by make_scyl().
make_cone()
TriMesh * trimesh::make_cone (int tess_th, int tess_r, float r = 1.0f)
make_cube()
TriMesh * trimesh::make_cube (int tess)
make_cyl()
TriMesh * trimesh::make_cyl (int tess_th, int tess_h, float r = 1.0f)
Referenced by make_helix(), make_surface_of_revolution(), and make_torus().
make_disc()
TriMesh * trimesh::make_disc (int tess_th, int tess_r)
Referenced by make_cone().
make_fixed_shape()
TriMesh * trimesh::make_fixed_shape (FixedShape shape)
Referenced by make_platonic().
make_frac()
TriMesh * trimesh::make_frac (int tess)
make_grid()
Grid* trimesh::make_grid (TriMesh * mesh)
make_helix()
TriMesh * trimesh::make_helix (int tess_th, int tess_ph, float turns, float r = 0.2f)
make_klein()
TriMesh * trimesh::make_klein (int tess_th, int tess_ph)
make_knot()
TriMesh * trimesh::make_knot (int tess_th, int tess_ph, float r = 0.2f)
make_plane()
TriMesh * trimesh::make_plane (int tess_x, int tess_y = -1)
Referenced by make_wave().
make_platonic()
TriMesh * trimesh::make_platonic (int nfaces)
make_scyl()
TriMesh * trimesh::make_scyl (int tess_th, int tess_h, float r = 1.0f)
make_sphere_polar()
TriMesh * trimesh::make_sphere_polar (int tess_ph, int tess_th)
make_sphere_subdiv()
TriMesh * trimesh::make_sphere_subdiv (int nfaces, int nsubdiv)
make_surface_of_revolution() [1/2]
TriMesh* trimesh::make_surface_of_revolution (int tess_th, const ::std::vector< point > & curve_pts)
make_surface_of_revolution() [2/2]
TriMesh* trimesh::make_surface_of_revolution (int tess_th, const vector< point > & curve_pts)
make_teapot()
TriMesh * trimesh::make_teapot (int tess, bool omit_bottom = false, bool taller = false)
make_torus()
TriMesh * trimesh::make_torus (int tess_th, int tess_ph, float r = 0.25f)
make_uniform_cdfs()
static void trimesh::make_uniform_cdfs (const vector< float > & weights1, vector< float > & sampcdf1, const vector< float > & weights2, vector< float > & sampcdf2) static
Referenced by ICP().
make_wave()
TriMesh * trimesh::make_wave (int tess, float omega = M_PIf)
max_x()
static float trimesh::max_x (const TriMesh * mesh, int i) static
Referenced by orient().
median()
static float trimesh::median (vector< float > vals) static
Referenced by ICP_iter().
mesh_center_of_mass()
point trimesh::mesh_center_of_mass (TriMesh * mesh)
Referenced by normalize_variance(), pca_rotate(), and pca_snap().
mesh_covariance()
void trimesh::mesh_covariance (TriMesh * mesh, float(&) C[3][3])
Referenced by normalize_variance(), pca_rotate(), and pca_snap().
mix() [1/2]
template<class T , class A > static T trimesh::mix (const T & x, const T & y, const A & a) inline static
mix() [2/2]
template<class T , class S > static XForm<T> trimesh::mix (const XForm< T > & x, const XForm< T > & y, const S & a) inline static
mkface() [1/2]
static void trimesh::mkface (TriMesh * mesh, int v1, int v2, int v3) inline static
mkface() [2/2]
static void trimesh::mkface (TriMesh * mesh, int v1, int v2, int v3) inline static
Referenced by mkquad(), and trimesh::TriMesh::triangulate_grid().
mkpoint()
static void trimesh::mkpoint (TriMesh * mesh, float x, float y, float z) inline static
Referenced by make_ccone(), make_ccyl(), make_cube(), make_disc(), and make_sphere_polar().
mkquad()
static void trimesh::mkquad (TriMesh * mesh, int ll, int lr, int ul, int ur) inline static
myGluProject()
static GLint trimesh::myGluProject (GLdouble objX, GLdouble objY, GLdouble objZ, const GLdouble * model, const GLdouble * proj, const GLint * view, GLdouble * winX, GLdouble * winY, GLdouble * winZ) inline static
Referenced by myGluUnProject().
myGluUnProject()
static GLint trimesh::myGluUnProject (GLdouble winX, GLdouble winY, GLdouble winZ, const GLdouble * model, const GLdouble * proj, const GLint * view, GLdouble * objX, GLdouble * objY, GLdouble * objZ) inline static
new_loop_edge()
static point trimesh::new_loop_edge (TriMesh * mesh, int f1, int f2, int v0, int v1, int v2, int v3) static
Referenced by insert_vert().
noisify()
void trimesh::noisify (TriMesh * mesh, float amount)
norm_xf()
template<class T > static XForm<T> trimesh::norm_xf (const XForm< T > & xf) inline static
Referenced by apply_xform(), find_overlap_onedir(), ICP_iter(), and selectall_and_match().
normal_rnd() [1/3]
template<class T > static typename ::std::enable_if< ::std::is_floating_point<T>::value, T >::type trimesh::normal_rnd (T sigma) inline static
Referenced by noisify(), trimesh::Vec< 3, float >::normal_rnd(), and normal_rnd().
normal_rnd() [2/3]
template<class T > static typename ::std::enable_if< ::std::is_integral<T>::value, double >::type trimesh::normal_rnd (T sigma) inline static
normal_rnd() [3/3]
static float trimesh::normal_rnd () inline static
normalize()
template<size_t D, class T > static void trimesh::normalize (Vec< D, T > & v) inline static
Referenced by apply_xform(), diffuse_normals(), myGluUnProject(), trimesh::TriMesh::need_curvatures(), trimesh::TriMesh::need_dcurv(), trimesh::TriMesh::need_normals(), normalized(), numbrella(), and write_stl().
normalize_variance()
void trimesh::normalize_variance (TriMesh * mesh)
normalized()
template<size_t D, class T > static Vec<D,T> trimesh::normalized (const Vec< D, T > & v) inline static
normals_from_faces_area()
static void trimesh::normals_from_faces_area (vector< TriMesh::Face > & faces, vector< point > & vertices, vector< vec > & normals) static
Referenced by trimesh::TriMesh::need_normals().
normals_from_faces_Max()
static void trimesh::normals_from_faces_Max (vector< TriMesh::Face > & faces, vector< point > & vertices, vector< vec > & normals) static
Referenced by trimesh::TriMesh::need_normals().
normals_from_points()
static void trimesh::normals_from_points (vector< point > & vertices, vector< vec > & normals) static
Referenced by trimesh::TriMesh::need_normals().
normals_from_tstrips_area()
static void trimesh::normals_from_tstrips_area (vector< int > & tstrips, vector< point > & vertices, vector< vec > & normals) static
Referenced by trimesh::TriMesh::need_normals().
normals_from_tstrips_Max()
static void trimesh::normals_from_tstrips_Max (vector< int > & tstrips, vector< point > & vertices, vector< vec > & normals) static
Referenced by trimesh::TriMesh::need_normals().
now()
static timestamp trimesh::now () inline static
Referenced by trimesh::GLCamera::autospin(), bilateral_smooth_mesh(), compute_overlaps(), diffuse_curv(), diffuse_dcurv(), diffuse_normals(), diffuse_vector(), trimesh::GLCamera::GLCamera(), ICP(), ICP_iter(), JoinMarkerArrays(), JoinMarkerArraysAndMarkers(), JoinMarkers(), main(), common::MakeArrowMarkerByEnds(), common::MakeArrowMarkerByPose(), common::MakeCovarianceMarker(), MakePointsNormalMarker(), common::MakeTextMarker(), MarkerArrayOfArrow(), MarkerArrayOfSensor(), MarkerOfArrow(), MarkerOfBoundary(), MarkerOfCircle(), MarkerOfEclipse(), MarkerOfLines(), MarkerOfPoints(), MarkerOfText(), trimesh::GLCamera::mouse(), myGluUnProject(), dbg::pretty_print(), and smooth_mesh().
numbrella()
void trimesh::numbrella (TriMesh * mesh, float stepsize)
operator!() [1/2]
template<size_t D, class T > static bool trimesh::operator! (const Box< D, T > & b) inline static
operator!() [2/2]
template<size_t D, class T > static bool trimesh::operator! (const Vec< D, T > & v) inline static
operator!=() [1/3]
template<size_t D, class T > static bool trimesh::operator!= (const Box< D, T > & b1, const Box< D, T > & b2) inline static
operator!=() [2/3]
template<class T > static bool trimesh::operator!= (const XForm< T > & xf1, const XForm< T > & xf2) inline static
operator!=() [3/3]
template<size_t D, class T > static bool trimesh::operator!= (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator%()
template<class T > static const Vec<3,T> trimesh::operator% (const Vec< 3, T > & v1, const Vec< 3, T > & v2) inline static
operator*() [1/3]
template<class T > static XForm<T> trimesh::operator* (const XForm< T > & xf1, const XForm< T > & xf2) inline static
operator*() [2/3]
template<class S , class T > static const S trimesh::operator* (const XForm< T > & xf, const S & v) inline static
operator*() [3/3]
template<size_t D, class T > static const Vec<D,T> trimesh::operator* (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator+() [1/3]
template<class T > static XForm<T> trimesh::operator+ (const XForm< T > & xf1, const XForm< T > & xf2) inline static
operator+() [2/3]
template<size_t D, class T > static const Vec<D,T> trimesh::operator+ (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator+() [3/3]
template<size_t D, class T > static const Vec<D,T>& trimesh::operator+ (const Vec< D, T > & v) inline static
operator-() [1/4]
static float trimesh::operator- (const timestamp & t1, const timestamp & t2) inline static
operator-() [2/4]
template<class T > static XForm<T> trimesh::operator- (const XForm< T > & xf1, const XForm< T > & xf2) inline static
operator-() [3/4]
template<size_t D, class T > static const Vec<D,T> trimesh::operator- (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator-() [4/4]
template<size_t D, class T > static const Vec<D,T> trimesh::operator- (const Vec< D, T > & v) inline static
operator/()
template<size_t D, class T > static const Vec<D,T> trimesh::operator/ (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator<()
template<size_t D, class T > static bool trimesh::operator< (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator<<() [1/2]
template<class T > static inline ::std::ostream& trimesh::operator<< (::std::ostream & os, const XForm< T > & m) static
operator<<() [2/2]
template<size_t D, class T > static inline ::std::ostream& trimesh::operator<< (::std::ostream & os, const Vec< D, T > & v) static
operator<=()
template<size_t D, class T > static bool trimesh::operator<= (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator==() [1/3]
template<size_t D, class T > static bool trimesh::operator== (const Box< D, T > & b1, const Box< D, T > & b2) inline static
operator==() [2/3]
template<class T > static bool trimesh::operator== (const XForm< T > & xf1, const XForm< T > & xf2) inline static
operator==() [3/3]
template<size_t D, class T > static bool trimesh::operator== (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator>()
template<size_t D, class T > static bool trimesh::operator> (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator>=()
template<size_t D, class T > static bool trimesh::operator>= (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
operator>>() [1/2]
template<class T > static inline ::std::istream& trimesh::operator>> (::std::istream & is, XForm< T > & m) static
operator>>() [2/2]
template<size_t D, class T > static inline ::std::istream& trimesh::operator>> (::std::istream & is, Vec< D, T > & v) static
operator^()
template<size_t D, class T > static const T trimesh::operator^ (const Vec< D, T > & v1, const Vec< D, T > & v2) inline static
opposite()
static point trimesh::opposite (TriMesh * mesh, int f, int v) static
Referenced by butterfly().
orient()
void trimesh::orient (TriMesh * mesh)
orthogonalize()
template<class T > static void trimesh::orthogonalize (XForm< T > & xf) inline static
Referenced by ICP_iter().
pca_rotate()
void trimesh::pca_rotate (TriMesh * mesh)
pca_snap()
void trimesh::pca_snap (TriMesh * mesh)
ply_property()
static bool trimesh::ply_property (const char * buf, int & len, bool binary) static
Referenced by read_ply().
ply_type_len()
static int trimesh::ply_type_len (const char * buf, bool binary) static
Referenced by ply_property(), and read_ply().
point_center_of_mass() [1/2]
point trimesh::point_center_of_mass (const vector< point > & pts)
Referenced by mesh_center_of_mass().
point_center_of_mass() [2/2]
point trimesh::point_center_of_mass (const ::std::vector< point > & pts)
point_covariance() [1/2]
void trimesh::point_covariance (const ::std::vector< point > & pts, float(&) C[3][3])
point_covariance() [2/2]
void trimesh::point_covariance (const vector< point > & pts, float(&) C[3][3])
Referenced by mesh_covariance().
proj_curv()
void trimesh::proj_curv (const vec & old_u, const vec & old_v, float old_ku, float old_kuv, float old_kv, const vec & new_u, const vec & new_v, float & new_ku, float & new_kuv, float & new_kv)
Referenced by trimesh::TriMesh::need_curvatures(), trimesh::TriMesh::need_dcurv(), and trimesh::AccumCurv::operator()().
proj_dcurv()
void trimesh::proj_dcurv (const vec & old_u, const vec & old_v, const Vec< 4 > old_dcurv, const vec & new_u, const vec & new_v, Vec< 4 > & new_dcurv)
Referenced by trimesh::TriMesh::need_dcurv(), and trimesh::AccumDCurv::operator()().
pushback()
static void trimesh::pushback (const char * buf, FILE * f) static
Referenced by trimesh::TriMesh::read_helper().
radians() [1/3]
template<class T > static double trimesh::radians (const T & x) inline static
Referenced by std::get().
radians() [2/3]
static float trimesh::radians (const float & x) inline static
radians() [3/3]
static long double trimesh::radians (const long double & x) inline static
read_3ds()
static bool trimesh::read_3ds (FILE * f, TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
read_faces_asc()
static bool trimesh::read_faces_asc (FILE * f, TriMesh * mesh, int nfaces, int face_len, int face_count, int face_idx, bool read_to_eol = false) static
Referenced by read_off(), read_ply(), and read_sm().
read_faces_bin()
static bool trimesh::read_faces_bin (FILE * f, TriMesh * mesh, bool need_swap, int nfaces, int face_len, int face_count, int face_idx) static
Referenced by read_ply(), and read_vvd().
read_grid_asc()
static bool trimesh::read_grid_asc (FILE * f, TriMesh * mesh) static
Referenced by read_ply().
read_grid_bin()
static bool trimesh::read_grid_bin (FILE * f, TriMesh * mesh, bool need_swap) static
Referenced by read_ply().
read_obj()
static bool trimesh::read_obj (FILE * f, TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
read_off()
static bool trimesh::read_off (FILE * f, TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
read_ply()
static bool trimesh::read_ply (FILE * f, TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
read_pts()
static bool trimesh::read_pts (FILE * f, TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
read_ray()
static bool trimesh::read_ray (FILE * f, TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
read_sm()
static bool trimesh::read_sm (FILE * f, TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
read_stl()
static bool trimesh::read_stl (FILE * f, TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
read_strips_asc()
static bool trimesh::read_strips_asc (FILE * f, TriMesh * mesh) static
Referenced by read_ply().
read_strips_bin()
static bool trimesh::read_strips_bin (FILE * f, TriMesh * mesh, bool need_swap) static
Referenced by read_ply().
read_verts_asc()
static bool trimesh::read_verts_asc (FILE * f, TriMesh * mesh, int nverts, int vert_len, int vert_pos, int vert_norm, int vert_color, bool float_color, int vert_conf) static
Referenced by read_off(), read_ply(), and read_sm().
read_verts_bin()
static bool trimesh::read_verts_bin (FILE * f, TriMesh * mesh, bool & need_swap, int nverts, int vert_len, int vert_pos, int vert_norm, int vert_color, bool float_color, int vert_conf) static
Referenced by read_3ds(), and read_ply().
read_vvd()
static bool trimesh::read_vvd (FILE * f, TriMesh * mesh) static
Referenced by trimesh::TriMesh::read_helper().
reflect()
template<size_t D, class T > static Vec<D,T> trimesh::reflect (const Vec< D, T > & I, const Vec< D, T > & N) inline static
refract()
template<size_t D, class T > static Vec<D,T> trimesh::refract (const Vec< D, T > & I, const Vec< D, T > & N, const T & eta) inline static
remap_verts() [1/2]
void trimesh::remap_verts (TriMesh * mesh, const std::vector< int > & remap_table)
Referenced by reorder_verts().
remap_verts() [2/2]
void trimesh::remap_verts (TriMesh * mesh, const ::std::vector< int > & remap_table)
Referenced by join(), remove_vertices(), and shared().
remove_faces() [1/2]
void trimesh::remove_faces (TriMesh * mesh, const ::std::vector< bool > & toremove)
Referenced by select_big_comps(), select_comp(), and select_small_comps().
remove_faces() [2/2]
void trimesh::remove_faces (TriMesh * mesh, const vector< bool > & toremove)
Referenced by remove_sliver_faces().
remove_sliver_faces()
void trimesh::remove_sliver_faces (TriMesh * mesh)
Referenced by trimesh::TriMesh::triangulate_grid().
remove_unused_vertices()
void trimesh::remove_unused_vertices (TriMesh * mesh)
Referenced by select_big_comps(), select_comp(), and select_small_comps().
remove_vertices() [1/2]
void trimesh::remove_vertices (TriMesh * mesh, const vector< bool > & toremove)
Referenced by remove_unused_vertices().
remove_vertices() [2/2]
void trimesh::remove_vertices (TriMesh * mesh, const ::std::vector< bool > & toremove)
Referenced by clip(), and erode().
reorder_verts()
void trimesh::reorder_verts (TriMesh * mesh)
replace_ext()
static inline ::std::string trimesh::replace_ext (const ::std::string & filename, const ::std::string & ext) static
Referenced by bboxname(), and xfname().
rot()
void trimesh::rot (TriMesh * mesh, float r, const vec & axis)
Referenced by align_symm(), trimesh::GLCamera::autospin(), make_surface_of_revolution(), and myGluUnProject().
rot_coord_sys()
static void trimesh::rot_coord_sys (const vec & old_u, const vec & old_v, const vec & new_norm, vec & new_u, vec & new_v) static
Referenced by diagonalize_curv(), proj_curv(), and proj_dcurv().
rot_only()
template<class T > static XForm<T> trimesh::rot_only (const XForm< T > & xf) inline static
scale() [1/3]
void trimesh::scale (TriMesh * mesh, float s)
Referenced by align_scale(), align_symm(), eigdc(), ICP_iter(), myGluUnProject(), trimesh::TriMesh::need_pointareas(), noisify(), normalize_variance(), scale(), svd(), and uniform_rnd().
scale() [2/3]
void trimesh::scale (TriMesh * mesh, float sx, float sy, float sz)
scale() [3/3]
void trimesh::scale (TriMesh * mesh, float s, const vec & d)
select_big_comps() [1/2]
void trimesh::select_big_comps (TriMesh * mesh, const vector< int > & comps, const vector< int > & compsizes, int min_size, int total_largest)
select_big_comps() [2/2]
void trimesh::select_big_comps (TriMesh * mesh, const ::std::vector< int > & comps, const ::std::vector< int > & compsizes, int min_size, int total_largest = ::std::numeric_limits< int >::max())
select_comp() [1/2]
void trimesh::select_comp (TriMesh * mesh, const vector< int > & comps, int whichcc)
select_comp() [2/2]
void trimesh::select_comp (TriMesh * mesh, const ::std::vector< int > & comps, int whichcc)
select_small_comps() [1/2]
void trimesh::select_small_comps (TriMesh * mesh, const ::std::vector< int > & comps, const ::std::vector< int > & compsizes, int max_size, int total_smallest = ::std::numeric_limits< int >::max())
select_small_comps() [2/2]
void trimesh::select_small_comps (TriMesh * mesh, const vector< int > & comps, const vector< int > & compsizes, int max_size, int total_smallest)
selectall_and_match()
static void trimesh::selectall_and_match (TriMesh * tgt, TriMesh * src, const xform & srcxf, const KDtree * tgtkd, float maxdist, float angle_thresh, vector< PtPair > & pairs) static
Referenced by ICP_iter().
sgn()
template<class T > static T trimesh::sgn (const T & x) inline static
Referenced by std::get(), and sign().
shared()
void trimesh::shared (TriMesh * mesh, float tol)
sign()
template<class T > static T trimesh::sign (const T & x) inline static
skip_comments()
static void trimesh::skip_comments (FILE * f) static
Referenced by read_faces_asc(), read_obj(), read_off(), read_sm(), read_strips_asc(), and read_verts_asc().
slurp_verts_bin()
static bool trimesh::slurp_verts_bin (FILE * f, TriMesh * mesh, bool need_swap, int nverts) static
Referenced by read_verts_bin().
smooth_mesh()
void trimesh::smooth_mesh (TriMesh * themesh, float sigma)
smoothstep()
template<class T , class A , class B > static T trimesh::smoothstep (const A & a, const B & b, const T & x) inline static
Referenced by std::get().
sort_comps()
static void trimesh::sort_comps (vector< int > & comps, vector< int > & compsizes) static
Referenced by find_comps().
sqr() [1/2]
static float trimesh::sqr (float x) inline static
Referenced by trimesh::KDtree::Node::build(), trimesh::KDtree::closest_to_pt(), trimesh::KDtree::closest_to_ray(), dist2(), dist2ray2(), trimesh::KDtree::Node::exists_pt(), trimesh::KDtree::exists_pt_within(), trimesh::KDtree::Node::find_closest_compat_to_pt(), trimesh::KDtree::Node::find_closest_compat_to_ray(), trimesh::KDtree::Node::find_closest_to_pt(), trimesh::KDtree::Node::find_closest_to_ray(), trimesh::KDtree::Node::find_k_closest_compat_to_pt(), and trimesh::KDtree::Node::find_k_closest_to_pt().
sqr() [2/2]
template<class T > static T trimesh::sqr (const T & x) inline static
Referenced by bilateral_smooth_mesh(), decompose_rot(), diffuse_curv(), diffuse_dcurv(), diffuse_normals(), diffuse_vector(), dist2(), eigdc(), trimesh::Basis< D, T >::excess(), find_overlap_onedir(), std::get(), ICP_iter(), join(), ldltdc(), len2(), loop_update_alpha(), make_cube(), myGluUnProject(), trimesh::TriMesh::need_bsphere(), new_loop_edge(), normal_rnd(), trimesh::Basis< D, T >::pop(), trimesh::Basis< D, T >::push(), refract(), remove_sliver_faces(), selectall_and_match(), trimesh::GLCamera::setupGL(), shared(), smooth_mesh(), trimesh::TriMesh::stat(), trimesh::Vec< 3, float >::sumsqr(), and svd().
step()
template<class T , class A > static T trimesh::step (const A & a, const T & x) inline static
Referenced by std::get(), and smoothstep().
string_printf()
static inline ::std::string trimesh::string_printf (const char * format, ...) static
subdiv()
void trimesh::subdiv (TriMesh * mesh, SubdivScheme scheme = SUBDIV_LOOP)
svd()
template<class T , int M, int N> static void trimesh::svd (T(&) A[M][N], T s[N], T(&) V[N][N]) inline static
swap_16()
static void trimesh::swap_16 (unsigned char * p) inline static
Referenced by swap_short(), and swap_ushort().
swap_32()
static void trimesh::swap_32 (unsigned char * p) inline static
Referenced by swap_float(), swap_int(), and swap_unsigned().
swap_64()
static void trimesh::swap_64 (unsigned char * p) inline static
Referenced by swap_double().
swap_double()
static void trimesh::swap_double (double & x) inline static
Referenced by read_vvd().
swap_float()
static void trimesh::swap_float (float & x) inline static
Referenced by check_need_swap(), read_stl(), read_verts_bin(), slurp_verts_bin(), swap_vert_props(), and write_stl().
swap_int()
static void trimesh::swap_int (int & x) inline static
Referenced by read_faces_bin(), read_grid_bin(), read_stl(), read_strips_bin(), read_vvd(), write_faces_bin(), write_grid_bin(), write_ply_binary(), write_stl(), and write_strips_bin().
swap_short()
static void trimesh::swap_short (short & x) inline static
swap_unsigned()
static void trimesh::swap_unsigned (unsigned & x) inline static
Referenced by read_3ds(), and read_faces_bin().
swap_ushort()
static void trimesh::swap_ushort (unsigned short & x) inline static
Referenced by read_3ds().
swap_vert_props()
static void trimesh::swap_vert_props (TriMesh * mesh, bool swap_color) static
Referenced by write_verts_bin().
tess()
static void trimesh::tess (const vector< point > & verts, const vector< int > & thisface, vector< TriMesh::Face > & tris) static
Referenced by make_cube(), make_teapot(), read_faces_asc(), read_faces_bin(), read_obj(), and read_ray().
trans()
void trimesh::trans (TriMesh * mesh, const vec & transvec)
Referenced by align_pt2pl_trans(), align_scale(), align_symm(), trimesh::GLCamera::autospin(), myGluUnProject(), normalize_variance(), pca_rotate(), and pca_snap().
trans_only()
template<class T > static XForm<T> trimesh::trans_only (const XForm< T > & xf) inline static
transp()
template<class T > static XForm<T> trimesh::transp (const XForm< T > & xf) inline static
Referenced by transpose().
transpose()
template<class T > static void trimesh::transpose (XForm< T > & xf) inline static
trinorm()
template<class T > static Vec<3,T> trimesh::trinorm (const Vec< 3, T > & v0, const Vec< 3, T > & v1, const Vec< 3, T > & v2) inline static
Referenced by mesh_center_of_mass(), mesh_covariance(), orient(), trimesh::TriMesh::stat(), and trimesh::TriMesh::trinorm().
tstrip_build()
static void trimesh::tstrip_build (TriMesh & mesh, int f, vector< signed char > & face_avail, vector< int > & todo) static
Referenced by trimesh::TriMesh::need_tstrips().
umbrella()
void trimesh::umbrella (TriMesh * mesh, float stepsize, bool tangent = false)
Referenced by lmsmooth().
uniform_rnd() [1/3]
template<class T > static typename ::std::enable_if< ::std::is_integral<T>::value, T >::type trimesh::uniform_rnd (T n) inline static
Referenced by trimesh::TriMesh::feature_size(), trimesh::Noise3D::Noise3D(), noisify(), normal_rnd(), trimesh::Vec< 3, float >::uniform_rnd(), and uniform_rnd().
uniform_rnd() [2/3]
template<class T > static typename ::std::enable_if< ::std::is_floating_point<T>::value, T >::type trimesh::uniform_rnd (T n) inline static
uniform_rnd() [3/3]
static float trimesh::uniform_rnd () inline static
void()
typedef trimesh::void (APIENTRYP glGenBuffers_t)
Referenced by trimesh::TriMesh::dprintf(), trimesh::TriMesh::set_verbose(), and trimesh::GLManager::texture().
we_are_big_endian()
static bool trimesh::we_are_big_endian () inline static
Referenced by read_3ds(), read_ply(), read_stl(), and write_stl().
we_are_little_endian()
static bool trimesh::we_are_little_endian () inline static
Referenced by read_ply(), read_vvd(), we_are_big_endian(), trimesh::TriMesh::write(), and write_ply_binary().
write_cc()
static bool trimesh::write_cc (TriMesh * mesh, FILE * f, const char * filename, bool write_norm, bool float_color) static
Referenced by trimesh::TriMesh::write().
write_dae()
static bool trimesh::write_dae (TriMesh * mesh, FILE * f) static
Referenced by trimesh::TriMesh::write().
write_faces_asc()
static bool trimesh::write_faces_asc (TriMesh * mesh, FILE * f, const char * before_face, const char * after_line) static
Referenced by write_obj(), write_off(), write_ply_ascii(), write_ray(), and write_sm().
write_faces_bin()
static bool trimesh::write_faces_bin (TriMesh * mesh, FILE * f, bool need_swap, int before_face_len, const char * before_face, int after_face_len, const char * after_face) static
Referenced by write_ply_binary().
write_grid_asc()
static bool trimesh::write_grid_asc (TriMesh * mesh, FILE * f) static
Referenced by write_ply_ascii().
write_grid_bin()
static bool trimesh::write_grid_bin (TriMesh * mesh, FILE * f, bool need_swap) static
Referenced by write_ply_binary().
write_obj()
static bool trimesh::write_obj (TriMesh * mesh, FILE * f, bool write_norm) static
Referenced by trimesh::TriMesh::write().
write_off()
static bool trimesh::write_off (TriMesh * mesh, FILE * f) static
Referenced by trimesh::TriMesh::write().
write_ply_ascii()
static bool trimesh::write_ply_ascii (TriMesh * mesh, FILE * f, bool write_norm, bool write_grid, bool float_color) static
Referenced by trimesh::TriMesh::write().
write_ply_binary()
static bool trimesh::write_ply_binary (TriMesh * mesh, FILE * f, bool little_endian, bool write_norm, bool write_grid, bool float_color) static
Referenced by trimesh::TriMesh::write().
write_ply_header()
static bool trimesh::write_ply_header (TriMesh * mesh, FILE * f, const char * format, bool write_grid, bool write_tstrips, bool write_norm, bool float_color) static
Referenced by write_ply_ascii(), and write_ply_binary().
write_pts()
static bool trimesh::write_pts (TriMesh * mesh, FILE * f) static
Referenced by trimesh::TriMesh::write().
write_ray()
static bool trimesh::write_ray (TriMesh * mesh, FILE * f) static
Referenced by trimesh::TriMesh::write().
write_sm()
static bool trimesh::write_sm (TriMesh * mesh, FILE * f) static
Referenced by trimesh::TriMesh::write().
write_stl()
static bool trimesh::write_stl (TriMesh * mesh, FILE * f) static
Referenced by trimesh::TriMesh::write().
write_strips_asc()
static bool trimesh::write_strips_asc (TriMesh * mesh, FILE * f) static
Referenced by write_ply_ascii().
write_strips_bin()
static bool trimesh::write_strips_bin (TriMesh * mesh, FILE * f, bool need_swap) static
Referenced by write_ply_binary().
write_verts_asc()
static bool trimesh::write_verts_asc (TriMesh * mesh, FILE * f, const char * before_vert, const char * before_norm, const char * before_color, bool float_color, const char * before_conf, const char * after_line) static
Referenced by write_obj(), write_off(), write_ply_ascii(), write_ray(), and write_sm().
write_verts_bin()
static bool trimesh::write_verts_bin (TriMesh * mesh, FILE * f, bool need_swap, bool write_norm, bool write_color, bool float_color, bool write_conf) static
Referenced by write_ply_binary().
write_verts_bin_helper()
static bool trimesh::write_verts_bin_helper (TriMesh * mesh, FILE * f, bool write_norm, bool write_color, bool float_color, bool write_conf) static
Referenced by write_verts_bin().
wt() [1/2]
static float trimesh::wt (const point & p1, const point & p2, float invsigma2) inline static
Referenced by align_symm(), mesh_center_of_mass(), trimesh::TriMesh::need_curvatures(), trimesh::TriMesh::need_dcurv(), new_loop_edge(), and zorin_edge().
wt() [2/2]
static float trimesh::wt (const TriMesh * themesh, int v1, int v2, float invsigma2) inline static
Referenced by diffuse_vert_field(), and jones_filter().
xfname()
static inline ::std::string trimesh::xfname (const ::std::string & filename) static
xorshift_rnd()
static unsigned trimesh::xorshift_rnd (unsigned n = ~0u) inline static
Referenced by trimesh::TriMesh::feature_size(), and uniform_rnd().
XYTDegreeFromXForm()
std::vector<double> trimesh::XYTDegreeFromXForm (const xform & xf)
zorin_edge()
static point trimesh::zorin_edge (TriMesh * mesh, int f1, int f2, int v0, int v1, int v2, int v3) static
Referenced by insert_vert().
Variable Documentation
cube_faces
const int trimesh::cube_faces[] static
Initial value:
= {
    4, 0, 1, 2, 3,
    4, 5, 4, 3, 2,
    4, 4, 5, 6, 7,
    4, 1, 0, 7, 6,
    4, 6, 5, 2, 1,
    4, 0, 3, 4, 7,
}
cube_verts
const float trimesh::cube_verts[] static
Initial value:
= {
    -1, -1, -1,
    -1,  1, -1,
    1,  1, -1,
    1, -1, -1,
    1, -1,  1,
    1,  1,  1,
    -1,  1,  1,
    -1, -1,  1,
}
cuboctahedron_faces
const int trimesh::cuboctahedron_faces[] static
Initial value:
= {
    3, 0, 1, 2,
    3, 0, 3, 4,
    3, 1, 6, 5,
    3, 2, 8, 7,
    3, 3, 7, 9,
    3, 4, 10, 6,
    3, 5, 11, 8,
    3, 9, 11, 10,
    4, 0, 2, 7, 3,
    4, 0, 4, 6, 1,
    4, 1, 5, 8, 2,
    4, 3, 9, 10, 4,
    4, 5, 6, 10, 11,
    4, 7, 8, 11, 9,
}
cuboctahedron_verts
const float trimesh::cuboctahedron_verts[] static
Initial value:
= {
    0, 0, 1.1547,
    1., 0, 0.57735,
    0.3333333, 0.942809, 0.57735,
    -1., 0, 0.57735,
    -0.3333333, -0.942809, 0.57735,
    1., 0, -0.57735,
    0.6666667, -0.942809, 0,
    -0.6666667, 0.942809, 0,
    0.3333333, 0.942809, -0.57735,
    -1., 0, -0.57735,
    -0.3333333, -0.942809, -0.57735,
    0, 0, -1.1547,
}
deltoidal_hexecontahedron_faces
const int trimesh::deltoidal_hexecontahedron_faces[] static
deltoidal_hexecontahedron_verts
const float trimesh::deltoidal_hexecontahedron_verts[] static
deltoidal_icositetrahedron_faces
const int trimesh::deltoidal_icositetrahedron_faces[] static
Initial value:
= {
    4, 3, 0, 1, 2,
    4, 3, 4, 5, 0,
    4, 0, 6, 7, 1,
    4, 1, 7, 8, 2,
    4, 2, 9, 10, 3,
    4, 0, 5, 11, 6,
    4, 5, 4, 12, 11,
    4, 4, 3, 10, 13,
    4, 7, 6, 14, 15,
    4, 2, 8, 16, 9,
    4, 8, 7, 15, 17,
    4, 10, 9, 16, 18,
    4, 11, 19, 14, 6,
    4, 4, 13, 20, 12,
    4, 12, 21, 19, 11,
    4, 10, 18, 20, 13,
    4, 14, 22, 17, 15,
    4, 8, 17, 23, 16,
    4, 16, 23, 24, 18,
    4, 14, 19, 21, 22,
    4, 12, 20, 25, 21,
    4, 20, 18, 24, 25,
    4, 17, 22, 24, 23,
    4, 21, 25, 24, 22,
}
deltoidal_icositetrahedron_verts
const float trimesh::deltoidal_icositetrahedron_verts[] static
Initial value:
= {
    0.3574067, 0.4142136, 0.933949,
    -0.2764395, 0.3203772, 0.933949,
    -0.4620888, -0.2928932, 0.933949,
    0.3574067, -0.4142136, 0.933949,
    0.9675382, -0.2928932, 0.386854,
    0.8293185, 0.3203772, 0.510794,
    0.1480427, 1., 0.386854,
    -0.6101315, 0.7071068, 0.547095,
    -1.010899, 0, 0.386854,
    -0.438374, -0.7734591, 0.510794,
    0.1480427, -1., 0.386854,
    0.8194955, 0.7071068, 0,
    1.010899, 0, -0.386854,
    0.667384, -0.7734591, 0.0876383,
    -0.1480427, 1., -0.386854,
    -0.667384, 0.7734591, -0.0876383,
    -0.8194955, -0.7071068, 0,
    -0.9675382, 0.2928932, -0.386854,
    -0.1480427, -1., -0.386854,
    0.438374, 0.7734591, -0.510794,
    0.6101315, -0.7071068, -0.547095,
    0.4620888, 0.2928932, -0.933949,
    -0.3574067, 0.4142136, -0.933949,
    -0.8293185, -0.3203772, -0.510794,
    -0.3574067, -0.4142136, -0.933949,
    0.2764395, -0.3203772, -0.933949,
}
disdyakis_dodecahedron_faces
const int trimesh::disdyakis_dodecahedron_faces[] static
disdyakis_dodecahedron_verts
const float trimesh::disdyakis_dodecahedron_verts[] static
Initial value:
= {
    0.2157394, 0.2265409, 0.976451,
    -0.4242512, 0.1952621, 0.976451,
    0.2157394, -0.6306019, 0.976451,
    0.7961552, 0.1952621, 0.706812,
    0.1360457, 1., 0.615752,
    -0.5756442, -0.3867295, 0.755245,
    0.8402574, -0.3867295, 0.442412,
    -0.624518, 0.6132705, 0.534039,
    -0.5680774, -0.8619288, 0.325484,
    -1.154386, 0, 0.255053,
    0.7913836, 0.6132705, 0.221206,
    0.6523289, -0.8619288, 0.0558442,
    1.154386, 0, -0.255053,
    -0.6523289, 0.8619288, -0.0558442,
    0.0488738, -1., 0.221206,
    0.5680774, 0.8619288, -0.325484,
    -0.0488738, 1., -0.221206,
    -0.7913836, -0.6132705, -0.221206,
    -0.1360457, -1., -0.615752,
    0.624518, -0.6132705, -0.534039,
    -0.8402574, 0.3867295, -0.442412,
    -0.2157394, 0.6306019, -0.976451,
    -0.7961552, -0.1952621, -0.706812,
    0.5756442, 0.3867295, -0.755245,
    0.4242512, -0.1952621, -0.976451,
    -0.2157394, -0.2265409, -0.976451,
}
disdyakis_triacontahedron_faces
const int trimesh::disdyakis_triacontahedron_faces[] static
disdyakis_triacontahedron_verts
const float trimesh::disdyakis_triacontahedron_verts[] static
dodecahedron_faces
const int trimesh::dodecahedron_faces[] static
Initial value:
= {
    5, 13, 12, 5, 16, 6,
    5, 12, 13, 7, 19, 4,
    5, 12, 4, 9, 8, 5,
    5, 9, 4, 19, 18, 3,
    5, 2, 17, 16, 5, 8,
    5, 0, 14, 15, 3, 18,
    5, 0, 10, 11, 1, 14,
    5, 0, 18, 19, 7, 10,
    5, 7, 13, 6, 11, 10,
    5, 3, 15, 2, 8, 9,
    5, 1, 17, 2, 15, 14,
    5, 1, 11, 6, 16, 17,
}
dodecahedron_verts
const float trimesh::dodecahedron_verts[] static
Initial value:
= {
    -1, -1, -1,
    -1,  1, -1,
     1,  1, -1,
     1, -1, -1,
     1, -1,  1,
     1,  1,  1,
    -1,  1,  1,
    -1, -1,  1,
     phi,  phibar, 0,
     phi, -phibar, 0,
    -phi, -phibar, 0,
    -phi,  phibar, 0,
     phibar, 0,  phi,
    -phibar, 0,  phi,
    -phibar, 0, -phi,
     phibar, 0, -phi,
    0,  phi,  phibar,
    0,  phi, -phibar,
    0, -phi, -phibar,
    0, -phi,  phibar,
}
glAttachShader
glAttachShader_t trimesh::glAttachShader static
Referenced by trimesh::GLManager::make_shader().
glBindBuffer
glBindBuffer_t trimesh::glBindBuffer static
Referenced by trimesh::GLManager::draw_points(), trimesh::GLManager::use_buffer(), and trimesh::GLManager::use_ibuffer().
glBindFramebuffer
glBindFramebuffer_t trimesh::glBindFramebuffer static
Referenced by trimesh::GLManager::rendertarget().
glBindVertexArray
glBindVertexArray_t trimesh::glBindVertexArray static
Referenced by trimesh::GLManager::slow_tstrips(), and trimesh::GLManager::~GLManager().
glBufferData
glBufferData_t trimesh::glBufferData static
Referenced by trimesh::GLManager::update_buffer(), and trimesh::GLManager::update_ibuffer().
glClampColor
glClampColor_t trimesh::glClampColor static
Referenced by trimesh::GLManager::slow_tstrips().
glClampColorARB
glClampColorARB_t trimesh::glClampColorARB static
Referenced by trimesh::GLManager::slow_tstrips().
glCompileShader
glCompileShader_t trimesh::glCompileShader static
Referenced by trimesh::GLManager::make_shader().
glCreateProgram
glCreateProgram_t trimesh::glCreateProgram static
Referenced by trimesh::GLManager::make_shader().
glCreateShader
glCreateShader_t trimesh::glCreateShader static
Referenced by trimesh::GLManager::make_shader().
glDeleteBuffers
glDeleteBuffers_t trimesh::glDeleteBuffers static
Referenced by trimesh::GLManager::clear_buffer(), and trimesh::GLManager::clear_ibuffer().
glDeleteFramebuffers
glDeleteFramebuffers_t trimesh::glDeleteFramebuffers static
Referenced by trimesh::GLManager::rendertarget().
glDeleteProgram
glDeleteProgram_t trimesh::glDeleteProgram static
Referenced by trimesh::GLManager::clear_shader(), and trimesh::GLManager::make_shader().
glDeleteShader
glDeleteShader_t trimesh::glDeleteShader static
Referenced by trimesh::GLManager::clear_shader(), and trimesh::GLManager::make_shader().
glDeleteVertexArrays
glDeleteVertexArrays_t trimesh::glDeleteVertexArrays static
Referenced by trimesh::GLManager::~GLManager().
glDisableVertexAttribArray
glDisableVertexAttribArray_t trimesh::glDisableVertexAttribArray static
Referenced by trimesh::GLManager::clear_attribute(), trimesh::GLManager::clear_attributes(), and trimesh::GLManager::use_shader().
glEnableVertexAttribArray
glEnableVertexAttribArray_t trimesh::glEnableVertexAttribArray static
glFramebufferTexture2D
glFramebufferTexture2D_t trimesh::glFramebufferTexture2D static
Referenced by trimesh::GLManager::rendertarget().
glGenBuffers
glGenBuffers_t trimesh::glGenBuffers static
Referenced by trimesh::GLManager::make_buffer(), and trimesh::GLManager::make_ibuffer().
glGenFramebuffers
glGenFramebuffers_t trimesh::glGenFramebuffers static
Referenced by trimesh::GLManager::rendertarget().
glGenVertexArrays
glGenVertexArrays_t trimesh::glGenVertexArrays static
Referenced by trimesh::GLManager::slow_tstrips().
glGetActiveAttrib
glGetActiveAttrib_t trimesh::glGetActiveAttrib static
Referenced by trimesh::GLManager::make_shader().
glGetActiveUniform
glGetActiveUniform_t trimesh::glGetActiveUniform static
Referenced by trimesh::GLManager::make_shader().
glGetAttribLocation
glGetAttribLocation_t trimesh::glGetAttribLocation static
Referenced by trimesh::GLManager::attribute(), and trimesh::GLManager::make_shader().
glGetProgramInfoLog
glGetProgramInfoLog_t trimesh::glGetProgramInfoLog static
Referenced by trimesh::GLManager::shader_ready(), and trimesh::GLManager::slow_tstrips().
glGetProgramiv
glGetProgramiv_t trimesh::glGetProgramiv static
Referenced by trimesh::GLManager::make_shader(), trimesh::GLManager::shader_ready(), and trimesh::GLManager::slow_tstrips().
glGetShaderInfoLog
glGetShaderInfoLog_t trimesh::glGetShaderInfoLog static
Referenced by trimesh::GLManager::slow_tstrips().
glGetShaderiv
glGetShaderiv_t trimesh::glGetShaderiv static
Referenced by trimesh::GLManager::slow_tstrips().
glGetUniformLocation
glGetUniformLocation_t trimesh::glGetUniformLocation static
Referenced by trimesh::GLManager::make_shader(), and trimesh::GLManager::uniform().
glLinkProgram
glLinkProgram_t trimesh::glLinkProgram static
Referenced by trimesh::GLManager::make_shader().
glPrimitiveRestartIndex
glPrimitiveRestartIndex_t trimesh::glPrimitiveRestartIndex static
Referenced by trimesh::GLManager::slow_tstrips().
glPrimitiveRestartIndexNV
glPrimitiveRestartIndexNV_t trimesh::glPrimitiveRestartIndexNV static
Referenced by trimesh::GLManager::slow_tstrips().
glShaderSource
glShaderSource_t trimesh::glShaderSource static
Referenced by trimesh::GLManager::make_shader().
glUniform1f
glUniform1f_t trimesh::glUniform1f static
Referenced by trimesh::GLManager::uniform1f().
glUniform1i
glUniform1i_t trimesh::glUniform1i static
Referenced by trimesh::GLManager::uniform1i(), and trimesh::GLManager::uniformTexture().
glUniform2f
glUniform2f_t trimesh::glUniform2f static
Referenced by trimesh::GLManager::uniform2f().
glUniform2i
glUniform2i_t trimesh::glUniform2i static
Referenced by trimesh::GLManager::uniform2i().
glUniform3f
glUniform3f_t trimesh::glUniform3f static
Referenced by trimesh::GLManager::uniform3f().
glUniform3i
glUniform3i_t trimesh::glUniform3i static
Referenced by trimesh::GLManager::uniform3i().
glUniform4f
glUniform4f_t trimesh::glUniform4f static
Referenced by trimesh::GLManager::uniform4f().
glUniform4i
glUniform4i_t trimesh::glUniform4i static
Referenced by trimesh::GLManager::uniform4i().
glUniformMatrix2fv
glUniformMatrix2fv_t trimesh::glUniformMatrix2fv static
Referenced by trimesh::GLManager::uniformMatrix2fv().
glUniformMatrix3fv
glUniformMatrix3fv_t trimesh::glUniformMatrix3fv static
Referenced by trimesh::GLManager::uniformMatrix3fv().
glUniformMatrix4fv
glUniformMatrix4fv_t trimesh::glUniformMatrix4fv static
Referenced by trimesh::GLManager::uniformMatrix4fv().
glUseProgram
glUseProgram_t trimesh::glUseProgram static
Referenced by trimesh::GLManager::use_shader().
glValidateProgram
glValidateProgram_t trimesh::glValidateProgram static
Referenced by trimesh::GLManager::shader_ready().
glVertexAttrib1f
glVertexAttrib1f_t trimesh::glVertexAttrib1f static
Referenced by trimesh::GLManager::attribute1f().
glVertexAttrib2f
glVertexAttrib2f_t trimesh::glVertexAttrib2f static
Referenced by trimesh::GLManager::attribute2f().
glVertexAttrib3f
glVertexAttrib3f_t trimesh::glVertexAttrib3f static
Referenced by trimesh::GLManager::attribute3f().
glVertexAttrib4f
glVertexAttrib4f_t trimesh::glVertexAttrib4f static
Referenced by trimesh::GLManager::attribute4f().
glVertexAttribPointer
glVertexAttribPointer_t trimesh::glVertexAttribPointer static
icosahedron_faces
const int trimesh::icosahedron_faces[] static
Initial value:
= {
    3, 0, 4, 1,
    3, 0, 9, 4,
    3, 9, 5, 4,
    3, 4, 5, 8,
    3, 4, 8, 1,
    3, 8, 10, 1,
    3, 8, 3, 10,
    3, 5, 3, 8,
    3, 5, 2, 3,
    3, 2, 7, 3,
    3, 7, 10, 3,
    3, 7, 6, 10,
    3, 7, 11, 6,
    3, 11, 0, 6,
    3, 0, 1, 6,
    3, 6, 1, 10,
    3, 9, 0, 11,
    3, 9, 11, 2,
    3, 9, 2, 5,
    3, 7, 2, 11,
}
icosahedron_verts
const float trimesh::icosahedron_verts[] static
Initial value:
= {
    0, -1,  phi,
    0,  1,  phi,
    0, -1, -phi,
    0,  1, -phi,
     phi, 0,  1,
     phi, 0, -1,
    -phi, 0,  1,
    -phi, 0, -1,
     1,  phi, 0,
     1, -phi, 0,
    -1,  phi, 0,
    -1, -phi, 0,
}
icosidodecahedron_faces
const int trimesh::icosidodecahedron_faces[] static
icosidodecahedron_verts
const float trimesh::icosidodecahedron_verts[] static
octahedron_faces
const int trimesh::octahedron_faces[] static
Initial value:
= {
    3, 0, 1, 2,
    3, 0, 2, 4,
    3, 0, 4, 5,
    3, 0, 5, 1,
    3, 3, 2, 1,
    3, 3, 1, 5,
    3, 3, 5, 4,
    3, 3, 4, 2,
}
octahedron_verts
const float trimesh::octahedron_verts[] static
Initial value:
= {
    1, 0, 0,
    0, 1, 0,
    0, 0, 1,
    -1, 0, 0,
    0, -1, 0,
    0, 0, -1,
}
pentagonal_hexecontahedron_faces
const int trimesh::pentagonal_hexecontahedron_faces[] static
pentagonal_hexecontahedron_verts
const float trimesh::pentagonal_hexecontahedron_verts[] static
pentagonal_icositetrahedron_faces
const int trimesh::pentagonal_icositetrahedron_faces[] static
Initial value:
= {
    5, 4, 0, 1, 2, 3,
    5, 0, 4, 5, 6, 7,
    5, 1, 0, 7, 8, 9,
    5, 2, 1, 9, 10, 11,
    5, 3, 2, 11, 12, 13,
    5, 4, 3, 13, 14, 15,
    5, 5, 4, 15, 16, 17,
    5, 6, 5, 17, 18, 19,
    5, 7, 6, 19, 20, 8,
    5, 9, 8, 20, 21, 22,
    5, 10, 9, 22, 23, 24,
    5, 11, 10, 24, 25, 12,
    5, 13, 12, 26, 27, 14,
    5, 15, 14, 27, 28, 16,
    5, 17, 16, 28, 29, 18,
    5, 19, 18, 29, 30, 31,
    5, 20, 19, 31, 32, 21,
    5, 22, 21, 32, 33, 23,
    5, 24, 23, 33, 34, 25,
    5, 12, 25, 34, 35, 26,
    5, 27, 26, 35, 36, 28,
    5, 29, 28, 36, 37, 30,
    5, 31, 30, 37, 33, 32,
    5, 34, 33, 37, 36, 35,
}
pentagonal_icositetrahedron_verts
const float trimesh::pentagonal_icositetrahedron_verts[] static
pentakis_dodecahedron_faces
const int trimesh::pentakis_dodecahedron_faces[] static
pentakis_dodecahedron_verts
const float trimesh::pentakis_dodecahedron_verts[] static
phi
const float trimesh::phi = 1.61803399f static
Referenced by myGluUnProject().
phibar
const float trimesh::phibar = 0.61803399f static
rhombic_dodecahedron_faces
const int trimesh::rhombic_dodecahedron_faces[] static
Initial value:
= {
    4, 3, 0, 1, 2,
    4, 3, 4, 5, 0,
    4, 0, 5, 6, 1,
    4, 1, 7, 8, 2,
    4, 2, 8, 9, 3,
    4, 5, 4, 10, 11,
    4, 4, 3, 9, 10,
    4, 1, 6, 12, 7,
    4, 6, 5, 11, 12,
    4, 8, 7, 12, 13,
    4, 9, 8, 13, 10,
    4, 10, 13, 12, 11,
}
rhombic_dodecahedron_verts
const float trimesh::rhombic_dodecahedron_verts[] static
Initial value:
= {
    0.5, 0.3535534, 0.866025,
    -0.5, 0.7071068, 0.866025,
    -0.5, -0.3535534, 0.866025,
    0.5, -0.7071068, 0.866025,
    1., -0.3535534, 0,
    1., 0.7071068, 0,
    0, 1.06066, 0,
    -1., 0.3535534, 0,
    -1., -0.7071068, 0,
    0, -1.06066, 0,
    0.5, -0.7071068, -0.866025,
    0.5, 0.3535534, -0.866025,
    -0.5, 0.7071068, -0.866025,
    -0.5, -0.3535534, -0.866025,
}
rhombic_triacontahedron_faces
const int trimesh::rhombic_triacontahedron_faces[] static
rhombic_triacontahedron_verts
const float trimesh::rhombic_triacontahedron_verts[] static
rhombicosidodecahedron_faces
const int trimesh::rhombicosidodecahedron_faces[] static
rhombicosidodecahedron_verts
const float trimesh::rhombicosidodecahedron_verts[] static
rhombicuboctahedron_faces
const int trimesh::rhombicuboctahedron_faces[] static
Initial value:
= {
    3, 0, 2, 3,
    3, 1, 6, 5,
    3, 4, 9, 11,
    3, 7, 15, 13,
    3, 8, 16, 10,
    3, 12, 14, 19,
    3, 17, 22, 18,
    3, 20, 21, 23,
    4, 0, 1, 5, 2,
    4, 0, 3, 9, 4,
    4, 0, 4, 7, 1,
    4, 1, 7, 13, 6,
    4, 2, 5, 12, 8,
    4, 2, 8, 10, 3,
    4, 3, 10, 17, 9,
    4, 4, 11, 15, 7,
    4, 5, 6, 14, 12,
    4, 6, 13, 20, 14,
    4, 8, 12, 19, 16,
    4, 9, 17, 18, 11,
    4, 10, 16, 22, 17,
    4, 11, 18, 21, 15,
    4, 13, 15, 21, 20,
    4, 14, 20, 23, 19,
    4, 16, 19, 23, 22,
    4, 18, 22, 23, 21,
}
rhombicuboctahedron_verts
const float trimesh::rhombicuboctahedron_verts[] static
Initial value:
= {
    0, 0, 1.07072,
    0.7148135, 0, 0.797175,
    -0.104682, 0.7071068, 0.797175,
    -0.6841528, 0.2071068, 0.797175,
    -0.104682, -0.7071068, 0.797175,
    0.6101315, 0.7071068, 0.523628,
    1.04156, 0.2071068, 0.136774,
    0.6101315, -0.7071068, 0.523628,
    -0.3574067, 1., 0.136774,
    -0.7888348, -0.5, 0.523628,
    -0.9368776, 0.5, 0.136774,
    -0.3574067, -1., 0.136774,
    0.3574067, 1., -0.136774,
    0.9368776, -0.5, -0.136774,
    0.7888348, 0.5, -0.523628,
    0.3574067, -1., -0.136774,
    -0.6101315, 0.7071068, -0.523628,
    -1.04156, -0.2071068, -0.136774,
    -0.6101315, -0.7071068, -0.523628,
    0.104682, 0.7071068, -0.797175,
    0.6841528, -0.2071068, -0.797175,
    0.104682, -0.7071068, -0.797175,
    -0.7148135, 0, -0.797175,
    0, 0, -1.07072,
}
snub_cube_faces
const int trimesh::snub_cube_faces[] static
snub_cube_verts
const float trimesh::snub_cube_verts[] static
Initial value:
= {
    0, 0, 1.07736,
    0.7442063, 0, 0.779019,
    0.3123013, 0.6755079, 0.779019,
    -0.482096, 0.5669449, 0.779019,
    -0.7169181, -0.1996786, 0.779019,
    -0.1196038, -0.7345325, 0.779019,
    0.6246025, -0.7345325, 0.480673,
    1.056508, -0.1996786, 0.0680691,
    0.8867128, 0.5669449, 0.230276,
    0.2621103, 1.042774, 0.0680691,
    -0.532287, 0.9342111, 0.0680691,
    -1.006317, 0.3082417, 0.230276,
    -0.7020817, -0.784071, 0.230276,
    0.02728827, -1.074865, 0.0680691,
    0.6667271, -0.784071, -0.318466,
    0.8216855, -0.09111555, -0.690828,
    0.6518908, 0.6755079, -0.528621,
    -0.1196038, 0.8751866, -0.616812,
    -0.8092336, 0.4758293, -0.528621,
    -0.9914803, -0.2761507, -0.318466,
    -0.4467414, -0.825648, -0.528621,
    0.1926974, -0.5348539, -0.915157,
    0.1846311, 0.2587032, -1.02942,
    -0.5049987, -0.1406541, -0.941226,
}
snub_dodecahedron_faces
const int trimesh::snub_dodecahedron_faces[] static
snub_dodecahedron_verts
const float trimesh::snub_dodecahedron_verts[] static
sqrt2
const float trimesh::sqrt2 = 1.41421356f static
sqrt6
const float trimesh::sqrt6 = 2.44948974f static
sqrt8
const float trimesh::sqrt8 = 2.82842712f static
teapot_patches
const int trimesh::teapot_patches[] static
teapot_verts
const float trimesh::teapot_verts[] static
Referenced by make_teapot().
tetrahedron_faces
const int trimesh::tetrahedron_faces[] static
Initial value:
= {
    3, 0, 1, 2,
    3, 2, 1, 3,
    3, 2, 3, 0,
    3, 0, 3, 1,
}
tetrahedron_verts
const float trimesh::tetrahedron_verts[] static
Initial value:
= {
    0, 0, 3,
    sqrt8, 0, -1,
    -sqrt2, sqrt6, -1,
    -sqrt2, -sqrt6, -1,
}
tetrakis_hexahedron_faces
const int trimesh::tetrakis_hexahedron_faces[] static
Initial value:
= {
    3, 2, 0, 1,
    3, 2, 3, 0,
    3, 0, 4, 1,
    3, 1, 5, 2,
    3, 0, 3, 6,
    3, 3, 2, 5,
    3, 1, 4, 7,
    3, 4, 0, 8,
    3, 5, 1, 9,
    3, 3, 10, 6,
    3, 6, 8, 0,
    3, 5, 11, 3,
    3, 4, 8, 7,
    3, 7, 9, 1,
    3, 9, 12, 5,
    3, 6, 10, 8,
    3, 10, 3, 11,
    3, 11, 5, 12,
    3, 7, 8, 13,
    3, 9, 7, 12,
    3, 10, 13, 8,
    3, 11, 12, 10,
    3, 13, 12, 7,
    3, 13, 10, 12,
}
tetrakis_hexahedron_verts
const float trimesh::tetrakis_hexahedron_verts[] static
Initial value:
= {
    0.3162278, 0.7071068, 0.948683,
    -0.7378648, -0.2357023, 0.948683,
    0.3162278, -0.3535534, 0.948683,
    1.159502, -0.2357023, 0.316228,
    -0.6324555, 0.7071068, 0.474342,
    0.1054093, -1.178511, 0.316228,
    0.7905694, 0.7071068, 0,
    -1.159502, 0.2357023, -0.316228,
    -0.1054093, 1.178511, -0.316228,
    -0.7905694, -0.7071068, 0,
    0.7378648, 0.2357023, -0.948683,
    0.6324555, -0.7071068, -0.474342,
    -0.3162278, -0.7071068, -0.948683,
    -0.3162278, 0.3535534, -0.948683,
}
triakis_icosahedron_faces
const int trimesh::triakis_icosahedron_faces[] static
triakis_icosahedron_verts
const float trimesh::triakis_icosahedron_verts[] static
triakis_octahedron_faces
const int trimesh::triakis_octahedron_faces[] static
Initial value:
= {
    3, 2, 0, 1,
    3, 2, 3, 0,
    3, 0, 4, 1,
    3, 1, 3, 2,
    3, 0, 3, 5,
    3, 1, 4, 6,
    3, 4, 0, 6,
    3, 3, 1, 7,
    3, 3, 8, 5,
    3, 5, 8, 0,
    3, 6, 9, 1,
    3, 0, 10, 6,
    3, 1, 11, 7,
    3, 7, 11, 3,
    3, 8, 3, 12,
    3, 0, 8, 10,
    3, 1, 9, 11,
    3, 9, 6, 11,
    3, 6, 10, 8,
    3, 3, 11, 12,
    3, 12, 11, 8,
    3, 6, 13, 11,
    3, 8, 13, 6,
    3, 8, 11, 13,
}
triakis_octahedron_verts
const float trimesh::triakis_octahedron_verts[] static
Initial value:
= {
    0.2810846, 1., 0.959683,
    -0.7609261, -0.7071068, 0.959683,
    0.2810846, -0.1715729, 0.959683,
    1.15844, -0.7071068, 0.397514,
    -0.6785983, 0.4142136, 0.630372,
    0.9114565, 0.4142136, 0.164656,
    -1.15844, 0.7071068, -0.397514,
    0.0482265, -1., 0.164656,
    0.7609261, 0.7071068, -0.959683,
    -0.9114565, -0.4142136, -0.164656,
    -0.0482265, 1., -0.164656,
    -0.2810846, -1., -0.959683,
    0.6785983, -0.4142136, -0.630372,
    -0.2810846, 0.1715729, -0.959683,
}
triakis_tetrahedron_faces
const int trimesh::triakis_tetrahedron_faces[] static
Initial value:
= {
    3, 2, 0, 1,
    3, 2, 3, 0,
    3, 0, 4, 1,
    3, 1, 3, 2,
    3, 0, 3, 5,
    3, 1, 4, 6,
    3, 4, 0, 6,
    3, 3, 1, 7,
    3, 3, 6, 5,
    3, 5, 6, 0,
    3, 6, 7, 1,
    3, 7, 6, 3,
}
triakis_tetrahedron_verts
const float trimesh::triakis_tetrahedron_verts[] static
Initial value:
= {
    0.4264014, 1.414214, 0.904534,
    -1.13707, -0.942809, 0.904534,
    0.4264014, -0.2828427, 0.904534,
    1.421338, -0.942809, -0.301511,
    -0.8528029, 0.5656854, 0.180907,
    0.6822423, 0.5656854, -0.54272,
    -0.7106691, 0.4714045, -1.50756,
    -0.2558409, -0.8485281, -0.54272,
}
truncated_cube_faces
const int trimesh::truncated_cube_faces[] static
Initial value:
= {
    3, 0, 3, 1,
    3, 2, 6, 5,
    3, 4, 8, 9,
    3, 7, 12, 13,
    3, 10, 17, 16,
    3, 11, 15, 18,
    3, 14, 19, 20,
    3, 21, 22, 23,
    8, 0, 1, 4, 9, 15, 11, 6, 2,
    8, 0, 2, 5, 10, 16, 12, 7, 3,
    8, 1, 3, 7, 13, 19, 14, 8, 4,
    8, 5, 6, 11, 18, 22, 21, 17, 10,
    8, 8, 14, 20, 23, 22, 18, 15, 9,
    8, 12, 16, 17, 21, 23, 20, 19, 13,
}
truncated_cube_verts
const float trimesh::truncated_cube_verts[] static
Initial value:
= {
    0, 0, 1.04201,
    0.5621693, 0, 0.877355,
    -0.4798415, 0.2928932, 0.877355,
    0.2569714, -0.5, 0.877355,
    0.8773552, 0.2928932, 0.479841,
    -0.9014684, 0.2071068, 0.479841,
    -0.5962706, 0.7071068, 0.479841,
    0.1405423, -0.9142136, 0.479841,
    1.017898, 0.2071068, -0.0823278,
    0.7609261, 0.7071068, 0.0823278,
    -1.017898, -0.2071068, 0.0823278,
    -0.2810846, 1., 0.0823278,
    -0.2810846, -1., 0.0823278,
    0.2810846, -1., -0.0823278,
    0.9014684, -0.2071068, -0.479841,
    0.2810846, 1., -0.0823278,
    -0.7609261, -0.7071068, -0.0823278,
    -0.8773552, -0.2928932, -0.479841,
    -0.1405423, 0.9142136, -0.479841,
    0.5962706, -0.7071068, -0.479841,
    0.4798415, -0.2928932, -0.877355,
    -0.5621693, 0, -0.877355,
    -0.2569714, 0.5, -0.877355,
    0, 0, -1.04201,
}
truncated_cuboctahedron_faces
const int trimesh::truncated_cuboctahedron_faces[] static
Initial value:
= {
    4, 0, 1, 4, 2,
    4, 3, 8, 14, 7,
    4, 5, 10, 18, 11,
    4, 6, 12, 20, 13,
    4, 9, 17, 24, 16,
    4, 15, 23, 27, 19,
    4, 21, 25, 33, 29,
    4, 22, 30, 38, 31,
    4, 26, 35, 41, 34,
    4, 28, 37, 42, 36,
    4, 32, 39, 44, 40,
    4, 43, 46, 47, 45,
    6, 0, 2, 6, 13, 8, 3,
    6, 1, 5, 11, 17, 9, 4,
    6, 7, 14, 22, 31, 23, 15,
    6, 10, 19, 27, 35, 26, 18,
    6, 12, 21, 29, 37, 28, 20,
    6, 16, 24, 32, 40, 33, 25,
    6, 30, 36, 42, 46, 43, 38,
    6, 34, 41, 45, 47, 44, 39,
    8, 0, 3, 7, 15, 19, 10, 5, 1,
    8, 2, 4, 9, 16, 25, 21, 12, 6,
    8, 8, 13, 20, 28, 36, 30, 22, 14,
    8, 11, 18, 26, 34, 39, 32, 24, 17,
    8, 23, 31, 38, 43, 45, 41, 35, 27,
    8, 29, 33, 40, 44, 47, 46, 42, 37,
}
truncated_cuboctahedron_verts
const float trimesh::truncated_cuboctahedron_verts[] static
truncated_dodecahedron_faces
const int trimesh::truncated_dodecahedron_faces[] static
truncated_dodecahedron_verts
const float trimesh::truncated_dodecahedron_verts[] static
truncated_icosahedron_faces
const int trimesh::truncated_icosahedron_faces[] static
truncated_icosahedron_verts
const float trimesh::truncated_icosahedron_verts[] static
truncated_icosidodecahedron_faces
const int trimesh::truncated_icosidodecahedron_faces[] static
truncated_icosidodecahedron_verts
const float trimesh::truncated_icosidodecahedron_verts[] static
truncated_octahedron_faces
const int trimesh::truncated_octahedron_faces[] static
Initial value:
= {
    4, 0, 3, 5, 1,
    4, 2, 7, 12, 6,
    4, 4, 9, 15, 10,
    4, 8, 13, 19, 14,
    4, 11, 17, 21, 16,
    4, 18, 20, 23, 22,
    6, 0, 1, 4, 10, 7, 2,
    6, 0, 2, 6, 13, 8, 3,
    6, 1, 5, 11, 16, 9, 4,
    6, 3, 8, 14, 17, 11, 5,
    6, 6, 12, 18, 22, 19, 13,
    6, 7, 10, 15, 20, 18, 12,
    6, 9, 16, 21, 23, 20, 15,
    6, 14, 19, 22, 23, 21, 17,
}
truncated_octahedron_verts
const float trimesh::truncated_octahedron_verts[] static
Initial value:
= {
    0, 0, 1.05409,
    0.6324555, 0, 0.843274,
    -0.421637, 0.4714045, 0.843274,
    -0.07027284, -0.6285394, 0.843274,
    0.843274, 0.4714045, 0.421637,
    0.5621827, -0.6285394, 0.632455,
    -0.9135469, 0.3142697, 0.421637,
    -0.2108185, 0.942809, 0.421637,
    -0.5621827, -0.7856742, 0.421637,
    0.9838197, 0.3142697, -0.210818,
    0.421637, 0.942809, 0.210818,
    0.7027284, -0.7856742, 0,
    -0.7027284, 0.7856742, 0,
    -0.9838197, -0.3142697, 0.210818,
    -0.421637, -0.942809, -0.210818,
    0.5621827, 0.7856742, -0.421637,
    0.9135469, -0.3142697, -0.421637,
    0.2108185, -0.942809, -0.421637,
    -0.5621827, 0.6285394, -0.632455,
    -0.843274, -0.4714045, -0.421637,
    0.07027284, 0.6285394, -0.843274,
    0.421637, -0.4714045, -0.843274,
    -0.6324555, 0, -0.843274,
    0, 0, -1.05409,
}
truncated_tetrahedron_faces
const int trimesh::truncated_tetrahedron_faces[] static
Initial value:
= {
    3, 0, 3, 1,
    3, 2, 6, 5,
    3, 4, 8, 9,
    3, 7, 10, 11,
    6, 0, 1, 4, 9, 6, 2,
    6, 0, 2, 5, 10, 7, 3,
    6, 1, 3, 7, 11, 8, 4,
    6, 5, 6, 9, 8, 11, 10,
}
truncated_tetrahedron_verts
const float trimesh::truncated_tetrahedron_verts[] static
Initial value:
= {
    0, 0, 1.10554,
    0.8528029, 0, 0.703527,
    -0.7106691, 0.4714045, 0.703527,
    0.3316456, -0.7856742, 0.703527,
    0.9949367, 0.4714045, -0.100504,
    -1.089693, 0.1571348, -0.100504,
    -0.5685352, 0.942809, -0.100504,
    -0.04737794, -1.099944, -0.100504,
    0.6159132, 0.1571348, -0.904534,
    0.2842676, 0.942809, -0.502519,
    -0.758047, -0.6285394, -0.502519,
    0.09475587, -0.6285394, -0.904534,
}