Symmetric NDT: trimesh::Miniball< D, T > Class Template Reference
trimesh::Miniball< D, T > Class Template Reference
#include <bsphere.h>
Public Types
typedef ::std::list< Vec< D, T > >::iterator It
Public Member Functions
void check_in (const Vec< D, T > &p)
template<class I >
void check_in (I first, I last)
void build (bool pivoting=true)
Vec< D, T > center () const
T squared_radius () const
Member Typedef Documentation
It
template<size_t D, class T> typedef ::std::list< Vec<D,T> >::iterator trimesh::Miniball< D, T >::It
Member Function Documentation
build()
template<size_t D, class T > void trimesh::Miniball< D, T >::build (bool pivoting = true)
Referenced by trimesh::TriMesh::need_bsphere().
center()
template<size_t D, class T> Vec<D,T> trimesh::Miniball< D, T >::center () const inline
Referenced by trimesh::TriMesh::need_bsphere(), and trimesh::Basis< D, T >::pop().
check_in() [1/2]
template<size_t D, class T> void trimesh::Miniball< D, T >::check_in (const Vec< D, T > & p) inline
Referenced by trimesh::TriMesh::need_bsphere().
check_in() [2/2]
template<size_t D, class T> template<class I > void trimesh::Miniball< D, T >::check_in (I first, I last) inline
squared_radius()
template<size_t D, class T> T trimesh::Miniball< D, T >::squared_radius () const inline
Referenced by trimesh::TriMesh::need_bsphere().
The documentation for this class was generated from the following file:
bsphere.h