Symmetric NDT: trimesh::GLManager Class Reference
trimesh::GLManager Class Reference
#include <GLManager.h>
Classes
struct AttributeInfo
class BufferInfo
class ShaderDefine
class ShaderInfo
struct UniformInfo
Public Member Functions
GLManager ()
~GLManager ()
void define (const char *defname, const char *value)
void clear_defines ()
unsigned make_shader (const char *name, const char *vert_text, const char *frag_text)
unsigned make_shader_from_files (const char *name, const char *vert_filename, const char *frag_filename)
bool use_shader (unsigned ind=0)
bool use_shader (const char *name)
void clear_shader (unsigned ind)
void clear_shader (const char *name)
void clear_shaders ()
void uniform1i (int ind, int x)
void uniform2i (int ind, int x, int y)
void uniform3i (int ind, int x, int y, int z)
void uniform4i (int ind, int x, int y, int z, int w)
void uniform1iv (int ind, const int *p)
void uniform2iv (int ind, const int *p)
void uniform3iv (int ind, const int *p)
void uniform4iv (int ind, const int *p)
void uniform1f (int ind, float x)
void uniform2f (int ind, float x, float y)
void uniform3f (int ind, float x, float y, float z)
void uniform4f (int ind, float x, float y, float z, float w)
void uniform1fv (int ind, const float *p)
void uniform2fv (int ind, const float *p)
void uniform3fv (int ind, const float *p)
void uniform4fv (int ind, const float *p)
void uniformMatrix2fv (int ind, const float *p)
void uniformMatrix3fv (int ind, const float *p)
void uniformMatrix4fv (int ind, const float *p)
void uniformTexture (int ind, unsigned texind)
void uniformTexture (int ind, const void *p)
template<class T >
void uniformTexture (int ind, const ::std::vector< T > &v)
void uniform1i (const char *name, int x)
void uniform2i (const char *name, int x, int y)
void uniform3i (const char *name, int x, int y, int z)
void uniform4i (const char *name, int x, int y, int z, int w)
void uniform1iv (const char *name, const int *p)
void uniform2iv (const char *name, const int *p)
void uniform3iv (const char *name, const int *p)
void uniform4iv (const char *name, const int *p)
void uniform1f (const char *name, float x)
void uniform2f (const char *name, float x, float y)
void uniform3f (const char *name, float x, float y, float z)
void uniform4f (const char *name, float x, float y, float z, float w)
void uniform1fv (const char *name, const float *p)
void uniform2fv (const char *name, const float *p)
void uniform3fv (const char *name, const float *p)
void uniform4fv (const char *name, const float *p)
void uniformMatrix2fv (const char *name, const float *p)
void uniformMatrix3fv (const char *name, const float *p)
void uniformMatrix4fv (const char *name, const float *p)
void uniformTexture (const char *name, unsigned texind)
void uniformTexture (const char *name, const void *p)
template<class T >
void uniformTexture (const char *name, const ::std::vector< T > &v)
void clear_uniform (int ind)
void clear_uniform (const char *name)
void clear_uniforms ()
void attributearray1fv (int ind, const float *p, size_t stride=0, size_t offset=0)
void attributearray2fv (int ind, const float *p, size_t stride=0, size_t offset=0)
void attributearray3fv (int ind, const float *p, size_t stride=0, size_t offset=0)
void attributearray4fv (int ind, const float *p, size_t stride=0, size_t offset=0)
void attributearray1fv (const char *name, const float *p, size_t stride=0, size_t offset=0)
void attributearray2fv (const char *name, const float *p, size_t stride=0, size_t offset=0)
void attributearray3fv (const char *name, const float *p, size_t stride=0, size_t offset=0)
void attributearray4fv (const char *name, const float *p, size_t stride=0, size_t offset=0)
template<class T >
void attributearray1fv (int ind, const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void attributearray2fv (int ind, const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void attributearray3fv (int ind, const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void attributearray4fv (int ind, const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void attributearray1fv (const char *name, const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void attributearray2fv (const char *name, const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void attributearray3fv (const char *name, const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void attributearray4fv (const char *name, const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
void attributearray1fv (int ind, unsigned buf, size_t stride=0, size_t offset=0)
void attributearray2fv (int ind, unsigned buf, size_t stride=0, size_t offset=0)
void attributearray3fv (int ind, unsigned buf, size_t stride=0, size_t offset=0)
void attributearray4fv (int ind, unsigned buf, size_t stride=0, size_t offset=0)
void attributearray1fv (const char *name, unsigned buf, size_t stride=0, size_t offset=0)
void attributearray2fv (const char *name, unsigned buf, size_t stride=0, size_t offset=0)
void attributearray3fv (const char *name, unsigned buf, size_t stride=0, size_t offset=0)
void attributearray4fv (const char *name, unsigned buf, size_t stride=0, size_t offset=0)
void attribute1f (int ind, float x)
void attribute2f (int ind, float x, float y)
void attribute3f (int ind, float x, float y, float z)
void attribute4f (int ind, float x, float y, float z, float w)
void attribute1fv (int ind, const float *p)
void attribute2fv (int ind, const float *p)
void attribute3fv (int ind, const float *p)
void attribute4fv (int ind, const float *p)
void attribute1f (const char *name, float x)
void attribute2f (const char *name, float x, float y)
void attribute3f (const char *name, float x, float y, float z)
void attribute4f (const char *name, float x, float y, float z, float w)
void attribute1fv (const char *name, const float *p)
void attribute2fv (const char *name, const float *p)
void attribute3fv (const char *name, const float *p)
void attribute4fv (const char *name, const float *p)
void clear_attribute (int ind)
void clear_attribute (const char *name)
void clear_attributes ()
void vertexarray3fv (const float *p, size_t stride=0, size_t offset=0)
void normalarray3fv (const float *p, size_t stride=0, size_t offset=0)
void colorarray3fv (const float *p, size_t stride=0, size_t offset=0)
void colorarray4fv (const float *p, size_t stride=0, size_t offset=0)
void texcoordarray2fv (const float *p, size_t stride=0, size_t offset=0)
template<class T >
void vertexarray3fv (const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void normalarray3fv (const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void colorarray3fv (const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void colorarray4fv (const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
template<class T >
void texcoordarray2fv (const ::std::vector< T > &v, size_t stride=0, size_t offset=0)
void vertexarray3fv (unsigned buf, size_t stride=0, size_t offset=0)
void normalarray3fv (unsigned buf, size_t stride=0, size_t offset=0)
void colorarray3fv (unsigned buf, size_t stride=0, size_t offset=0)
void colorarray4fv (unsigned buf, size_t stride=0, size_t offset=0)
void texcoordarray2fv (unsigned buf, size_t stride=0, size_t offset=0)
void clear_vertexarray ()
void clear_normalarray ()
void clear_colorarray ()
void clear_texcoordarray ()
void normal3f (float nx, float ny, float nz)
void normal3fv (const float *p)
void color3f (float r, float g, float b)
void color3fv (const float *p)
void color4f (float r, float g, float b, float a)
void color4fv (const float *p)
void texcoord2f (float u, float v)
void texcoord2fv (const float *p)
unsigned make_buffer (const float *p, size_t nfloat)
template<class T >
unsigned make_buffer (const ::std::vector< T > &v)
void update_buffer (unsigned buf, const float *p, size_t nfloat)
template<class T >
void update_buffer (unsigned buf, const ::std::vector< T > &v)
bool use_buffer (unsigned buf=0)
bool use_buffer (const void *p)
template<class T >
bool use_buffer (const ::std::vector< T > &v)
void clear_buffer (unsigned buf)
void clear_buffer (const void *p)
template<class T >
void clear_buffer (const ::std::vector< T > &v)
void clear_buffers ()
unsigned make_ibuffer (const unsigned *p, size_t ninds)
unsigned make_ibuffer (const int *p, size_t ninds)
template<class T >
unsigned make_ibuffer (const ::std::vector< T > &v)
void update_ibuffer (unsigned buf, const unsigned *p, size_t ninds)
void update_ibuffer (unsigned buf, const int *p, size_t ninds)
template<class T >
void update_ibuffer (unsigned buf, const ::std::vector< T > &v)
bool use_ibuffer (unsigned buf=0)
bool use_ibuffer (const void *p)
template<class T >
bool use_ibuffer (const ::std::vector< T > &v)
void clear_ibuffer (unsigned buf)
void clear_ibuffer (const void *p)
template<class T >
void clear_ibuffer (const ::std::vector< T > &v)
void clear_ibuffers ()
void flip_textures (bool flip)
unsigned make_texture (int w, int h, const void *p, unsigned format=0x1907u, unsigned type=0x1401u, unsigned internalformat=0)
template<class T >
unsigned make_texture (int w, int h, const ::std::vector< T > &v, unsigned format=0x1907u, unsigned type=0x1401u, unsigned internalformat=0)
void update_texture (unsigned texind, int w, int h, const void *p, unsigned format=0x1907u, unsigned type=0x1401u, unsigned internalformat=0)
template<class T >
void update_texture (unsigned texind, int w, int h, const ::std::vector< T > &v, unsigned format=0x1907u, unsigned type=0x1401u, unsigned internalformat=0)
bool use_texture (unsigned texind=0)
bool use_texture (const void *p)
template<class T >
bool use_texture (const ::std::vector< T > &v)
void clear_texture (unsigned ind)
void clear_texture (const void *p)
template<class T >
void clear_texture (const ::std::vector< T > &v)
void clear_textures ()
void rendertarget (unsigned texind=0, unsigned depthbufferind=0)
bool shader_ready ()
void draw_points (size_t start, size_t npoints)
void draw_points (size_t npoints)
void draw_tris (const unsigned *p, size_t start, size_t ntris)
void draw_tris (const unsigned *p, size_t ntris)
void draw_tris (const int *p, size_t start, size_t ntris)
void draw_tris (const int *p, size_t ntris)
template<class T >
void draw_tris (const ::std::vector< T > &v)
template<class T >
void draw_tris (const ::std::vector< T > &v, size_t start, size_t ntris)
void draw_tris (size_t start, size_t ntris)
void draw_tris (int start, size_t ntris)
void draw_tris (size_t ntris)
void draw_tstrips (const unsigned *p, size_t start, size_t nstripinds)
void draw_tstrips (const unsigned *p, size_t nstripinds)
void draw_tstrips (const int *p, size_t start, size_t nstripinds)
void draw_tstrips (const int *p, size_t nstripinds)
template<class T >
void draw_tstrips (const ::std::vector< T > &v)
template<class T >
void draw_tstrips (const ::std::vector< T > &v, size_t start, size_t nstripinds)
void draw_tstrips (size_t start, size_t nstripinds)
void draw_tstrips (int start, size_t nstripinds)
void draw_tstrips (size_t nstripinds)
void clear ()
unsigned shader (const char *name, bool print_if_not_found=false)
int uniform (const char *name, bool print_if_not_found=false)
int attribute (const char *name, bool print_if_not_found=false)
unsigned buffer (const void *p, bool print_if_not_found=false)
template<class T >
unsigned buffer (const ::std::vector< T > &v, bool print_if_not_found=false)
unsigned ibuffer (const void *p, bool print_if_not_found=false)
template<class T >
unsigned ibuffer (const ::std::vector< T > &v, bool print_if_not_found=false)
unsigned texture (const void *p, bool print_if_not_found=false)
template<class T >
unsigned texture (const ::std::vector< T > &v, bool print_if_not_found=false)
float glversion ()
bool is_gles ()
bool extension_supported (const char *name)
bool have_primitive_restart ()
bool slow_tstrips ()
void set_error_hook (void(*hook)(const char *))
Constructor & Destructor Documentation
GLManager()
trimesh::GLManager::GLManager ()
~GLManager()
trimesh::GLManager::~GLManager ()
Member Function Documentation
attribute()
int trimesh::GLManager::attribute (const char * name, bool print_if_not_found = false)
Referenced by attribute1f(), attribute1fv(), attribute2f(), attribute2fv(), attribute3f(), attribute3fv(), attribute4f(), attribute4fv(), attributearray1fv(), attributearray2fv(), attributearray3fv(), attributearray4fv(), clear_attribute(), and draw_tstrips().
attribute1f() [1/2]
void trimesh::GLManager::attribute1f (int ind, float x)
Referenced by attribute1f(), and attributearray4fv().
attribute1f() [2/2]
void trimesh::GLManager::attribute1f (const char * name, float x) inline
attribute1fv() [1/2]
void trimesh::GLManager::attribute1fv (int ind, const float * p) inline
Referenced by attribute1fv().
attribute1fv() [2/2]
void trimesh::GLManager::attribute1fv (const char * name, const float * p) inline
attribute2f() [1/2]
void trimesh::GLManager::attribute2f (int ind, float x, float y)
Referenced by attribute2f(), and attributearray4fv().
attribute2f() [2/2]
void trimesh::GLManager::attribute2f (const char * name, float x, float y) inline
attribute2fv() [1/2]
void trimesh::GLManager::attribute2fv (int ind, const float * p) inline
Referenced by attribute2fv().
attribute2fv() [2/2]
void trimesh::GLManager::attribute2fv (const char * name, const float * p) inline
attribute3f() [1/2]
void trimesh::GLManager::attribute3f (int ind, float x, float y, float z)
Referenced by attribute3f(), and attributearray4fv().
attribute3f() [2/2]
void trimesh::GLManager::attribute3f (const char * name, float x, float y, float z) inline
attribute3fv() [1/2]
void trimesh::GLManager::attribute3fv (int ind, const float * p) inline
Referenced by attribute3fv().
attribute3fv() [2/2]
void trimesh::GLManager::attribute3fv (const char * name, const float * p) inline
attribute4f() [1/2]
void trimesh::GLManager::attribute4f (int ind, float x, float y, float z, float w)
Referenced by attribute4f(), and attributearray4fv().
attribute4f() [2/2]
void trimesh::GLManager::attribute4f (const char * name, float x, float y, float z, float w) inline
attribute4fv() [1/2]
void trimesh::GLManager::attribute4fv (int ind, const float * p) inline
Referenced by attribute4fv().
attribute4fv() [2/2]
void trimesh::GLManager::attribute4fv (const char * name, const float * p) inline
attributearray1fv() [1/6]
void trimesh::GLManager::attributearray1fv (int ind, const float * p, size_t stride = 0, size_t offset = 0) inline
Referenced by attributearray1fv().
attributearray1fv() [2/6]
void trimesh::GLManager::attributearray1fv (const char * name, const float * p, size_t stride = 0, size_t offset = 0) inline
attributearray1fv() [3/6]
template<class T > void trimesh::GLManager::attributearray1fv (int ind, const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
attributearray1fv() [4/6]
template<class T > void trimesh::GLManager::attributearray1fv (const char * name, const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
attributearray1fv() [5/6]
void trimesh::GLManager::attributearray1fv (int ind, unsigned buf, size_t stride = 0, size_t offset = 0) inline
attributearray1fv() [6/6]
void trimesh::GLManager::attributearray1fv (const char * name, unsigned buf, size_t stride = 0, size_t offset = 0) inline
attributearray2fv() [1/6]
void trimesh::GLManager::attributearray2fv (int ind, const float * p, size_t stride = 0, size_t offset = 0) inline
Referenced by attributearray2fv().
attributearray2fv() [2/6]
void trimesh::GLManager::attributearray2fv (const char * name, const float * p, size_t stride = 0, size_t offset = 0) inline
attributearray2fv() [3/6]
template<class T > void trimesh::GLManager::attributearray2fv (int ind, const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
attributearray2fv() [4/6]
template<class T > void trimesh::GLManager::attributearray2fv (const char * name, const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
attributearray2fv() [5/6]
void trimesh::GLManager::attributearray2fv (int ind, unsigned buf, size_t stride = 0, size_t offset = 0) inline
attributearray2fv() [6/6]
void trimesh::GLManager::attributearray2fv (const char * name, unsigned buf, size_t stride = 0, size_t offset = 0) inline
attributearray3fv() [1/6]
void trimesh::GLManager::attributearray3fv (int ind, const float * p, size_t stride = 0, size_t offset = 0) inline
Referenced by attributearray3fv().
attributearray3fv() [2/6]
void trimesh::GLManager::attributearray3fv (const char * name, const float * p, size_t stride = 0, size_t offset = 0) inline
attributearray3fv() [3/6]
template<class T > void trimesh::GLManager::attributearray3fv (int ind, const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
attributearray3fv() [4/6]
template<class T > void trimesh::GLManager::attributearray3fv (const char * name, const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
attributearray3fv() [5/6]
void trimesh::GLManager::attributearray3fv (int ind, unsigned buf, size_t stride = 0, size_t offset = 0) inline
attributearray3fv() [6/6]
void trimesh::GLManager::attributearray3fv (const char * name, unsigned buf, size_t stride = 0, size_t offset = 0) inline
attributearray4fv() [1/6]
void trimesh::GLManager::attributearray4fv (int ind, const float * p, size_t stride = 0, size_t offset = 0) inline
Referenced by attributearray4fv().
attributearray4fv() [2/6]
void trimesh::GLManager::attributearray4fv (const char * name, const float * p, size_t stride = 0, size_t offset = 0) inline
attributearray4fv() [3/6]
template<class T > void trimesh::GLManager::attributearray4fv (int ind, const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
attributearray4fv() [4/6]
template<class T > void trimesh::GLManager::attributearray4fv (const char * name, const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
attributearray4fv() [5/6]
void trimesh::GLManager::attributearray4fv (int ind, unsigned buf, size_t stride = 0, size_t offset = 0) inline
attributearray4fv() [6/6]
void trimesh::GLManager::attributearray4fv (const char * name, unsigned buf, size_t stride = 0, size_t offset = 0) inline
buffer() [1/2]
unsigned trimesh::GLManager::buffer (const void * p, bool print_if_not_found = false)
Referenced by buffer(), clear_buffer(), clear_ibuffer(), draw_tstrips(), and use_buffer().
buffer() [2/2]
template<class T > unsigned trimesh::GLManager::buffer (const ::std::vector< T > & v, bool print_if_not_found = false) inline
clear()
void trimesh::GLManager::clear ()
Referenced by draw_tstrips(), and ~GLManager().
clear_attribute() [1/2]
void trimesh::GLManager::clear_attribute (int ind)
Referenced by attribute4fv(), and clear_attribute().
clear_attribute() [2/2]
void trimesh::GLManager::clear_attribute (const char * name) inline
clear_attributes()
void trimesh::GLManager::clear_attributes ()
Referenced by clear_attribute().
clear_buffer() [1/3]
void trimesh::GLManager::clear_buffer (unsigned buf)
Referenced by clear_buffer(), clear_buffers(), and use_buffer().
clear_buffer() [2/3]
void trimesh::GLManager::clear_buffer (const void * p) inline
clear_buffer() [3/3]
template<class T > void trimesh::GLManager::clear_buffer (const ::std::vector< T > & v) inline
clear_buffers()
void trimesh::GLManager::clear_buffers ()
Referenced by clear(), and clear_buffer().
clear_colorarray()
void trimesh::GLManager::clear_colorarray ()
Referenced by clear_attributes(), and texcoordarray2fv().
clear_defines()
void trimesh::GLManager::clear_defines ()
Referenced by clear().
clear_ibuffer() [1/3]
void trimesh::GLManager::clear_ibuffer (unsigned buf)
Referenced by clear_ibuffer(), clear_ibuffers(), and use_ibuffer().
clear_ibuffer() [2/3]
void trimesh::GLManager::clear_ibuffer (const void * p) inline
clear_ibuffer() [3/3]
template<class T > void trimesh::GLManager::clear_ibuffer (const ::std::vector< T > & v) inline
clear_ibuffers()
void trimesh::GLManager::clear_ibuffers ()
Referenced by clear(), and clear_ibuffer().
clear_normalarray()
void trimesh::GLManager::clear_normalarray ()
Referenced by clear_attributes(), and texcoordarray2fv().
clear_shader() [1/2]
void trimesh::GLManager::clear_shader (unsigned ind)
Referenced by clear_shader(), clear_shaders(), and use_shader().
clear_shader() [2/2]
void trimesh::GLManager::clear_shader (const char * name) inline
clear_shaders()
void trimesh::GLManager::clear_shaders ()
Referenced by clear(), and clear_shader().
clear_texcoordarray()
void trimesh::GLManager::clear_texcoordarray ()
Referenced by clear_attributes(), and texcoordarray2fv().
clear_texture() [1/3]
void trimesh::GLManager::clear_texture (unsigned ind)
Referenced by clear_texture(), clear_textures(), and use_texture().
clear_texture() [2/3]
void trimesh::GLManager::clear_texture (const void * p) inline
clear_texture() [3/3]
template<class T > void trimesh::GLManager::clear_texture (const ::std::vector< T > & v) inline
clear_textures()
void trimesh::GLManager::clear_textures ()
Referenced by clear(), and clear_texture().
clear_uniform() [1/2]
void trimesh::GLManager::clear_uniform (int ind)
Referenced by clear_uniform(), and uniformTexture().
clear_uniform() [2/2]
void trimesh::GLManager::clear_uniform (const char * name) inline
clear_uniforms()
void trimesh::GLManager::clear_uniforms ()
Referenced by clear_uniform().
clear_vertexarray()
void trimesh::GLManager::clear_vertexarray ()
Referenced by clear_attributes(), and texcoordarray2fv().
color3f()
void trimesh::GLManager::color3f (float r, float g, float b)
Referenced by color3fv(), and normal3fv().
color3fv()
void trimesh::GLManager::color3fv (const float * p) inline
color4f()
void trimesh::GLManager::color4f (float r, float g, float b, float a)
Referenced by color3fv(), and color4fv().
color4fv()
void trimesh::GLManager::color4fv (const float * p) inline
colorarray3fv() [1/3]
void trimesh::GLManager::colorarray3fv (const float * p, size_t stride = 0, size_t offset = 0)
Referenced by clear_attribute(), colorarray3fv(), texcoordarray2fv(), and use_shader().
colorarray3fv() [2/3]
template<class T > void trimesh::GLManager::colorarray3fv (const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
colorarray3fv() [3/3]
void trimesh::GLManager::colorarray3fv (unsigned buf, size_t stride = 0, size_t offset = 0)
colorarray4fv() [1/3]
void trimesh::GLManager::colorarray4fv (const float * p, size_t stride = 0, size_t offset = 0)
Referenced by clear_attribute(), colorarray4fv(), texcoordarray2fv(), and use_shader().
colorarray4fv() [2/3]
template<class T > void trimesh::GLManager::colorarray4fv (const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
colorarray4fv() [3/3]
void trimesh::GLManager::colorarray4fv (unsigned buf, size_t stride = 0, size_t offset = 0)
define()
void trimesh::GLManager::define (const char * defname, const char * value)
draw_points() [1/2]
void trimesh::GLManager::draw_points (size_t start, size_t npoints)
Referenced by clear_texture(), and draw_points().
draw_points() [2/2]
void trimesh::GLManager::draw_points (size_t npoints) inline
draw_tris() [1/9]
void trimesh::GLManager::draw_tris (const unsigned * p, size_t start, size_t ntris)
Referenced by draw_points(), and draw_tris().
draw_tris() [2/9]
void trimesh::GLManager::draw_tris (const unsigned * p, size_t ntris) inline
draw_tris() [3/9]
void trimesh::GLManager::draw_tris (const int * p, size_t start, size_t ntris) inline
draw_tris() [4/9]
void trimesh::GLManager::draw_tris (const int * p, size_t ntris) inline
draw_tris() [5/9]
template<class T > void trimesh::GLManager::draw_tris (const ::std::vector< T > & v) inline
draw_tris() [6/9]
template<class T > void trimesh::GLManager::draw_tris (const ::std::vector< T > & v, size_t start, size_t ntris) inline
draw_tris() [7/9]
void trimesh::GLManager::draw_tris (size_t start, size_t ntris)
draw_tris() [8/9]
void trimesh::GLManager::draw_tris (int start, size_t ntris) inline
draw_tris() [9/9]
void trimesh::GLManager::draw_tris (size_t ntris) inline
draw_tstrips() [1/9]
void trimesh::GLManager::draw_tstrips (const unsigned * p, size_t start, size_t nstripinds)
Referenced by draw_points(), draw_tris(), and draw_tstrips().
draw_tstrips() [2/9]
void trimesh::GLManager::draw_tstrips (const unsigned * p, size_t nstripinds) inline
draw_tstrips() [3/9]
void trimesh::GLManager::draw_tstrips (const int * p, size_t start, size_t nstripinds) inline
draw_tstrips() [4/9]
void trimesh::GLManager::draw_tstrips (const int * p, size_t nstripinds) inline
draw_tstrips() [5/9]
template<class T > void trimesh::GLManager::draw_tstrips (const ::std::vector< T > & v) inline
draw_tstrips() [6/9]
template<class T > void trimesh::GLManager::draw_tstrips (const ::std::vector< T > & v, size_t start, size_t nstripinds) inline
draw_tstrips() [7/9]
void trimesh::GLManager::draw_tstrips (size_t start, size_t nstripinds)
draw_tstrips() [8/9]
void trimesh::GLManager::draw_tstrips (int start, size_t nstripinds) inline
draw_tstrips() [9/9]
void trimesh::GLManager::draw_tstrips (size_t nstripinds) inline
extension_supported()
bool trimesh::GLManager::extension_supported (const char * name)
Referenced by slow_tstrips(), and texture().
flip_textures()
void trimesh::GLManager::flip_textures (bool flip)
Referenced by clear_ibuffer().
glversion()
float trimesh::GLManager::glversion ()
Referenced by rendertarget(), slow_tstrips(), and texture().
have_primitive_restart()
bool trimesh::GLManager::have_primitive_restart ()
Referenced by slow_tstrips(), and texture().
ibuffer() [1/2]
unsigned trimesh::GLManager::ibuffer (const void * p, bool print_if_not_found = false)
Referenced by buffer(), ibuffer(), and use_ibuffer().
ibuffer() [2/2]
template<class T > unsigned trimesh::GLManager::ibuffer (const ::std::vector< T > & v, bool print_if_not_found = false) inline
is_gles()
bool trimesh::GLManager::is_gles ()
Referenced by slow_tstrips(), and texture().
make_buffer() [1/2]
unsigned trimesh::GLManager::make_buffer (const float * p, size_t nfloat)
Referenced by make_buffer(), and texcoord2fv().
make_buffer() [2/2]
template<class T > unsigned trimesh::GLManager::make_buffer (const ::std::vector< T > & v) inline
make_ibuffer() [1/3]
unsigned trimesh::GLManager::make_ibuffer (const unsigned * p, size_t ninds)
Referenced by clear_buffer(), and make_ibuffer().
make_ibuffer() [2/3]
unsigned trimesh::GLManager::make_ibuffer (const int * p, size_t ninds) inline
make_ibuffer() [3/3]
template<class T > unsigned trimesh::GLManager::make_ibuffer (const ::std::vector< T > & v) inline
make_shader()
unsigned trimesh::GLManager::make_shader (const char * name, const char * vert_text, const char * frag_text)
Referenced by make_shader_from_files().
make_shader_from_files()
unsigned trimesh::GLManager::make_shader_from_files (const char * name, const char * vert_filename, const char * frag_filename)
make_texture() [1/2]
unsigned trimesh::GLManager::make_texture (int w, int h, const void * p, unsigned format = 0x1907u, unsigned type = 0x1401u, unsigned internalformat = 0)
Referenced by clear_ibuffer(), and make_texture().
make_texture() [2/2]
template<class T > unsigned trimesh::GLManager::make_texture (int w, int h, const ::std::vector< T > & v, unsigned format = 0x1907u, unsigned type = 0x1401u, unsigned internalformat = 0) inline
normal3f()
void trimesh::GLManager::normal3f (float nx, float ny, float nz)
Referenced by normal3fv(), and texcoordarray2fv().
normal3fv()
void trimesh::GLManager::normal3fv (const float * p) inline
normalarray3fv() [1/3]
void trimesh::GLManager::normalarray3fv (const float * p, size_t stride = 0, size_t offset = 0)
Referenced by clear_attribute(), normalarray3fv(), texcoordarray2fv(), and use_shader().
normalarray3fv() [2/3]
template<class T > void trimesh::GLManager::normalarray3fv (const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
normalarray3fv() [3/3]
void trimesh::GLManager::normalarray3fv (unsigned buf, size_t stride = 0, size_t offset = 0)
rendertarget()
void trimesh::GLManager::rendertarget (unsigned texind = 0, unsigned depthbufferind = 0)
Referenced by clear_texture().
set_error_hook()
void trimesh::GLManager::set_error_hook (void(*)(const char *) hook)
Referenced by texture().
shader()
unsigned trimesh::GLManager::shader (const char * name, bool print_if_not_found = false)
Referenced by clear_shader(), draw_tstrips(), and use_shader().
shader_ready()
bool trimesh::GLManager::shader_ready ()
Referenced by clear_texture(), and draw_points().
slow_tstrips()
bool trimesh::GLManager::slow_tstrips ()
Referenced by texture().
texcoord2f()
void trimesh::GLManager::texcoord2f (float u, float v)
Referenced by color4fv(), and texcoord2fv().
texcoord2fv()
void trimesh::GLManager::texcoord2fv (const float * p) inline
texcoordarray2fv() [1/3]
void trimesh::GLManager::texcoordarray2fv (const float * p, size_t stride = 0, size_t offset = 0)
Referenced by clear_attribute(), texcoordarray2fv(), and use_shader().
texcoordarray2fv() [2/3]
template<class T > void trimesh::GLManager::texcoordarray2fv (const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
texcoordarray2fv() [3/3]
void trimesh::GLManager::texcoordarray2fv (unsigned buf, size_t stride = 0, size_t offset = 0)
texture() [1/2]
unsigned trimesh::GLManager::texture (const void * p, bool print_if_not_found = false)
Referenced by clear_texture(), ibuffer(), texture(), uniformTexture(), and use_texture().
texture() [2/2]
template<class T > unsigned trimesh::GLManager::texture (const ::std::vector< T > & v, bool print_if_not_found = false) inline
uniform()
int trimesh::GLManager::uniform (const char * name, bool print_if_not_found = false)
Referenced by clear_uniform(), draw_tstrips(), uniform1f(), uniform1fv(), uniform1i(), uniform1iv(), uniform2f(), uniform2fv(), uniform2i(), uniform2iv(), uniform3f(), uniform3fv(), uniform3i(), uniform3iv(), uniform4f(), uniform4fv(), uniform4i(), uniform4iv(), uniformMatrix2fv(), uniformMatrix3fv(), uniformMatrix4fv(), and uniformTexture().
uniform1f() [1/2]
void trimesh::GLManager::uniform1f (int ind, float x)
Referenced by attribute1fv(), uniform1f(), uniform1fv(), and uniform4iv().
uniform1f() [2/2]
void trimesh::GLManager::uniform1f (const char * name, float x) inline
uniform1fv() [1/2]
void trimesh::GLManager::uniform1fv (int ind, const float * p) inline
Referenced by uniform1fv().
uniform1fv() [2/2]
void trimesh::GLManager::uniform1fv (const char * name, const float * p) inline
uniform1i() [1/2]
void trimesh::GLManager::uniform1i (int ind, int x)
Referenced by clear_shader(), uniform1i(), and uniform1iv().
uniform1i() [2/2]
void trimesh::GLManager::uniform1i (const char * name, int x) inline
uniform1iv() [1/2]
void trimesh::GLManager::uniform1iv (int ind, const int * p) inline
Referenced by uniform1iv().
uniform1iv() [2/2]
void trimesh::GLManager::uniform1iv (const char * name, const int * p) inline
uniform2f() [1/2]
void trimesh::GLManager::uniform2f (int ind, float x, float y)
Referenced by attribute2fv(), uniform2f(), uniform2fv(), and uniform4iv().
uniform2f() [2/2]
void trimesh::GLManager::uniform2f (const char * name, float x, float y) inline
uniform2fv() [1/2]
void trimesh::GLManager::uniform2fv (int ind, const float * p) inline
Referenced by uniform2fv().
uniform2fv() [2/2]
void trimesh::GLManager::uniform2fv (const char * name, const float * p) inline
uniform2i() [1/2]
void trimesh::GLManager::uniform2i (int ind, int x, int y)
Referenced by clear_shader(), uniform2i(), and uniform2iv().
uniform2i() [2/2]
void trimesh::GLManager::uniform2i (const char * name, int x, int y) inline
uniform2iv() [1/2]
void trimesh::GLManager::uniform2iv (int ind, const int * p) inline
Referenced by uniform2iv().
uniform2iv() [2/2]
void trimesh::GLManager::uniform2iv (const char * name, const int * p) inline
uniform3f() [1/2]
void trimesh::GLManager::uniform3f (int ind, float x, float y, float z)
Referenced by attribute3fv(), uniform3f(), uniform3fv(), and uniform4iv().
uniform3f() [2/2]
void trimesh::GLManager::uniform3f (const char * name, float x, float y, float z) inline
uniform3fv() [1/2]
void trimesh::GLManager::uniform3fv (int ind, const float * p) inline
Referenced by uniform3fv().
uniform3fv() [2/2]
void trimesh::GLManager::uniform3fv (const char * name, const float * p) inline
uniform3i() [1/2]
void trimesh::GLManager::uniform3i (int ind, int x, int y, int z)
Referenced by clear_shader(), uniform3i(), and uniform3iv().
uniform3i() [2/2]
void trimesh::GLManager::uniform3i (const char * name, int x, int y, int z) inline
uniform3iv() [1/2]
void trimesh::GLManager::uniform3iv (int ind, const int * p) inline
Referenced by uniform3iv().
uniform3iv() [2/2]
void trimesh::GLManager::uniform3iv (const char * name, const int * p) inline
uniform4f() [1/2]
void trimesh::GLManager::uniform4f (int ind, float x, float y, float z, float w)
Referenced by attribute4fv(), uniform4f(), uniform4fv(), and uniform4iv().
uniform4f() [2/2]
void trimesh::GLManager::uniform4f (const char * name, float x, float y, float z, float w) inline
uniform4fv() [1/2]
void trimesh::GLManager::uniform4fv (int ind, const float * p) inline
Referenced by uniform4fv().
uniform4fv() [2/2]
void trimesh::GLManager::uniform4fv (const char * name, const float * p) inline
uniform4i() [1/2]
void trimesh::GLManager::uniform4i (int ind, int x, int y, int z, int w)
Referenced by clear_shader(), uniform4i(), and uniform4iv().
uniform4i() [2/2]
void trimesh::GLManager::uniform4i (const char * name, int x, int y, int z, int w) inline
uniform4iv() [1/2]
void trimesh::GLManager::uniform4iv (int ind, const int * p) inline
Referenced by uniform4iv().
uniform4iv() [2/2]
void trimesh::GLManager::uniform4iv (const char * name, const int * p) inline
uniformMatrix2fv() [1/2]
void trimesh::GLManager::uniformMatrix2fv (int ind, const float * p)
Referenced by uniform4fv(), and uniformMatrix2fv().
uniformMatrix2fv() [2/2]
void trimesh::GLManager::uniformMatrix2fv (const char * name, const float * p) inline
uniformMatrix3fv() [1/2]
void trimesh::GLManager::uniformMatrix3fv (int ind, const float * p)
Referenced by uniform4fv(), and uniformMatrix3fv().
uniformMatrix3fv() [2/2]
void trimesh::GLManager::uniformMatrix3fv (const char * name, const float * p) inline
uniformMatrix4fv() [1/2]
void trimesh::GLManager::uniformMatrix4fv (int ind, const float * p)
Referenced by uniform4fv(), and uniformMatrix4fv().
uniformMatrix4fv() [2/2]
void trimesh::GLManager::uniformMatrix4fv (const char * name, const float * p) inline
uniformTexture() [1/6]
void trimesh::GLManager::uniformTexture (int ind, unsigned texind)
Referenced by uniform4fv(), and uniformTexture().
uniformTexture() [2/6]
void trimesh::GLManager::uniformTexture (int ind, const void * p) inline
uniformTexture() [3/6]
template<class T > void trimesh::GLManager::uniformTexture (int ind, const ::std::vector< T > & v) inline
uniformTexture() [4/6]
void trimesh::GLManager::uniformTexture (const char * name, unsigned texind) inline
uniformTexture() [5/6]
void trimesh::GLManager::uniformTexture (const char * name, const void * p) inline
uniformTexture() [6/6]
template<class T > void trimesh::GLManager::uniformTexture (const char * name, const ::std::vector< T > & v) inline
update_buffer() [1/2]
void trimesh::GLManager::update_buffer (unsigned buf, const float * p, size_t nfloat)
Referenced by make_buffer(), and update_buffer().
update_buffer() [2/2]
template<class T > void trimesh::GLManager::update_buffer (unsigned buf, const ::std::vector< T > & v) inline
update_ibuffer() [1/3]
void trimesh::GLManager::update_ibuffer (unsigned buf, const unsigned * p, size_t ninds)
Referenced by make_ibuffer(), and update_ibuffer().
update_ibuffer() [2/3]
void trimesh::GLManager::update_ibuffer (unsigned buf, const int * p, size_t ninds) inline
update_ibuffer() [3/3]
template<class T > void trimesh::GLManager::update_ibuffer (unsigned buf, const ::std::vector< T > & v) inline
update_texture() [1/2]
void trimesh::GLManager::update_texture (unsigned texind, int w, int h, const void * p, unsigned format = 0x1907u, unsigned type = 0x1401u, unsigned internalformat = 0)
Referenced by make_texture(), and update_texture().
update_texture() [2/2]
template<class T > void trimesh::GLManager::update_texture (unsigned texind, int w, int h, const ::std::vector< T > & v, unsigned format = 0x1907u, unsigned type = 0x1401u, unsigned internalformat = 0) inline
use_buffer() [1/3]
bool trimesh::GLManager::use_buffer (unsigned buf = 0)
Referenced by clear_buffer(), clear_buffers(), colorarray3fv(), colorarray4fv(), normalarray3fv(), texcoordarray2fv(), update_buffer(), use_buffer(), and vertexarray3fv().
use_buffer() [2/3]
bool trimesh::GLManager::use_buffer (const void * p) inline
use_buffer() [3/3]
template<class T > bool trimesh::GLManager::use_buffer (const ::std::vector< T > & v) inline
use_ibuffer() [1/3]
bool trimesh::GLManager::use_ibuffer (unsigned buf = 0)
Referenced by clear_ibuffer(), clear_ibuffers(), update_ibuffer(), and use_ibuffer().
use_ibuffer() [2/3]
bool trimesh::GLManager::use_ibuffer (const void * p) inline
use_ibuffer() [3/3]
template<class T > bool trimesh::GLManager::use_ibuffer (const ::std::vector< T > & v) inline
use_shader() [1/2]
bool trimesh::GLManager::use_shader (unsigned ind = 0)
Referenced by clear_shader(), clear_shaders(), make_shader(), and use_shader().
use_shader() [2/2]
bool trimesh::GLManager::use_shader (const char * name) inline
use_texture() [1/3]
bool trimesh::GLManager::use_texture (unsigned texind = 0)
Referenced by clear_texture(), clear_textures(), uniformTexture(), update_texture(), and use_texture().
use_texture() [2/3]
bool trimesh::GLManager::use_texture (const void * p) inline
use_texture() [3/3]
template<class T > bool trimesh::GLManager::use_texture (const ::std::vector< T > & v) inline
vertexarray3fv() [1/3]
void trimesh::GLManager::vertexarray3fv (const float * p, size_t stride = 0, size_t offset = 0)
Referenced by clear_attribute(), texcoordarray2fv(), use_shader(), and vertexarray3fv().
vertexarray3fv() [2/3]
template<class T > void trimesh::GLManager::vertexarray3fv (const ::std::vector< T > & v, size_t stride = 0, size_t offset = 0) inline
vertexarray3fv() [3/3]
void trimesh::GLManager::vertexarray3fv (unsigned buf, size_t stride = 0, size_t offset = 0)
The documentation for this class was generated from the following files:
GLManager.h
GLManager.cc