Symmetric NDT: cost_functors.h File Reference
cost_functors.h File Reference
#include <ceres/ceres.h>
#include <Eigen/Dense>
#include <sndt/ndt_cell.h>
#include <sndt/sndt_cell.h>
Classes
class AngleLocalParameterization
struct SICPCostFunctor
struct NDTD2DCostFunctor
struct SNDTCostFunctor
Functions
template<typename T >
Eigen::Matrix< T, 2, 2 > RotationMatrix2D (T yaw)
Function Documentation
RotationMatrix2D()
template<typename T > Eigen::Matrix<T, 2, 2> RotationMatrix2D (T yaw)
Referenced by SICPCostFunctor::operator()(), NDTD2DCostFunctor::operator()(), and SNDTCostFunctor::operator()().