Symmetric NDT: trimesh::Color Class Reference
trimesh::Color Class Reference
#include <Color.h>
Public Types
enum Colorspace {
CIELAB, XYZ, RGB, SRGB,
YCBCR, HSV
}
Public Types inherited from trimesh::Vec< 3, float >
typedef float value_type
typedef value_type * pointer
typedef const value_type * const_pointer
typedef value_type & reference
typedef const value_type & const_reference
typedef value_type * iterator
typedef const value_type * const_iterator
typedef ::std::reverse_iterator< iterator > reverse_iterator
typedef ::std::reverse_iterator< const_iterator > const_reverse_iterator
typedef ::std::size_t size_type
typedef ::std::ptrdiff_t difference_type
typedef ::std::conditional< ::std::is_integral< float >::value, double, float >::type float_type
Public Member Functions
Color ()
Color (const Vec< 3, float > &v_)
Color (const Vec< 3, double > &v_)
Color (float r_, float g_, float b_)
Color (double r_, double g_, double b_)
Color (const float *rgb)
Color (const double *rgb)
Color (float c)
Color (double c)
Color & operator= (float c)
Color & operator= (double c)
Color (int r_, int g_, int b_)
Color (const int *rgb)
Color (const unsigned char *rgb)
Color (int c)
Color & operator= (int c)
const Color col_transform (float m11, float m12, float m13, float m21, float m22, float m23, float m31, float m32, float m33) const
const Color convert (Colorspace src, Colorspace dst) const
const Color gamma (float g_) const
const Color gamma (Colorspace dst) const
const Color ungamma (float g_) const
const Color ungamma (Colorspace dst) const
Public Member Functions inherited from trimesh::Vec< 3, float >
Vec ()
Vec (Vec_uninitialized *)
Vec (const float &x_, const float &y_)
Vec (const float &x_, const float &y_, const float &z_)
Vec (const float &x_, const float &y_, const float &z_, const float &w_)
Vec (S x_, typename ::std::enable_if< ::std::is_arithmetic< S >::value, void >::type *=0)
Vec (const S &v_, typename ::std::enable_if< !::std::is_arithmetic< S >::value, void >::type *=0)
typename ::std::enable_if< ::std::is_arithmetic< S >::value, Vec & >::type operator= (S x_)
typename ::std::enable_if< !::std::is_arithmetic< S >::value, Vec & >::type operator= (const S &v_)
reference operator[] (size_type i)
reference operator[] (int i)
const_reference operator[] (size_type i) const
const_reference operator[] (int i) const
reference at (size_type i)
const_reference at (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
operator float * ()
operator const float * ()
operator const float * () const
pointer data ()
const_pointer data () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
size_type size () const
size_type max_size () const
TRIMESH_DEPRECATED bool empty () const
void clear ()
void fill (const value_type &x_)
void set (const value_type &x_)
void set (const float &x_, const float &y_)
void set (const float &x_, const float &y_, const float &z_)
void set (const float &x_, const float &y_, const float &z_, const float &w_)
Vec & operator+= (const Vec &v_)
Vec & operator+= (const float &x_)
Vec & operator-= (const Vec &v_)
Vec & operator-= (const float &x_)
Vec & operator*= (const Vec &v_)
Vec & operator*= (const float &x_)
Vec & operator/= (const Vec &v_)
Vec & operator/= (const float &x_)
Vec & min (const Vec &v_)
Vec & min (const float &x_)
value_type min () const
Vec & max (const Vec &v_)
Vec & max (const float &x_)
value_type max () const
Vec & clamp (const Vec &a, const Vec &b)
Vec & clamp (const float &a, const float &b)
void swap (Vec &v_)
value_type dot (const Vec &v_) const
Vec< 3, float > cross (const Vec< 3, float > &v_) const
value_type sum () const
value_type sumabs () const
value_type sumsqr () const
float_type avg () const
float_type avgabs () const
float_type mean () const
float_type meanabs () const
float_type rms () const
value_type product () const
value_type minabs () const
value_type maxabs () const
Vec apply (value_type func(value_type)) const
Vec apply (value_type func(const value_type &)) const
Vec cshift (int n) const
Vec shift (int n) const
int indexof (const float &x_) const
Static Public Member Functions
static Color black ()
static Color white ()
static Color red ()
static Color green ()
static Color blue ()
static Color yellow ()
static Color cyan ()
static Color magenta ()
static Color orange ()
static Color hsv (float H, float S, float V)
Static Public Member Functions inherited from trimesh::Vec< 3, float >
static Vec< D, float > uniform_rnd (float sigma=1)
static Vec< D, float > normal_rnd (float sigma=1)
Additional Inherited Members
Public Attributes inherited from trimesh::Vec_data< D, float >
float v [D]
Member Enumeration Documentation
Colorspace
enum trimesh::Color::Colorspace
Enumerator
CIELAB
XYZ
RGB
SRGB
YCBCR
HSV
Constructor & Destructor Documentation
Color() [1/13]
trimesh::Color::Color () inline
Referenced by black(), blue(), col_transform(), Color(), convert(), cyan(), gamma(), green(), hsv(), magenta(), operator=(), orange(), red(), ungamma(), white(), and yellow().
Color() [2/13]
trimesh::Color::Color (const Vec< 3, float > & v_) inline
Color() [3/13]
trimesh::Color::Color (const Vec< 3, double > & v_) inline
Color() [4/13]
trimesh::Color::Color (float r_, float g_, float b_) inline
Color() [5/13]
trimesh::Color::Color (double r_, double g_, double b_) inline
Color() [6/13]
trimesh::Color::Color (const float * rgb) inline explicit
Color() [7/13]
trimesh::Color::Color (const double * rgb) inline explicit
Color() [8/13]
trimesh::Color::Color (float c) inline explicit
Color() [9/13]
trimesh::Color::Color (double c) inline explicit
Color() [10/13]
trimesh::Color::Color (int r_, int g_, int b_) inline
Color() [11/13]
trimesh::Color::Color (const int * rgb) inline explicit
Color() [12/13]
trimesh::Color::Color (const unsigned char * rgb) inline explicit
Color() [13/13]
trimesh::Color::Color (int c) inline explicit
Member Function Documentation
black()
static Color trimesh::Color::black () inline static
blue()
static Color trimesh::Color::blue () inline static
col_transform()
const Color trimesh::Color::col_transform (float m11, float m12, float m13, float m21, float m22, float m23, float m31, float m32, float m33) const inline
convert()
const Color trimesh::Color::convert (Colorspace src, Colorspace dst) const inline
Referenced by convert().
cyan()
static Color trimesh::Color::cyan () inline static
gamma() [1/2]
const Color trimesh::Color::gamma (float g_) const inline
gamma() [2/2]
const Color trimesh::Color::gamma (Colorspace dst) const inline
green()
static Color trimesh::Color::green () inline static
hsv()
static Color trimesh::Color::hsv (float H, float S, float V) inline static
Referenced by convert().
magenta()
static Color trimesh::Color::magenta () inline static
operator=() [1/3]
Color& trimesh::Color::operator= (float c) inline
operator=() [2/3]
Color& trimesh::Color::operator= (double c) inline
operator=() [3/3]
Color& trimesh::Color::operator= (int c) inline
orange()
static Color trimesh::Color::orange () inline static
red()
static Color trimesh::Color::red () inline static
ungamma() [1/2]
const Color trimesh::Color::ungamma (float g_) const inline
ungamma() [2/2]
const Color trimesh::Color::ungamma (Colorspace dst) const inline
white()
static Color trimesh::Color::white () inline static
yellow()
static Color trimesh::Color::yellow () inline static
The documentation for this class was generated from the following file:
Color.h