Symmetric NDT: wrapper.hpp File Reference
sndt_exec/include/sndt_exec/wrapper.hpp File Reference
#include <bits/stdc++.h>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/search/kdtree.h>
#include "common/common.h"
#include "sndt/ndt_matcher.h"
#include "normal2d/Normal2dEstimation.h"
Typedefs
typedef pcl::PointCloud< pcl::PointXYZ > PCXYZ
typedef pcl::PointCloud< pcl::PointXYZ >::Ptr PCXYZPtr
Functions
MatrixXd MatrixXdFromPCL (PCXYZ pc)
MatrixXd MatrixXdFromPCL (PCXYZPtr pc)
PCXYZPtr PCLFromMatrixXd (const MatrixXd &mtx)
void DoSNDT (common::MatchPackage &mp, common::MatchInternal &mit, const vector< double > &params)
Wrapper of SNDT.
NDTMap MakeMap (const vector< pair< MatrixXd, Affine2d >> &data, const Vector2d &intrinsic, const vector< double > &params)
Typedef Documentation
PCXYZ
typedef pcl::PointCloud<pcl::PointXYZ> PCXYZ
PCXYZPtr
typedef pcl::PointCloud<pcl::PointXYZ>::Ptr PCXYZPtr
Function Documentation
DoSNDT()
void DoSNDT (common::MatchPackage & mp, common::MatchInternal & mit, const vector< double > & params)
Wrapper of SNDT.
Parameters
mp
mit
params
MakeMap()
NDTMap MakeMap (const vector< pair< MatrixXd, Affine2d >> & data, const Vector2d & intrinsic, const vector< double > & params)
Parameters
data MatrixXd 2xN & Affine2d
point_intrinsic variance (r_sig^2, theta_sig^2)
params (cell_size, radius)
Referenced by cb(), and main().
MatrixXdFromPCL() [1/2]
MatrixXd MatrixXdFromPCL (PCXYZ pc)
Referenced by MatrixXdFromPCL().
MatrixXdFromPCL() [2/2]
MatrixXd MatrixXdFromPCL (PCXYZPtr pc)
PCLFromMatrixXd()
PCXYZPtr PCLFromMatrixXd (const MatrixXd & mtx)
Referenced by DoSNDT().