Symmetric NDT: ego.cc File Reference
ego.cc File Reference
#include <bits/stdc++.h>
#include <conti_radar/Measurement.h>
#include <geometry_msgs/Twist.h>
#include <message_filters/subscriber.h>
#include <message_filters/sync_policies/approximate_time.h>
#include <message_filters/time_synchronizer.h>
#include <nav_msgs/Odometry.h>
#include <pcl/PCLPointCloud2.h>
#include <pcl/filters/filter.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/sample_consensus/ransac.h>
#include <pcl/sample_consensus/sac_model_plane.h>
#include <pcl/sample_consensus/sac_model_sphere.h>
#include <pcl_ros/point_cloud.h>
#include <pcl_ros/transforms.h>
#include <ros/ros.h>
#include <sensor_msgs/PointCloud2.h>
#include <tf2_eigen/tf2_eigen.h>
#include <boost/program_options.hpp>
#include <common/EgoPointClouds.h>
#include <common/common.h>
Typedefs
typedef message_filters::sync_policies::ApproximateTime< conti_radar::Measurement, conti_radar::Measurement, conti_radar::Measurement, conti_radar::Measurement, conti_radar::Measurement > NoCloudSyncPolicy
Functions
sensor_msgs::PointCloud2 conti_to_rospc (const conti_radar::Measurement &msg)
void SystemMotion (string id, const conti_radar::MeasurementConstPtr &input, MatrixXd &Rj, VectorXd &VDj)
vector< int > InliersAfterRANSAC (const MatrixXd &R, const VectorXd &VD, double threshold)
MatrixXd PreserveRows (const MatrixXd &mtx, const vector< int > &cols)
Matrix3d ComputeCovariance (const MatrixXd &RANSAC_R, const MatrixXd &RANSAC_VD, const Vector3d &ego_mat)
nav_msgs::Odometry MakeOdom (double time, const Vector3d &ego_mat, const Matrix3d &cov_mat)
conti_radar::Measurement ContiMsg (const conti_radar::MeasurementConstPtr &input, const vector< int > &indices)
conti_radar::Measurement ContiMsgComp (string id, const conti_radar::MeasurementConstPtr &input, const vector< int > &indices, const Vector3d &ego_mat)
Matrix4d GetTransform (const Vector3d &xyt)
vector< geometry_msgs::Point > ToGeometryMsgs (const sensor_msgs::PointCloud2 &msg)
common::PointCloudSensor MakePointCloudSensor (string frame_id, const Matrix4d &origin, const sensor_msgs::PointCloud2 &pc, sensor_msgs::PointCloud2 &augpc)
void Callback (const conti_radar::MeasurementConstPtr &f_input, const conti_radar::MeasurementConstPtr &fl_input, const conti_radar::MeasurementConstPtr &fr_input, const conti_radar::MeasurementConstPtr &bl_input, const conti_radar::MeasurementConstPtr &br_input)
void savecb (const std_msgs::Empty::ConstPtr &msg)
void PreComputeSystem ()
int main (int argc, char **argv)
Variables
ros::Publisher pub
ros::Publisher pub_pc
ros::Publisher f_outlier_pub
ros::Publisher fr_outlier_pub
ros::Publisher fl_outlier_pub
ros::Publisher br_outlier_pub
ros::Publisher bl_outlier_pub
ros::Publisher f_inlier_pub
ros::Publisher fr_inlier_pub
ros::Publisher fl_inlier_pub
ros::Publisher br_inlier_pub
ros::Publisher bl_inlier_pub
vector< common::EgoPointClouds > vepcs
string outpath
unordered_map< string, ros::Publisher > publishers
unordered_map< string, Vector3d > sensor_origins
unordered_map< string, Matrix4d > sensor_tfs
unordered_map< string, Matrix< double, 2, 3 > > S
Typedef Documentation
NoCloudSyncPolicy
typedef message_filters::sync_policies::ApproximateTime< conti_radar::Measurement, conti_radar::Measurement, conti_radar::Measurement, conti_radar::Measurement, conti_radar::Measurement> NoCloudSyncPolicy
Function Documentation
Callback()
void Callback (const conti_radar::MeasurementConstPtr & f_input, const conti_radar::MeasurementConstPtr & fl_input, const conti_radar::MeasurementConstPtr & fr_input, const conti_radar::MeasurementConstPtr & bl_input, const conti_radar::MeasurementConstPtr & br_input)
Referenced by main().
ComputeCovariance()
Matrix3d ComputeCovariance (const MatrixXd & RANSAC_R, const MatrixXd & RANSAC_VD, const Vector3d & ego_mat)
Referenced by Callback().
conti_to_rospc()
sensor_msgs::PointCloud2 conti_to_rospc (const conti_radar::Measurement & msg)
Referenced by Callback().
ContiMsg()
conti_radar::Measurement ContiMsg (const conti_radar::MeasurementConstPtr & input, const vector< int > & indices)
Referenced by Callback().
ContiMsgComp()
conti_radar::Measurement ContiMsgComp (string id, const conti_radar::MeasurementConstPtr & input, const vector< int > & indices, const Vector3d & ego_mat)
Referenced by Callback().
GetTransform()
Matrix4d GetTransform (const Vector3d & xyt)
Referenced by Callback(), and PreComputeSystem().
InliersAfterRANSAC()
vector<int> InliersAfterRANSAC (const MatrixXd & R, const VectorXd & VD, double threshold)
Referenced by Callback().
main()
int main (int argc, char ** argv)
MakeOdom()
nav_msgs::Odometry MakeOdom (double time, const Vector3d & ego_mat, const Matrix3d & cov_mat)
Referenced by Callback().
MakePointCloudSensor()
common::PointCloudSensor MakePointCloudSensor (string frame_id, const Matrix4d & origin, const sensor_msgs::PointCloud2 & pc, sensor_msgs::PointCloud2 & augpc)
Referenced by Callback().
PreComputeSystem()
void PreComputeSystem ()
Referenced by main().
PreserveRows()
MatrixXd PreserveRows (const MatrixXd & mtx, const vector< int > & cols)
Referenced by Callback().
savecb()
void savecb (const std_msgs::Empty::ConstPtr & msg)
Referenced by main().
SystemMotion()
void SystemMotion (string id, const conti_radar::MeasurementConstPtr & input, MatrixXd & Rj, VectorXd & VDj)
Referenced by Callback().
ToGeometryMsgs()
vector<geometry_msgs::Point> ToGeometryMsgs (const sensor_msgs::PointCloud2 & msg)
Referenced by Callback(), and MakePointCloudSensor().
Variable Documentation
bl_inlier_pub
ros::Publisher bl_inlier_pub
bl_outlier_pub
ros::Publisher bl_outlier_pub
br_inlier_pub
ros::Publisher br_inlier_pub
br_outlier_pub
ros::Publisher br_outlier_pub
f_inlier_pub
ros::Publisher f_inlier_pub
f_outlier_pub
ros::Publisher f_outlier_pub
fl_inlier_pub
ros::Publisher fl_inlier_pub
fl_outlier_pub
ros::Publisher fl_outlier_pub
fr_inlier_pub
ros::Publisher fr_inlier_pub
fr_outlier_pub
ros::Publisher fr_outlier_pub
outpath
string outpath
Referenced by main(), and savecb().
pub
ros::Publisher pub
Referenced by Callback(), and main().
pub_pc
ros::Publisher pub_pc
Referenced by Callback(), and main().
publishers
unordered_map<string, ros::Publisher> publishers
Referenced by Callback(), and main().
S
unordered_map<string, Matrix<double, 2, 3> > S
Referenced by ContiMsgComp(), MakeNDTMap(), MakeSNDTMap(), PreComputeSystem(), and SystemMotion().
sensor_origins
unordered_map<string, Vector3d> sensor_origins
Referenced by ContiMsgComp(), main(), PreComputeSystem(), and SystemMotion().
sensor_tfs
unordered_map<string, Matrix4d> sensor_tfs
Referenced by Callback(), and PreComputeSystem().
vepcs
vector<common::EgoPointClouds> vepcs
Referenced by Callback(), main(), and savecb().