Symmetric NDT: trimesh::Basis< D, T > Class Template Reference
trimesh::Basis< D, T > Class Template Reference
#include <bsphere.h>
Public Member Functions
const T * center () const
T squared_radius () const
size_t size () const
T excess (const Vec< D, T > &p) const
void reset ()
bool push (const Vec< D, T > &p)
void pop ()
Member Function Documentation
center()
template<size_t D, class T> const T* trimesh::Basis< D, T >::center () const inline
Referenced by trimesh::Miniball< D, T >::center().
excess()
template<size_t D, class T > T trimesh::Basis< D, T >::excess (const Vec< D, T > & p) const
Referenced by trimesh::Basis< D, T >::size().
pop()
template<size_t D, class T > void trimesh::Basis< D, T >::pop ()
Referenced by trimesh::Basis< D, T >::size().
push()
template<size_t D, class T > bool trimesh::Basis< D, T >::push (const Vec< D, T > & p)
Referenced by trimesh::Basis< D, T >::size().
reset()
template<size_t D, class T > void trimesh::Basis< D, T >::reset ()
Referenced by trimesh::Basis< D, T >::size().
size()
template<size_t D, class T> size_t trimesh::Basis< D, T >::size () const inline
squared_radius()
template<size_t D, class T> T trimesh::Basis< D, T >::squared_radius () const inline
Referenced by trimesh::Miniball< D, T >::squared_radius().
The documentation for this class was generated from the following file:
bsphere.h