Symmetric NDT: ndt_map.cc File Reference
ndt_map.cc File Reference
#include "sndt/ndt_map.h"
#include <bits/stdc++.h>
#include <pcl/point_types.h>
#include <pcl/search/kdtree.h>
#include <Eigen/Dense>
#include <gsl/gsl>
#include "normal2d/Normal2dEstimation.h"
Typedefs
typedef pcl::PointCloud< pcl::PointXYZ > PCXYZ
typedef pcl::PointCloud< pcl::PointXYZ >::Ptr PCXYZPtr
typedef pcl::PointCloud< pcl::PointXY > PCXY
typedef pcl::PointCloud< pcl::PointXY >::Ptr PCXYPtr
Functions
PCXY ToPCLXY (const PCXYZ &pc)
PCXYZ ToPCLXYZ (const PCXY &pc)
PCXYZPtr ComputeNormals (PCXYZPtr pc, double radius)
MatrixXd ComputeNormals2 (const MatrixXd &pc, double radius)
Typedef Documentation
PCXY
typedef pcl::PointCloud<pcl::PointXY> PCXY
PCXYPtr
typedef pcl::PointCloud<pcl::PointXY>::Ptr PCXYPtr
PCXYZ
typedef pcl::PointCloud<pcl::PointXYZ> PCXYZ
PCXYZPtr
typedef pcl::PointCloud<pcl::PointXYZ>::Ptr PCXYZPtr
Function Documentation
ComputeNormals()
PCXYZPtr ComputeNormals (PCXYZPtr pc, double radius)
Referenced by NDTMap::LoadPointCloud().
ComputeNormals2()
MatrixXd ComputeNormals2 (const MatrixXd & pc, double radius)
Referenced by MakeMap().
ToPCLXY()
PCXY ToPCLXY (const PCXYZ & pc)
Referenced by NDTMap::LoadPointCloud().
ToPCLXYZ()
PCXYZ ToPCLXYZ (const PCXY & pc)