Symmetric NDT: trimesh::XForm< T > Class Template Reference
trimesh::XForm< T > Class Template Reference
#include <XForm.h>
Public Types
typedef T value_type
typedef value_type * pointer
typedef const value_type * const_pointer
typedef value_type & reference
typedef const value_type & const_reference
typedef value_type * iterator
typedef const value_type * const_iterator
typedef ::std::reverse_iterator< iterator > reverse_iterator
typedef ::std::reverse_iterator< const_iterator > const_reverse_iterator
typedef ::std::size_t size_type
typedef ::std::ptrdiff_t difference_type
Public Member Functions
XForm (const T m0=1, const T m1=0, const T m2=0, const T m3=0, const T m4=0, const T m5=1, const T m6=0, const T m7=0, const T m8=0, const T m9=0, const T m10=1, const T m11=0, const T m12=0, const T m13=0, const T m14=0, const T m15=1)
template<class S >
XForm (S x, typename ::std::enable_if< ::std::is_arithmetic< S >::value, void >::type *=0)
template<class S >
XForm (const S &x)
template<class S >
XForm & operator= (const S &x)
reference operator[] (size_type i)
reference operator[] (int i)
const_reference operator[] (size_type i) const
const_reference operator[] (int i) const
reference operator() (size_type r, size_type c)
reference operator() (int r, int c)
const_reference operator() (size_type r, size_type c) const
const_reference operator() (int r, int c) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
operator T* ()
operator const T * ()
operator const T * () const
pointer data ()
const_pointer data () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
size_type size () const
size_type max_size () const
bool read (const ::std::string &filename)
bool write (const ::std::string &filename) const
Static Public Member Functions
static XForm< T > identity ()
static XForm< T > trans (const T &tx, const T &ty, const T &tz)
template<class S >
static XForm< T > trans (const S &t)
static XForm< T > rot (const T &angle, const T &rx, const T &ry, const T &rz)
template<class S >
static XForm< T > rot (const T &angle, const S &axis)
static XForm< T > rot_into (T d1x, T d1y, T d1z, T d2x, T d2y, T d2z)
template<class S >
static XForm< T > rot_into (const S &d1, const S &d2)
static XForm< T > scale (const T &s)
static XForm< T > scale (const T &sx, const T &sy, const T &sz)
static XForm< T > scale (const T &s, const T &dx, const T &dy, const T &dz)
template<class S >
static XForm< T > scale (const T &s, const S &dir)
static XForm< T > ortho (const T &l, const T &r, const T &b, const T &t, const T &n, const T &f)
static XForm< T > frustum (const T &l, const T &r, const T &b, const T &t, const T &n, const T &f)
template<class S >
static XForm< T > outer (const S &y, const S &x)
template<class S >
static XForm< T > fromarray (const S x[3][3])
template<class S >
static XForm< T > fromarray (const S x[4][4])
Protected Attributes
T m [16]
Member Typedef Documentation
const_iterator
template<class T> typedef const value_type* trimesh::XForm< T >::const_iterator
const_pointer
template<class T> typedef const value_type* trimesh::XForm< T >::const_pointer
const_reference
template<class T> typedef const value_type& trimesh::XForm< T >::const_reference
const_reverse_iterator
template<class T> typedef ::std::reverse_iterator<const_iterator> trimesh::XForm< T >::const_reverse_iterator
difference_type
template<class T> typedef ::std::ptrdiff_t trimesh::XForm< T >::difference_type
iterator
template<class T> typedef value_type* trimesh::XForm< T >::iterator
pointer
template<class T> typedef value_type* trimesh::XForm< T >::pointer
reference
template<class T> typedef value_type& trimesh::XForm< T >::reference
reverse_iterator
template<class T> typedef ::std::reverse_iterator<iterator> trimesh::XForm< T >::reverse_iterator
size_type
template<class T> typedef ::std::size_t trimesh::XForm< T >::size_type
value_type
template<class T> typedef T trimesh::XForm< T >::value_type
Constructor & Destructor Documentation
XForm() [1/3]
template<class T> trimesh::XForm< T >::XForm (const T m0 = 1, const T m1 = 0, const T m2 = 0, const T m3 = 0, const T m4 = 0, const T m5 = 1, const T m6 = 0, const T m7 = 0, const T m8 = 0, const T m9 = 0, const T m10 = 1, const T m11 = 0, const T m12 = 0, const T m13 = 0, const T m14 = 0, const T m15 = 1) inline
XForm() [2/3]
template<class T> template<class S > trimesh::XForm< T >::XForm (S x, typename ::std::enable_if< ::std::is_arithmetic< S >::value, void >::type * = 0) inline explicit
XForm() [3/3]
template<class T> template<class S > trimesh::XForm< T >::XForm (const S & x) inline explicit
Member Function Documentation
back() [1/2]
template<class T> reference trimesh::XForm< T >::back () inline
back() [2/2]
template<class T> const_reference trimesh::XForm< T >::back () const inline
begin() [1/2]
template<class T> iterator trimesh::XForm< T >::begin () inline
Referenced by trimesh::XForm< T >::cend(), trimesh::XForm< T >::crend(), trimesh::XForm< T >::end(), and trimesh::XForm< T >::rend().
begin() [2/2]
template<class T> const_iterator trimesh::XForm< T >::begin () const inline
cbegin()
template<class T> const_iterator trimesh::XForm< T >::cbegin () const inline
cend()
template<class T> const_iterator trimesh::XForm< T >::cend () const inline
crbegin()
template<class T> const_reverse_iterator trimesh::XForm< T >::crbegin () const inline
crend()
template<class T> const_reverse_iterator trimesh::XForm< T >::crend () const inline
data() [1/2]
template<class T> pointer trimesh::XForm< T >::data () inline
data() [2/2]
template<class T> const_pointer trimesh::XForm< T >::data () const inline
end() [1/2]
template<class T> iterator trimesh::XForm< T >::end () inline
Referenced by trimesh::XForm< T >::crbegin(), and trimesh::XForm< T >::rbegin().
end() [2/2]
template<class T> const_iterator trimesh::XForm< T >::end () const inline
fromarray() [1/2]
template<class T> template<class S > static XForm<T> trimesh::XForm< T >::fromarray (const S x[3][3]) inline static
fromarray() [2/2]
template<class T> template<class S > static XForm<T> trimesh::XForm< T >::fromarray (const S x[4][4]) inline static
front() [1/2]
template<class T> reference trimesh::XForm< T >::front () inline
front() [2/2]
template<class T> const_reference trimesh::XForm< T >::front () const inline
frustum()
template<class T> static XForm<T> trimesh::XForm< T >::frustum (const T & l, const T & r, const T & b, const T & t, const T & n, const T & f) inline static
identity()
template<class T> static XForm<T> trimesh::XForm< T >::identity () inline static
Referenced by trimesh::operator>>().
max_size()
template<class T> size_type trimesh::XForm< T >::max_size () const inline
operator const T *() [1/2]
template<class T> trimesh::XForm< T >::operator const T * () inline
operator const T *() [2/2]
template<class T> trimesh::XForm< T >::operator const T * () const inline
operator T*()
template<class T> trimesh::XForm< T >::operator T* () inline
operator()() [1/4]
template<class T> reference trimesh::XForm< T >::operator() (size_type r, size_type c) inline
operator()() [2/4]
template<class T> reference trimesh::XForm< T >::operator() (int r, int c) inline
operator()() [3/4]
template<class T> const_reference trimesh::XForm< T >::operator() (size_type r, size_type c) const inline
operator()() [4/4]
template<class T> const_reference trimesh::XForm< T >::operator() (int r, int c) const inline
operator=()
template<class T> template<class S > XForm& trimesh::XForm< T >::operator= (const S & x) inline
operator[]() [1/4]
template<class T> reference trimesh::XForm< T >::operator[] (size_type i) inline
operator[]() [2/4]
template<class T> reference trimesh::XForm< T >::operator[] (int i) inline
operator[]() [3/4]
template<class T> const_reference trimesh::XForm< T >::operator[] (size_type i) const inline
operator[]() [4/4]
template<class T> const_reference trimesh::XForm< T >::operator[] (int i) const inline
ortho()
template<class T> static XForm<T> trimesh::XForm< T >::ortho (const T & l, const T & r, const T & b, const T & t, const T & n, const T & f) inline static
outer()
template<class T> template<class S > static XForm<T> trimesh::XForm< T >::outer (const S & y, const S & x) inline static
rbegin() [1/2]
template<class T> reverse_iterator trimesh::XForm< T >::rbegin () inline
rbegin() [2/2]
template<class T> const_reverse_iterator trimesh::XForm< T >::rbegin () const inline
read()
template<class T> bool trimesh::XForm< T >::read (const ::std::string & filename) inline
rend() [1/2]
template<class T> reverse_iterator trimesh::XForm< T >::rend () inline
rend() [2/2]
template<class T> const_reverse_iterator trimesh::XForm< T >::rend () const inline
rot() [1/2]
template<class T> static XForm<T> trimesh::XForm< T >::rot (const T & angle, const T & rx, const T & ry, const T & rz) inline static
Referenced by trimesh::mix(), trimesh::orthogonalize(), and trimesh::XForm< T >::rot().
rot() [2/2]
template<class T> template<class S > static XForm<T> trimesh::XForm< T >::rot (const T & angle, const S & axis) inline static
rot_into() [1/2]
template<class T> static XForm<T> trimesh::XForm< T >::rot_into (T d1x, T d1y, T d1z, T d2x, T d2y, T d2z) inline static
Referenced by trimesh::XForm< T >::rot_into().
rot_into() [2/2]
template<class T> template<class S > static XForm<T> trimesh::XForm< T >::rot_into (const S & d1, const S & d2) inline static
scale() [1/4]
template<class T> static XForm<T> trimesh::XForm< T >::scale (const T & s) inline static
Referenced by trimesh::decompose_rot(), trimesh::orthogonalize(), and trimesh::XForm< T >::scale().
scale() [2/4]
template<class T> static XForm<T> trimesh::XForm< T >::scale (const T & sx, const T & sy, const T & sz) inline static
scale() [3/4]
template<class T> static XForm<T> trimesh::XForm< T >::scale (const T & s, const T & dx, const T & dy, const T & dz) inline static
scale() [4/4]
template<class T> template<class S > static XForm<T> trimesh::XForm< T >::scale (const T & s, const S & dir) inline static
size()
template<class T> size_type trimesh::XForm< T >::size () const inline
trans() [1/2]
template<class T> static XForm<T> trimesh::XForm< T >::trans (const T & tx, const T & ty, const T & tz) inline static
Referenced by trimesh::mix(), trimesh::orthogonalize(), and trimesh::XForm< T >::trans().
trans() [2/2]
template<class T> template<class S > static XForm<T> trimesh::XForm< T >::trans (const S & t) inline static
write()
template<class T> bool trimesh::XForm< T >::write (const ::std::string & filename) const inline
Member Data Documentation
m
template<class T> T trimesh::XForm< T >::m[16] protected
Referenced by trimesh::XForm< T >::begin(), trimesh::XForm< T >::cbegin(), trimesh::XForm< T >::data(), trimesh::XForm< T >::fromarray(), trimesh::XForm< T >::operator const T *(), trimesh::XForm< T >::operator T*(), and trimesh::operator<<().
The documentation for this class was generated from the following file:
XForm.h