Symmetric NDT: test0426.cc File Reference
test0426.cc File Reference
#include <bits/stdc++.h>
#include <nav_msgs/Path.h>
#include "common/common.h"
#include "common/EgoPointClouds.h"
#include "pclmatch/wrapper.hpp"
Typedefs
typedef pcl::PointCloud< pcl::PointXYZ > PointCloud
Functions
PointCloud PointCloudFromPoints (const vector< geometry_msgs::Point > &pts)
PointCloud AugmentPointCloud (const vector< PointCloud > &pcs, const vector< vector< double >> &vxyts, const vector< ros::Time > &times, Matrix4f &Tn0)
geometry_msgs::PoseStamped MakePST (const ros::Time &time, const Matrix4f &mtx)
int main (int argc, char **argv)
Typedef Documentation
PointCloud
typedef pcl::PointCloud<pcl::PointXYZ> PointCloud
Function Documentation
AugmentPointCloud()
PointCloud AugmentPointCloud (const vector< PointCloud > & pcs, const vector< vector< double >> & vxyts, const vector< ros::Time > & times, Matrix4f & Tn0)
Referenced by main().
main()
int main (int argc, char ** argv)
MakePST()
geometry_msgs::PoseStamped MakePST (const ros::Time & time, const Matrix4f & mtx)
Referenced by main().
PointCloudFromPoints()
PointCloud PointCloudFromPoints (const vector< geometry_msgs::Point > & pts)
Referenced by main().