Symmetric NDT: mcl_eval.cc File Reference
mcl_eval.cc File Reference
#include <bits/stdc++.h>
#include <boost/program_options.hpp>
#include <Eigen/Dense>
#include <boost/random/mersenne_twister.hpp>
#include <boost/random/normal_distribution.hpp>
#include "common/common.h"
#include <sndt/ndt_visualizations.h>
Classes
struct Eigen::internal::scalar_normal_dist_op< Scalar >
struct Eigen::internal::functor_traits< scalar_normal_dist_op< Scalar > >
Namespaces
Eigen
Eigen::internal
Functions
Eigen::MatrixXd GenerateSamples (Eigen::VectorXd mean, Eigen::MatrixXd covar, int size, int nn, const Eigen::internal::scalar_normal_dist_op< double > &randN)
void StringToMeanAndCov (string str, Vector2d &mean, Matrix2d &cov)
void StringToCenter (string str, Vector2d &cen)
vector< double > ComputeMeanAndCov (const Eigen::Vector2d &p, const Eigen::Vector2d &q, const Eigen::Vector2d &np, const Eigen::Vector2d &nq, const Eigen::Matrix2d &pcov, const Eigen::Matrix2d &qcov, const Eigen::Matrix2d &npcov, const Eigen::Matrix2d &nqcov)
int main (int argc, char **argv)
Function Documentation
ComputeMeanAndCov()
vector<double> ComputeMeanAndCov (const Eigen::Vector2d & p, const Eigen::Vector2d & q, const Eigen::Vector2d & np, const Eigen::Vector2d & nq, const Eigen::Matrix2d & pcov, const Eigen::Matrix2d & qcov, const Eigen::Matrix2d & npcov, const Eigen::Matrix2d & nqcov)
Referenced by main().
GenerateSamples()
Eigen::MatrixXd GenerateSamples (Eigen::VectorXd mean, Eigen::MatrixXd covar, int size, int nn, const Eigen::internal::scalar_normal_dist_op< double > & randN)
Referenced by main().
main()
int main (int argc, char ** argv)
StringToCenter()
void StringToCenter (string str, Vector2d & cen)
Referenced by main().
StringToMeanAndCov()
void StringToMeanAndCov (string str, Vector2d & mean, Matrix2d & cov)
Referenced by main().