Symmetric NDT: eigen_utils.h File Reference
common/include/common/eigen_utils.h File Reference
#include <angles/angles.h>
#include <std_msgs/Float64MultiArray.h>
#include <tf2_eigen/tf2_eigen.h>
#include <tf2_geometry_msgs/tf2_geometry_msgs.h>
#include <Eigen/Dense>
Functions
Eigen::Affine3d Affine3dFromXYZRPY (const Eigen::Vector3d &xyz, const Eigen::Vector3d &rpy)
Eigen::Affine3d Affine3dFromAffine2d (const Eigen::Affine2d &aff)
Eigen::Affine3d Affine3dFromMatrix3d (const Eigen::Matrix3d &mtx)
Eigen::Affine3d Affine3dFromMatrix4f (const Eigen::Matrix4f &mtx)
Eigen::Matrix< double, 6, 1 > XYZRPYFromAffine3d (const Eigen::Affine3d &mtx)
Eigen::Matrix< double, 6, 1 > XYZRPYFromMatrix4f (const Eigen::Matrix4f &mtx)
Eigen::Vector3d XYTRadianFromMatrix3d (const Eigen::Matrix3d &mtx)
Eigen::Vector3d XYTDegreeFromMatrix3d (const Eigen::Matrix3d &mtx)
Eigen::Matrix3d Matrix3dFromXYTRadian (const Eigen::Vector3d &xyt)
Eigen::Matrix3d Matrix3dFromXYTDegree (const Eigen::Vector3d &xyt)
Eigen::Matrix3d Matrix3dFromMatrix4f (const Eigen::Matrix4f &mtx)
Eigen::Matrix4f Matrix4fFromMatrix3d (const Eigen::Matrix3d &mtx)
Eigen::Matrix4f Matrix4fFromXYTRadian (const Eigen::Vector3d &xyt)
geometry_msgs::TransformStamped TstFromAffine3d (const Eigen::Affine3d &T, const ros::Time &stamp, const std::string &frame_id, const std::string &child_frame_id)
geometry_msgs::TransformStamped TstFromMatrix4f (const Eigen::Matrix4f &T, const ros::Time &stamp, const std::string &frame_id, const std::string &child_frame_id)
Eigen::Affine3d Conserve2DFromAffine3d (const Eigen::Affine3d &T)
Eigen::Vector2d TransNormRotDegAbsFromMatrix3d (const Eigen::Matrix3d &mtx)
geometry_msgs::PoseStamped MakePoseStampedMsg (const ros::Time &time, const Eigen::Matrix4f &mtx)
Function Documentation
Affine3dFromAffine2d()
Eigen::Affine3d Affine3dFromAffine2d (const Eigen::Affine2d & aff)
Referenced by Affine3dFromMatrix3d().
Affine3dFromMatrix3d()
Eigen::Affine3d Affine3dFromMatrix3d (const Eigen::Matrix3d & mtx)
Affine3dFromMatrix4f()
Eigen::Affine3d Affine3dFromMatrix4f (const Eigen::Matrix4f & mtx)
Referenced by MakePoseStampedMsg(), TstFromMatrix4f(), and XYZRPYFromMatrix4f().
Affine3dFromXYZRPY()
Eigen::Affine3d Affine3dFromXYZRPY (const Eigen::Vector3d & xyz, const Eigen::Vector3d & rpy)
Referenced by Conserve2DFromAffine3d().
Conserve2DFromAffine3d()
Eigen::Affine3d Conserve2DFromAffine3d (const Eigen::Affine3d & T)
Referenced by cb(), main(), and MakeGtLocal().
MakePoseStampedMsg()
geometry_msgs::PoseStamped MakePoseStampedMsg (const ros::Time & time, const Eigen::Matrix4f & mtx)
Referenced by main().
Matrix3dFromMatrix4f()
Eigen::Matrix3d Matrix3dFromMatrix4f (const Eigen::Matrix4f & mtx)
Matrix3dFromXYTDegree()
Eigen::Matrix3d Matrix3dFromXYTDegree (const Eigen::Vector3d & xyt)
Matrix3dFromXYTRadian()
Eigen::Matrix3d Matrix3dFromXYTRadian (const Eigen::Vector3d & xyt)
Referenced by Matrix3dFromMatrix4f(), Matrix3dFromXYTDegree(), and Matrix4fFromXYTRadian().
Matrix4fFromMatrix3d()
Eigen::Matrix4f Matrix4fFromMatrix3d (const Eigen::Matrix3d & mtx)
Referenced by main(), and Matrix4fFromXYTRadian().
Matrix4fFromXYTRadian()
Eigen::Matrix4f Matrix4fFromXYTRadian (const Eigen::Vector3d & xyt)
TransNormRotDegAbsFromMatrix3d()
Eigen::Vector2d TransNormRotDegAbsFromMatrix3d (const Eigen::Matrix3d & mtx)
Referenced by cb().
TstFromAffine3d()
geometry_msgs::TransformStamped TstFromAffine3d (const Eigen::Affine3d & T, const ros::Time & stamp, const std::string & frame_id, const std::string & child_frame_id)
Referenced by TstFromMatrix4f().
TstFromMatrix4f()
geometry_msgs::TransformStamped TstFromMatrix4f (const Eigen::Matrix4f & T, const ros::Time & stamp, const std::string & frame_id, const std::string & child_frame_id)
XYTDegreeFromMatrix3d()
Eigen::Vector3d XYTDegreeFromMatrix3d (const Eigen::Matrix3d & mtx)
Referenced by TransNormRotDegAbsFromMatrix3d().
XYTRadianFromMatrix3d()
Eigen::Vector3d XYTRadianFromMatrix3d (const Eigen::Matrix3d & mtx)
Referenced by XYTDegreeFromMatrix3d().
XYZRPYFromAffine3d()
Eigen::Matrix<double, 6, 1> XYZRPYFromAffine3d (const Eigen::Affine3d & mtx)
Referenced by Conserve2DFromAffine3d(), and XYZRPYFromMatrix4f().
XYZRPYFromMatrix4f()
Eigen::Matrix<double, 6, 1> XYZRPYFromMatrix4f (const Eigen::Matrix4f & mtx)
Referenced by Matrix3dFromMatrix4f().