Symmetric NDT: SNDTMap Class Reference
SNDTMap Class Reference
#include <sndt_map.h>
Public Member Functions
SNDTMap (double cell_size)
Construct a new SNDTMap object.
~SNDTMap ()
void LoadPointsAndNormals (const std::vector< Eigen::Vector2d > &points, const std::vector< Eigen::Vector2d > &normals)
Load points into the SNDTMap.
void LoadPointsWithCovariancesAndNormals (const std::vector< Eigen::Vector2d > &points, const std::vector< Eigen::Matrix2d > &point_covs, const std::vector< Eigen::Vector2d > &normals)
Load points and point covariances into the SNDTMap.
std::vector< std::shared_ptr< SNDTCell > > PseudoTransformCells (const Eigen::Affine2d &T, bool include_data=false) const
Perform transformation to SNDTMap.
SNDTCell * GetCellAndAllocate (const Eigen::Vector2d &point)
Get and allocate the cell by a given point.
const SNDTCell * GetCellForPoint (const Eigen::Vector2d &point) const
Get the cell by a given point.
virtual std::string ToString () const override
Convert the information of the SNDTMap to a string.
std::vector< Eigen::Vector2d > GetPoints () const
Get the Points object.
std::vector< Eigen::Vector2d > GetNormals () const
Get the Normals object.
size_t size () const
std::vector< SNDTCell * >::iterator begin ()
std::vector< SNDTCell * >::const_iterator begin () const
std::vector< SNDTCell * >::iterator end ()
std::vector< SNDTCell * >::const_iterator end () const
Public Member Functions inherited from MapInterface
MapInterface (double cell_size)
Construct a new MapInterface object.
virtual ~MapInterface ()=default
Eigen::Vector2i GetIndexForPoint (const Eigen::Vector2d &point) const
Get the index by a given point.
double GetCellSize () const
Eigen::Vector2d GetMapSize () const
Eigen::Vector2d GetMapCenter () const
Additional Inherited Members
Protected Member Functions inherited from MapInterface
void GuessMapSize (const std::vector< Eigen::Vector2d > &points)
Update mata information of MapInterface by points.
bool IsValidIndex (const Eigen::Vector2i &index) const
Check the validity of an index.
Protected Attributes inherited from MapInterface
bool is_loaded_
double cell_size_
Eigen::Vector2d map_size_
Eigen::Vector2d map_center_
Eigen::Vector2i map_center_index_
Eigen::Vector2i cellptrs_size_
Constructor & Destructor Documentation
SNDTMap()
SNDTMap::SNDTMap (double cell_size) explicit
Construct a new SNDTMap object.
Parameters
cell_size Cell size of the SNDTMap
~SNDTMap()
SNDTMap::~SNDTMap ()
Member Function Documentation
begin() [1/2]
std::vector<SNDTCell *>::iterator SNDTMap::begin () inline
Referenced by GetNormals(), GetPoints(), and PseudoTransformCells().
begin() [2/2]
std::vector<SNDTCell *>::const_iterator SNDTMap::begin () const inline
end() [1/2]
std::vector<SNDTCell *>::iterator SNDTMap::end () inline
Referenced by GetNormals(), GetPoints(), and PseudoTransformCells().
end() [2/2]
std::vector<SNDTCell *>::const_iterator SNDTMap::end () const inline
GetCellAndAllocate()
SNDTCell * SNDTMap::GetCellAndAllocate (const Eigen::Vector2d & point)
Get and allocate the cell by a given point.
Parameters
point Input point
Referenced by LoadPointsAndNormals(), and LoadPointsWithCovariancesAndNormals().
GetCellForPoint()
const SNDTCell * SNDTMap::GetCellForPoint (const Eigen::Vector2d & point) const
Get the cell by a given point.
Parameters
point Input point
Referenced by SNDTMatch().
GetNormals()
std::vector< Eigen::Vector2d > SNDTMap::GetNormals () const
Get the Normals object.
Note
The normals are retrived from active_cells_, which does not necessarily equal to the original input
GetPoints()
std::vector< Eigen::Vector2d > SNDTMap::GetPoints () const
Get the Points object.
Note
The points are retrived from active_cells_, which does not necessarily equal to the original input
Referenced by SNDTMatch().
LoadPointsAndNormals()
void SNDTMap::LoadPointsAndNormals (const std::vector< Eigen::Vector2d > & points, const std::vector< Eigen::Vector2d > & normals)
Load points into the SNDTMap.
Parameters
points Points to load
normals Normals to load
Note
points and normals should have the same size
LoadPointsWithCovariancesAndNormals()
void SNDTMap::LoadPointsWithCovariancesAndNormals (const std::vector< Eigen::Vector2d > & points, const std::vector< Eigen::Matrix2d > & point_covs, const std::vector< Eigen::Vector2d > & normals)
Load points and point covariances into the SNDTMap.
Parameters
points Points to load
point_covs Point covariances to load
normals Normals to load
Note
points, point_covs, and normals should have the same size
Referenced by MakeSNDTMap().
PseudoTransformCells()
std::vector< std::shared_ptr< SNDTCell > > SNDTMap::PseudoTransformCells (const Eigen::Affine2d & T, bool include_data = false) const
Perform transformation to SNDTMap.
Parameters
T Transformation
include_data Transform data as well (default false)
Returns
Transformed cells
Referenced by SNDTMatch().
size()
size_t SNDTMap::size () const inline
ToString()
std::string SNDTMap::ToString () const override virtual
Convert the information of the SNDTMap to a string.
Implements MapInterface.
The documentation for this class was generated from the following files:
sndt_map.h
sndt_map.cc